### ISSUE TITLE
Add performance section about brianium/paratest

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#103]

**Comment by benr77** [comment]
Is Paratest supported by Foundry? 

I've tried enabling it and my tests got SLOWER for some reason. I haven't investigated further at this stage though. Happy to help if you need anyone to test.

**Comment by nikophil** [comment]
I don't see any blocker which would prevent to use Foundry and Paratest together :thinking: 

I'm actually using them together on one of my projects (on a project with mongodb, not sql).
I would be curious to know why your tests got slower

**Comment by benr77** [comment]
When I say slower I mean A LOT slower. The log file is showing that it's fully recreating the database for every test. 

Without Paratest, it does this only once at the start of the test run, because I use DAMADoctrineTestBundle.

**Comment by nikophil** [comment]
if you use dama, it should only recreate the db as many times as you have parallel threads, this may deserve to investigate a little bit more :thinking:

**Comment by benr77** [comment]
Yes, that was what I was expecting too. I have 8 threads but it's definitely recreating the DB more than 8 times. I will dig a bit deeper and report back anything I discover.

**Comment by kbond** [comment]
I use Dama and paratest together on an app using mysql. It does work. I have the following in my `tests/bootstrap.php`:

```php
if (false === (bool) $_SERVER['APP_DEBUG'] && null === ($_SERVER['TEST_TOKEN'] ?? null)) {
    /*
     * Ensure a fresh cache when debug mode is disabled. When using paratest, this
     * file is required once at the very beginning, and once per process. Checking that
     * TEST_TOKEN is not set ensures this is only run once at the beginning.
     */
    (new Filesystem())->remove(__DIR__.'/../var/cache/test');
}
```

I think that is more because I run my tests with `debug=false` (for increased speed).

Are you using the `TEST_TOKEN` in your db name like [shown here](https://github.com/symfony/recipes/blob/6f47092b8fbebe82b1e79f06e5edd9baa2c3fc8f/doctrine/doctrine-bundle/2.10/config/packages/doctrine.yaml#L29)?

**Comment by benr77** [comment]
Yes, I use `TEST_TOKEN` as the DB name suffix. 

I have added that code to the `tests/bootstrap.php` -  it's handy but previously I was just clearing the cache before a test run via my Makefile, so that's not made any difference.

I have added some logging to Foundry's `ORMDatabaseResetter` and it's definitely dropping and recreating the database for every test, which is causing the slowdown. Without Paratest it's only doing this once at the start of the test run.

Could it be the DAMA configuration? I have:

```php
$containerConfigurator->extension('dama_doctrine_test', [
        'enable_static_connection' => true,
        'enable_static_meta_data_cache' => true,
        'enable_static_query_cache' => true,
    ]);
```

**Comment by kbond** [comment]
Other than being super slow, do the tests all still pass? Seems like dama isn't correctly being detected by foundry. Can you add some logging [here](https://github.com/zenstruck/foundry/blob/08ea145121ba90d08f9ed90b51a7fe531a81194b/src/Test/ORMDatabaseResetter.php#L56) to see if foundry is indeed detecting dama?

> Could it be the DAMA configuration? I have:

That's the default so no issue there.

**Comment by benr77** [comment]
I added some logging there and Dama is being detected correctly. But still the DB is reset. 

The dropping of the DB happens [here](https://github.com/zenstruck/foundry/blob/08ea145121ba90d08f9ed90b51a7fe531a81194b/src/Test/ORMDatabaseResetter.php#L128) in `dropAndResetDatabase()` rather than in `resetSchema()`.

**Comment by kbond** [comment]
Is there a way you can confirm the database is being reset once per test or once per test file? Edit: ok it looks like you already did this and it is before every test 🤔?

**Comment by benr77** [comment]
No, it seems the DB reset happens once per test FILE, and then the various tests in the file all run.

EDIT: My comment above was wrong - I just assumed it was before every test, but now the logging is showing it's definitely once per file.

**Comment by kbond** [comment]
Ok, so it seems like [this static variable](https://github.com/zenstruck/foundry/blob/08ea145121ba90d08f9ed90b51a7fe531a81194b/src/Test/DatabaseResetter.php#L28) isn't being kept as true between test files on the same paratest process

Can you try running paratest like this?

```cli
vendor/bin/paratest --runner WrapperRunner
```

I just ran my test suite w/o `--runner WrapperRunner` and it is super slow.

**Comment by kbond** [comment]
From the [docs](https://github.com/paratestphp/paratest/tree/6.x#optimizing-speed):

> The default Runner for PHPUnit spawns a new process for each testcase (or method in functional mode). This provides the highest compatibility but comes with the cost of many spawned processes and a bootstrapping for each process. Especially when you have a slow bootstrapping in your tests (like a database setup) you should try the WrapperRunner with --runner WrapperRunner. It spawns one "worker"-process for each parallel process (-p), executes the bootstrapping once and reuses these processes for each test executed. That way the overhead of process spawning and bootstrapping is reduced to the minimum.

This will not be needed in [paratest 7](https://github.com/paratestphp/paratest/releases/tag/v7.0.0).

**Comment by benr77** [comment]
You are right! It's completely sorted the issue. Thank you so much!

**Comment by kbond** [comment]
Excellent, I'm going to get on documenting this before I forget this nuance again.
