### ISSUE TITLE
Add a randomOrCreate() method

### ISSUE THREAD

**Issue by wouterj** [zenstruck/foundry#104]
Whenever I have an object that depends on another object (e.g. "Post" depends on a "User" as the author), I use `UserFactory::random()` in the initialize. However, this at the moment requires to have called `UserFactory::new()->create()` before calling `PostFactory::new()->create()`.

I suggest adding a `randomOrCreate()` method. To be discussed: should this have an optional `$attributes` argument?

**Comment by kbond** [comment]
> should this have an optional $attributes argument?

I think no because if an entity exists in the db, it wouldn't have these attributes. Or are you thinking that if attributes are passed, it uses `findOrCreate`? Either way, I think it may be confusing.
