### ISSUE TITLE
[Suggestion] Allow to get the object from assertExists()

### ISSUE THREAD

**Issue by wouterj** [zenstruck/foundry#105]
```php
UserFactory::repository()->assertExists([
    'fullName' => $this->userData['full-name'],
    'username' => $this->userData['username'],
]);

$user = UserFactory::repository()->find(['fullName' => $this->userData['full-name'], 'username' => $this->userData['username']])->object();
$this->assertTrue($container->get('security.password_encoder')->isPasswordValid($user, $this->userData['password']));
```

It would be nice if `$user` is returned from `assertExists()`, to avoid duplication. However, this will break the current fluent interface, so I'm not sure if (or how) we should fix this.

**Comment by kbond** [comment]
> However, this will break the current fluent interface

Hmm, yeah, didn't think of that. What about a `findOrFail()` method?

**Comment by wouterj** [comment]
See https://github.com/zenstruck/foundry/issues/106 for an alternative fix (but maybe more complex than this one)
