### ISSUE TITLE
Questioning about the deprecation of instance method "createMany":  MyFactory::new()->createMany(10)

### ISSUE THREAD

**Issue by mpiot** [zenstruck/foundry#115]
Hi,
I've a question about the deprecation of the usage of instance method `->createMany()` and its replacement by the static `::createMany()` method.

In many cases I use something like:
```php
MyFactory::new()
    ->firstState()
    ->secondState('myArg')
    ->createMany(10)
;
```

I've not find a way to continue to do that with the static method `::createMany()`. By checking the code and the doc, I've seen we can pass sometimes pass state function names in the `::new()` static function but this don't solve the problem (and do not support args).

I think I've miss something :D Thanks

**Comment by wouterj** [comment]
You can use `many()`:

```php
MyFactory::new()
    ->firstState()
    ->secondState('myArg')
    ->many(10)
    ->create()
;
```

My idea with this new feature was to make the "simple" (and we assumed most common) the shortest, making the more complex use-cases a bit more complex.

**Comment by mpiot** [comment]
@wouterj Oh oki, I've not see the `->many(10)->create();` but it's everywherein the doc... Damn :/

Thanks a lot for your help
