### ISSUE TITLE
Add repository methods to ModelFactory as static methods

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#124]
#123 made me think that more `RepositoryProxy` methods should be available on the `ModelFactory` as static methods:

- [x] `PostFactory::count(): int`
- [x] `PostFactory::assert()->empty(): void`
- [x] `PostFactory::assert()->count(): void`
- [x] `PostFactory::assert()->countGreaterThan(): void`
- [x] `PostFactory::assert()->countGreaterThanOrEqual(): void`
- [x] `PostFactory::assert()->countLessThan(): void`
- [x] `PostFactory::assert()->countLessThanOrEqual(): void`
- [x] `PostFactory::assert()->exists(): void` ~possible solution to #105~
- [x] `PostFactory::assert()->notExists(): void`
- [x] `PostFactory::truncate(): void`
- [x] `PostFactory::find(): Proxy` possible solution to #105
- [x] ~`PostFactory::findAll(): Proxy[]`~ `PostFactory::all(): Proxy[]`
- [x] `PostFactory::findBy(): Proxy[]`
- [x] ~`PostFactory::findOneBy(): Proxy`~ merge with `find()` above
- [x] `PostFactory::first(): Proxy`
- [x] `PostFactory::last(): Proxy`

@weaverryan, @wouterj WDYT? I'm wondering if we should use `__callStatic` here to accomplish?

This could possibly make `RepositoryProxy` just an implementation detail and not something you'd ever really need to use in user-land.

**Comment by wouterj** [comment]
I like it! (making it internal in 1.x would also allow removing the `RepositoryProxy` completely in 2.0)

It would add quite some methods to the factory though. Maybe an dedicated `assert()` helper would be nice?

```php
PostFactory::assert()->exists(...);
PostFactory::assert()->count();
```

**Comment by kbond** [comment]
Good call - I've updated the issue description to show the proposed API.

**Comment by kbond** [comment]
Hmm, with the new assert helper, `PostFactory::assert()->exists(): Proxy` (solution to #105) we wouldn't be able to autocomplete... What about: `PostFactory::assert()->exists(): void` and having `PostFactory::find(): Proxy` make the assertion? I want to have the methods that return a `Proxy` (find/first/last) throw an exception if no entity is found so either way an exception would be thrown.
