### ISSUE TITLE
Configure faker starter seed

### ISSUE THREAD

**Issue by mortezakarimi** [zenstruck/foundry#128]
Sometimes we want to create fixtures data always using the same seed for generating data
For example for running a test

https://github.com/fzaninotto/Faker#seeding-the-generator

**Comment by kbond** [comment]
Do you want to always use the same seed for all factories? You can create a faker service and [use in the bundle config](https://github.com/zenstruck/foundry#faker). Does that work for you?

Alternatively, I believe just calling `Factory::faker()->seed($yourSeed)` before generating your factories would work.

**Comment by kbond** [comment]
I'm guessing this worked. If not, let me know and we can reopen.
