### ISSUE TITLE
Why is using \Zenstruck\Foundry\Test\Factories trait needed?

### ISSUE THREAD

**Issue by knnnrd** [zenstruck/foundry#140]
Hello,

First of all I want to say this library is looking really nice. I'm in the progress of converting from liip/LiipTestFixturesBundle to this, but I have a question regarding the usage of the \Zenstruck\Foundry\Test\Factories trait.

My test seems to run fine regardless if I include the trait or not. Is it really necessary to use it?

Also, I don't really get why it's that important to shut down the kernel in certain cases (described here: https://github.com/zenstruck/foundry#enable-foundry-in-your-testcase). `self::createClient();` internally handles shutting down the kernel.

Thanks in advance.

**Comment by kbond** [comment]
> My test seems to run fine regardless if I include the trait or not. Is it really necessary to use it?

There are 2 main reasons for the `Factories` trait:
1. For using foundry in non-kernel tests (plain unit tests). This boots foundry in a usable state (entities won't be persisted as there is no database in this context).
2. When using in a kernel test, the trait boots foundry with some special configuration that allows your entities to be refreshed through kernel reboots. ie you create some factories, then shutdown the kernel, use self::createClient() to make some web requests, then check the state of the entities created at the beginning. Without the trait, you wouldn't be able to refresh the entities after the reboot. It is possible your tests don't do this so this is why it works without.

> Also, I don't really get why it's that important to shut down the kernel in certain cases

I actually think that may no longer be necessary as we changed some logic. I'll confirm and update the docs if that is no longer the case. The trait now uses an isolated kernel.

**Comment by knnnrd** [comment]
>     2\. Without the trait, you wouldn't be able to refresh the entities after the reboot. It is possible your tests don't do this so this is why it works without.

Indeed my test does not refresh the entities after the web request. Thanks for the quick response!

**Comment by kbond** [comment]
> I'll confirm and update the docs if that is no longer the case. The trait now uses an isolated kernel.

I confirmed and I'm removing that note in #142.
