### ISSUE TITLE
False positive for auto_refresh_proxies deprecation

### ISSUE THREAD

**Issue by jrushlow** [zenstruck/foundry#141]
In a PHPUnit 9.5 test w/ Symfony 5.2, the following edge triggers 

```
Remaining direct deprecation notices (1)

1x: Since zenstruck\foundry 1.9: Not explicitly configuring the default proxy auto-refresh is deprecated and will default to "true" in 2.0. Use "zenstruck_foundry.auto_refresh_proxies" in the bundle config or TestState::enableDefaultProxyAutoRefresh()/disableDefaultProxyAutoRefresh().
```

```php
// class ATest extends TestCase

use Factories;

public function testUnitTest(): void
{
    // ... create a few mocks

    $object = AFactory::new()->withoutPersisting()->create();

    ...
}
```

I've `--force`'d the recipe and have `zenstruck_foundry.auto_refresh_proxies` defined/set in `test` & `dev` configs. This unit test does not user the Symfony Kernel nor interact with the database. 

Declaring `TestState::disableDefaultProxyAutoRefresh();` before xor after calling the factory has no affect on the deprecation.

**Comment by kbond** [comment]
> Declaring TestState::disableDefaultProxyAutoRefresh(); before xor after calling the factory has no affect on the deprecation.

The `Factories` trait trait has a before test hook that is what's triggering the deprecation. Try calling `TestState::disableDefaultProxyAutoRefresh();` in `tests/bootstrap.php`.

But, certainly when using foundry in a non-kernel test, this deprecation shouldn't be triggered as auto-refreshing isn't possible when using foundry outside of a database context.

**Comment by kbond** [comment]
I believe #143 will fix this.
