### ISSUE TITLE
How to migrate database during test

### ISSUE THREAD

**Issue by knnnrd** [zenstruck/foundry#144]
Hi, I'm trying to use the `ResetDatabase` trait, but it only creates the database tables for the entities that are tracked by Doctrine. However we have many database columns which are not tracked by Doctrine but should be there during a test.

I looked at the source code but it doesn't seem like there is any support for this. Is this intended? Do I need to implement my own solution?

Thanks!

**Comment by kbond** [comment]
Hello, yes, this was intended as I didn't expect many people to have a different database structure that what is created with `doctrine:schema:create`. You're not the first person to have inquired about this.

How would you expect such a feature to work?

Currently, `ResetDatabase` has the following _flow_:
1. Before **first** test using the trait: 
    1. `doctrine:database:drop`
    2. `doctrine:database:create`
    3. `doctrine:schema:create`
2. Before **each** test using the trait:  (skips if DAMADoctrineTestBundle is enabled)
    1. `doctrine:schema:drop`
    2. `doctrine:schema:create`

I'm envisioning a `MigrateDatabase` trait with the following flow:
1. Before **first** test using the trait: 
    1. `doctrine:database:drop`
    2. `doctrine:database:create`
    3. `doctrine:migrations:migrate`
2. Before **each** test using the trait: (skips if DAMADoctrineTestBundle is enabled)
    1. `doctrine:migrations:migrate first` (I believe the first keyword resets everything)
    2. `doctrine:migrations:migrate`

What do you think? This has the potential to make your tests quite slow (if you have a lot of migrations) so out of the box optional integration with DAMADoctrineTestBundle (like `ResetDatabase`) would be a must.

**Comment by wouterj** [comment]
Btw, you can describe all manually added columns and tables to Doctrine (which also works nicely with the DoctrineMigrationBundle).

Unfortunately, I couldn't find any docs about this. You can see an example of this here: https://github.com/symfony/symfony/blob/cd7702f40c8e4e2486a4433849eced81bcef2bfa/src/Symfony/Bridge/Doctrine/SchemaListener/RememberMeTokenProviderDoctrineSchemaSubscriber.php
After creating the class, you must create a service for it and add the `doctrine.event_subscriber` tag.

**Comment by kbond** [comment]
@wouter, so this triggers `doctrine:schema:create` to add these?

**Comment by wouterj** [comment]
@kbond this listener is called when doctrine builds up his knowledge of the "schema" based on the entities (which is used by `doctrine:schema:*` and `doctrine:migrations:*`). This allows adding more tables/columns to the schema, so that Doctrine is aware of them.

**Comment by knnnrd** [comment]
>     * full-database

I think the flow you describe for a `MigrateDatabase` trait sounds about right. We don't have down migrations and I guess a lot of projects don't have them. I did a quick test how `doctrine:schema:drop --full-database --force` works, and I'm getting an error:
> SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails"

If you use the `--dump-sql` option you can see why this could happen. It's just a list of `DROP TABLE ...` statements in alphabetical order.

Automatic integration with DAMADoctrineTestBundle is indeed a must have.

**Comment by kbond** [comment]
> I did a quick test how doctrine:schema:drop --full-database --force works, and I'm getting an error

Hmm, that is indeed a problem... I don't know that is a great solution anyway. It's possible migrations may add "data" to your tables.

I'm not seeing how we can add this without requiring DAMADoctrineTestBundle.

Are you using DAMADoctrineTestBundle now? If so, what about removing the `ResetDatabase` trait from your tests and before your test suite runs, run the following:

```bash
bin/console doctrine:database:drop --force --if-exists --env=test
bin/console doctrine:database:create --env=test
bin/console doctrine:migrations:migrate --env=test
```

This puts your test db in a current migration state before the test suite runs and DAMADoctrineTestBundle will rollback to this after each test.

**Comment by knnnrd** [comment]
> I'm not seeing how we can add this without requiring DAMADoctrineTestBundle (unless we drop/create the db before every test which would be really slow I think).

Requiring DAMADoctrineTestBundle should be the default, but I also think people using this library should just be aware of the fact that things can get slow in certain circumstances. E.g.: we have another application which interacts with a really old database, the tables all use MyISAM as the storage engine, so no transactions, so DAMADoctrineTestBundle won't do anything.

We currently have our own PHPUnit `BeforeTestHook` which does exactly what you are suggesting. Ideally we would like to get rid of our own implementation and just use one provided by the library.

I also think a lot of applications insert data through database migrations (ours do).

Since this library already provides the `ResetDatabase` trait, I guess there should also be a `MigrateDatabase` variant. This variant should drop, create and migrate the database before the first test. Then if DAMADoctrineTestBundle is not detected it should drop the tables/database and migrate again.
The [OnSchemaDropTable](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/events.html#onschemadroptable-event) event might be a way to disable foreign key constraints, which means `doctrine:schema:drop --full-database` could be used instead of dropping the whole database?

**Comment by kbond** [comment]
> Since this library already provides the ResetDatabase trait, I guess there should also be a MigrateDatabase variant.

I'm now thinking to add to `ResetDatabase`. Almost the same logic, just different "commands" being run. More importantly, I don't want users to think they can mix and match. I'm thinking a config value/env variable: `FOUNDRY_RESET_MODE=migrate`

I'll play with adding this feature. I think if DAMADoctrineTestBundle isn't detected, I'll drop/create the db (to get the feature out quicker). It's slow but hopefully this should prompt users to look at DAMADoctrineTestBundle.

**Comment by kbond** [comment]
@knnnrd, would you be able to test #145 with your app?

**Comment by knnnrd** [comment]
@kbond I will try to test this somewhere during the next few weeks, then I will get back to you.
