### ISSUE TITLE
Support doctrine/odm

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#148]
Hello,

actually the library works like a charm for mongo except two things (at least for simple use cases):
- `DatabaseResetter` is coupled with `doctrine/orm` https://github.com/zenstruck/foundry/blob/master/src/Test/DatabaseResetter.php#L50
- The library injects `doctrine` service, but this service does not exist with odm (it's named `doctrine_mongodb`)

Maybe it would worth fixing both of these problems to make the library support doctrine/odm?
If that's OK, I would be happy to provide a PR

/cc @wouterj

**Comment by kbond** [comment]
Hey @nikophil, thanks for testing this - I really had no idea how this would work with a persistence layer other than the orm.

Yes, I'd love to support this fully so a PR would be great.

Is it common for an app to use both mongo and the orm together? Should we support this?

**Comment by nikophil** [comment]
Hi @kbond 

> Yes, I'd love to support this fully so a PR would be great.
Nice to here, I'm gonna work on that :)

> Is it common for an app to use both mongo and the orm together?
I've never seen a project where both are used, even if both are not incompatible.

> Should we support this?
I don't think this would be useful, unless if someone asks for it in the future. If you're OK I'd rather work on the simple implementation where we only support one case at a time (maybe we'll add a warning in the readme about the restriction?).

**Comment by kbond** [comment]
> If you're OK I'd rather work on the simple implementation

Yes, I agree, supporting both sounds complex...

**Comment by smilesrg** [comment]
>I don't think this would be useful, unless if someone asks for it in the future.

It should be useful! I have seen projects that were using both MySQL and MongoDB

**Comment by majermi4** [comment]
It would be awesome if Foundry considered ODM as much as ORM. :-) We have a huge project based on Doctrine ODM and the Alice based fixtures are getting out of hand so I argued we should switch to Foundry during our last developer meeting. But then the question came: "Well, does it actually support Doctrine ODM?" and we found this thread 😢

**Comment by kbond** [comment]
Yeah, originally, I planned this bundle to work with any doctrine/persistence implementation but as I added features it tightly coupled it to orm only as that's what I use. There's a stalled PR to add ODM support but it is complex. I hope to pick it up again in the future when I have time.

**Comment by wouterj** [comment]
As it's open source, maybe @majermi4's company can reserve some time to see if they can get the ODM PR (https://github.com/zenstruck/foundry/pull/157) to a mergeable state? 

@kbond is there anything you need to round up that PR?

**Comment by majermi4** [comment]
I had a quick look at the code in the PR but I fear that I won't have enough time in the near future that I'd be able to wrap up something like this :-/ 

However, I could try to explain to management of our company the importance of having this and get some financial support, would that be interesting to somebody?

**Comment by majermi4** [comment]
Btw, yesterday I tried using the #153 branch to create dev/db fixtures in our new project using ODM and except one little fix, it seems to work smoothly. 

I'd be personally really interested in getting this to work so if I can help in any way, I'd be happy to team up on this. I can provide some mongo/ODM ecosystem knowledge and early testing on code-base that utilizes nearly all the ODM features. I can also implement clearly defined sub-tasks for this but I don't think I'd be able to do it all on my own as I don't have that deep knowledge of Foundry internals, its development directions and all the context. :-)

**Comment by kbond** [comment]
Awesome, @majermi4, glad to hear you have something at least somewhat working.

I've added ODM support (or at least making it easier to add ODM support) to our [2.0 ideas/roadmap issue](https://github.com/zenstruck/foundry/issues/110). I think refactoring the internals to isolate orm-specific logic would make adding support much easier.

**Comment by sakalys** [comment]
@kbond, I don't think that anyone is working on this anymore, ain't it?

Is there any way others could contribute? Not sure how could I do that exactly, but I definitely have the need to have ODM support. Maybe I could contribute, but I'd need some guidance on the way "things are done here".

**Comment by smilesrg** [comment]
@sakalys if you want to contribute, then just do a fork, create a PR and you're done! :-)

**Comment by kbond** [comment]
I merged a few outstanding PR's into #153. I'm going to attempt to rebase and cleanup that PR as best I can but I'll likely need some help after that to finalize.

**Comment by kbond** [comment]
Update: https://github.com/zenstruck/foundry/pull/153#issuecomment-1003456244
