### ISSUE TITLE
ModelFactory::random() : How to get an unique random element ?

### ISSUE THREAD

**Issue by Tilotiti** [zenstruck/foundry#149]
Hello,

I have a question for you : 

I have 3 entities :

- `Customer`
- `Campaign`
- `Contact`

The `Contact` entity has a unique constraint on the relation `Customer` & `Campaign`, so you can have only one `Contact` by `Customer` and `Campaign` couple (we don't want to contact many times a customer for the same campaign).

When I run the script, I keep my `Campaign` database, but I truncate the `Customer` and `Contact` databases.

The logic in my application enforce me to start to use the `CustomerFactory`, then, to use the `ContactFactory`, I'm not allowed to create a new `Customer` with the `ContactFactory`.

I generate some `Customer` objects, then, for each `Campaign`, I use the `ContactFactory::createMany()`method, and I use, by default, the `CustomerFactory::random()` to select a random `Customer`.

But then I get a problem : the unique constraint is not respected. I sometime create multiple `Contact` with the same `Customer` and the same `Campaign`.

Is there any way to ask for the `CustomerFactory::random()` method to find you a "unique" `Customer`, not already selected ? Like the `fake::unique()` method ?

Thank for your help !

**Comment by kbond** [comment]
My first thought is `CustomerFactory::randomSet(5)`. This will return an array of 5 unique random customers:

```php
$customers = CustomerFactory::randomSet(5);

// I'm not entirely sure the following will work
ContactFactory::createMany(5, fn() => ['customer' => $customers[faker()->unique()->numberBetween(0, 4)]);
```

**Comment by Tilotiti** [comment]
> My first thought is `CustomerFactory::randomSet(5)`. This will return an array of 5 unique random customers:
> 
> ```
> $customers = CustomerFactory::randomSet(5);
> 
> // I'm not entirely sure the following will work
> ContactFactory::createMany(5, fn() => ['customer' => $customers[faker()->unique()->numberBetween(0, 4)]);
> ```

Just tried, but unfortunatly no.
They try to assign an array of `Customer`objects to the relation `Contact::$customer`.

**Comment by kbond** [comment]
Yeah, `CustomerFactory::randomSet(5);` return an array of 5 unique random customers. Are you trying to set this in `ContactFactory::getDefaults()`? This won't work for what you're trying to achieve. You'll have to "manually" create them in your test/fixture:

```php
// if you need 5
$customers = CustomerFactory::randomSet(5);

ContactFactory::createOne(['customer' => $customers[0]);
ContactFactory::createOne(['customer' => $customers[1]);
ContactFactory::createOne(['customer' => $customers[2]);
ContactFactory::createOne(['customer' => $customers[3]);
ContactFactory::createOne(['customer' => $customers[4]);
```

Of course, if you need to do this multiple times, the randomset could contain the same customers as previous. randomSet is only unique per call.

**Comment by kbond** [comment]
Here's another (untested) idea:

```php
ContactFactory::createMany(fn() => ['customer' => faker()->unique()->randomElement(CustomFactory::all())]);
```

**Comment by adelinerobinet** [comment]
> My first thought is `CustomerFactory::randomSet(5)`. This will return an array of 5 unique random customers:
> 
> ```
> $customers = CustomerFactory::randomSet(5);
> 
> // I'm not entirely sure the following will work
> ContactFactory::createMany(5, fn() => ['customer' => $customers[faker()->unique()->numberBetween(0, 4)]]);
> ```

**Comment by Tilotiti** [comment]
> Yeah, `CustomerFactory::randomSet(5);` returns an array of 5 unique random customers. Are you trying to set this in `ContactFactory::getDefaults()`? This won't work for what you're trying to achieve. You'll have to "manually" create them in your test/fixture:
> 
> ```
> // if you need 5
> $customers = CustomerFactory::randomSet(5);
> 
> ContactFactory::createOne(['customer' => $customers[0]);
> ContactFactory::createOne(['customer' => $customers[1]);
> ContactFactory::createOne(['customer' => $customers[2]);
> ContactFactory::createOne(['customer' => $customers[3]);
> ContactFactory::createOne(['customer' => $customers[4]);
> ```
> 
> Of course, if you need to do this multiple times, the randomset could contain the same customers as previous. randomSet is only unique per call.

I did run a loop to get this and to be shure that I don't have any duplicate Customer ...
