### ISSUE TITLE
Create many with a prePersist subscriber

### ISSUE THREAD

**Issue by mpiot** [zenstruck/foundry#150]
Hi,
I've a quetion about the `createMany()` function, in some case we can have a prePersist listener/subscriber that define a unique reference for some entities based on the last reference in database.

But, when we do a `createMany()`, it done something like `->persist()` many time, then `->flush()` at the end. Because of that, all the created entities by the `createMany()` function have the same reference.

Is there a way to ask foundry to flush after each persist when using the `createMany()`, or `new()->many()->create()`  function. I've found nothing about that actually ?

I've tried something like:

        MyFactory::new()->afterPersist(function (Proxy $object) {
            $object->save();
        })->many(10000)->create();

But, the callback is the same applied to all.

**Comment by kbond** [comment]
Did you mean to close? Seems related to #37.

**Comment by mpiot** [comment]
@kbond I've closed, because I've note this problem on all parts:
 - in one I just define a number, createMany(10) = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
 - in another, based on the year and the number I generate something like: AA0001, AA0002, AB0001, ... In this case I've collision
 
 Because it works on the first, I need some checks to confirm it, then in the Foundry code I've find you create it one by one, then normally only flush at the end.
 
 In my Callback, it's normal I think because it try to save before flush.
