### ISSUE TITLE
Entity Mapping Question

### ISSUE THREAD

**Issue by rydurham** [zenstruck/foundry#160]
Hello, 

Thank you for creating this project!  In the course of using this package to set up model factories in a slightly older application I have run into an error:

When I try to run something like this:

```php
$organization = OrganizationFactory::new()->create();
$account = AccountFactory::new()->create([
    'organization' => $organization,
]);
```

I get this error: 

```
Doctrine\Persistence\Mapping\MappingException: The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces
```

Is this something you may have encountered before? 

I am new to both Symfony and Doctrine - any insight you might have would be appreciated! Thanks!

**Comment by kbond** [comment]
Hey @rydurham!

Yes, I know why this is happening, the create method wraps your entity in a proxy to give you some helper methods/assetions.

If you change to:
```php
$organization = OrganizationFactory::new()->create();
$account = AccountFactory::new()->create([
    'organization' => $organization->object(), // get the underlying object from Zenstruck\Foundry\Proxy
]);
```

Does that work?

That being said though, I have logic to check for proxies and unwrap them so I'm not sure how you got this error. Are you using the latest version of foundry (v1.10.0)?

**Comment by rydurham** [comment]
Thank you for your help! 

I tried using `$organization->object()` but I still get the same error.  This is with Foundry 1.10.  (This is also a Symfony 4.4 / Doctrine ORM 2.* project if that is helpful.)

Does it matter if I have mappings defined in the `config/packages/doctrine.yml` file?

**Comment by kbond** [comment]
> Does it matter if I have mappings defined in the config/packages/doctrine.yml file?

No, that shouldn't matter.

This is strange... What about this:
```php
$account = AccountFactory::new()->create([
    'organization' => OrganizationFactory::new()
]);
```

1. Where are you creating these factories? In a test or in a data fixture?
2. What do your `OrganizationFactory` and `AccountFactory` classes look like? Just the default from the `make:factory` command?

**Comment by rydurham** [comment]
I really appreciate your help - thank you!

It appears that my original understanding of this error was incorrect.  On closer inspection of the stack trace it appears that the entity mapping and factory relationships are working fine.  The problem occurs later in the test when I attempt to persist the `$account` entity with the entity manager:

```php
// Test set up 
$organization = OrganizationFactory::new()->create();
$account = AccountFactory::new()->create([
    'organization' => $organization,
]);

// Persist the account from within an account service class:
$entityManager->persist($account);

```

This is the stack trace I am seeing:

```shell
There was 1 error:

1) Eoa\Tests\Functional\Service\AccountServiceTest::testPasswordResetValidToken
Doctrine\Persistence\Mapping\MappingException: The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces Eoa\Entity

/var/www/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php:23
/var/www/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php:91
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:154
/var/www/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:306
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:81
/var/www/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:185
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:287
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1763
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1736
/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:609
/var/www/tests/Functional/Service/AccountServiceTest.php:31
```

**Comment by kbond** [comment]
> I really appreciate your help - thank you!

You're very welcome!

Ok, this makes much more sense now. Basically, unless you are doing something very custom, you should not need to use the entity manager directly (with foundry created objects). Foundry abstracts all that and the Proxy object that is giving you the trouble is the key.

First, did you in anyway disable _auto-persisting_? If the answer is no, or you don't know what that is, then:
```php
// this automatically persists the organization (it's in your database after this line)
$organization = OrganizationFactory::new()->create();

// this automatically persists the account
$account = AccountFactory::new()->create([
    'organization' => $organization,
]);

// Remove this - it is not needed
// $entityManager->persist($account);
```

**Comment by rydurham** [comment]
I see.  That makes sense - thank you.   In this case the `$entityManager->persist($account)` call is in the code that is being tested, so I may need to investigate an alternative strategy.

Thank you again for your help!

**Comment by kbond** [comment]
You're welcome.

So you have some kind of service that you are trying to pass an "unpersisted" entity to and verify it gets persisted?

**Comment by rydurham** [comment]
In this case the account is created and persisted, then the service class being tested takes that account, alters it and persists the change on its own.  The goal of the test is to verify the change was saved.  

Being new to Symfony I am not sure if making the change like that in a service class is considered a bad practice or not.

**Comment by kbond** [comment]
The flow with foundry that I like to use for what you're describing is this:
```php
// Arrange
$organization = OrganizationFactory::new()->create();
$account = AccountFactory::new()->create([
    'valueToBeChanged' => 'initial value',
    'organization' => $organization,
]);

// Pre-Assertions (not required but I like using these)
$this->assertSame('initial value', $account->getValueToBeChanged());

// Act
$someService->doSomethingWithAccount($account->object()); // note the ->object() call - this unwraps it from the proxy

// Assert

// assuming you have "auto-refreshing" enabled (this is the default for new installs now)
$this->assertSame('expected new value', $account->getValueToBeChanged());

// if you don't have "auto-refreshing" enabled, do this instead:
$this->assertSame('expected new value', $account->refresh()->getValueToBeChanged());
```

**Comment by rydurham** [comment]
Ah! That is excellent.  I will give that a try.  Thanks!
