### ISSUE TITLE
Doctrine relationships with multi properties on the same entity

### ISSUE THREAD

**Issue by seb-jean** [zenstruck/foundry#166]
Hi,

I have a problem when using Doctrine relationships with multi properties on the same entity.

For my example: I would like messages sent and received to be attributed to the user who has the email "ilovesymfony@gmail.com". But the "sender_id" column is always filled in for this user. Normally there should be 5 rows with the ID "73" for the column "sender_id" and 5 other rows with the ID "73" for the column "receiver_id".

Here my repository : [https://github.com/seb-jean/factory](https://github.com/seb-jean/factory)

AppFixtures : https://github.com/seb-jean/factory/blob/main/src/DataFixtures/AppFixtures.php
UserFactory: https://github.com/seb-jean/factory/blob/main/src/Factory/UserFactory.php
MessageFactory: https://github.com/seb-jean/factory/blob/main/src/Factory/MessageFactory.php

Table user:
![user](https://user-images.githubusercontent.com/12116264/120458481-9ad41380-c397-11eb-8a9e-7710f25ed581.png)

Table message:
![message](https://user-images.githubusercontent.com/12116264/120458526-a32c4e80-c397-11eb-8382-817fb84a75eb.png)

Thank you for your help :)

**Comment by kbond** [comment]
Hey @seb-jean. So you want the `ilovesymfony@gmail.com` user to have 5 messages that they are the sender and 5 where they are the receiver? What about this?

```php
public function load(ObjectManager $manager)
{
    UserFactory::createMany(10);

    $ilovesymfony = UserFactory::createOne([
        'email' => 'ilovesymfony@gmail.com',
    ]);

    MessageFactory::createMany(5, ['sender' => $ilovesymfony]);
    MessageFactory::createMany(5, ['receiver' => $ilovesymfony]);

    $manager->flush();
}
```

**Comment by kbond** [comment]
Note, with my above code, it's possible for the `ilovesymfony@gmail.com` user to be both the sender and receiver because you are choosing a random user for the other field (which includes `ilovesymfony@gmail.com`). You can avoid this with this code:

```php
public function load(ObjectManager $manager)
{
    $users = UserFactory::createMany(10);

    $ilovesymfony = UserFactory::createOne([
        'email' => 'ilovesymfony@gmail.com',
    ]);

    // only choose a random receiver from the $users array which does not include ilovesymfony@gmail.com
    MessageFactory::createMany(5, fn() => ['sender' => $ilovesymfony, 'receiver' => faker()->randomElement($users)]);

    // only choose a random sender from the $users array which does not include ilovesymfony@gmail.com
    MessageFactory::createMany(5, fn() => ['receiver' => $ilovesymfony, 'sender' => faker()->randomElement($users)]);

    $manager->flush();
}
```

**Comment by seb-jean** [comment]
> So you want the `ilovesymfony@gmail.com` user to have 5 messages that they are the sender and 5 where they are the receiver?

Yes that's it :)

> ```
> public function load(ObjectManager $manager)
> {
>     $users = UserFactory::createMany(10);
> 
>     $ilovesymfony = UserFactory::createOne([
>         'email' => 'ilovesymfony@gmail.com',
>     ]);
> 
>     // only choose a random receiver from the $users array which does not include ilovesymfony@gmail.com
>     MessageFactory::createMany(5, fn() => ['sender' => $ilovesymfony, 'receiver' => faker()->randomElement($users)]);
> 
>     // only choose a random sender from the $users array which does not include ilovesymfony@gmail.com
>     MessageFactory::createMany(5, fn() => ['receiver' => $ilovesymfony, 'sender' => faker()->randomElement($users)]);
> 
>     $manager->flush();
> }
> ```

It works very well but why use a callback? :)

**Comment by kbond** [comment]
> It works very well but why use a callback? :)

If you don't use a callback, the faker random element call will evaluate just once. You'd have the same random user for all 5 sender's or receiver's.

**Comment by seb-jean** [comment]
OK I understand :).
Thank you very much @kbond for your time :pray:
