### ISSUE TITLE
Need some help to refactor standard fixture code into factory model

### ISSUE THREAD

**Issue by sabri-said** [zenstruck/foundry#178]
Hello, I wanted to create a factory and populate table with it.
Actually I have this code which woks well and give me the result I want. It add each `moodName` in database and increment the `$moodRating` up to 5.
```php
        $faker = Factory::create();
        $moodNames = ['Very Bad Mood', 'Bad Mood', 'Neutral Mood', 'Good Mood', 'Very Good Mood'];
        $moodRating = 1;
        foreach ($moodNames as $moodName) {
            $moodEntity = new Mood();
            $moodEntity->setName($moodName);
            $moodEntity->setRating($moodRating++);
            $moodEntity->setCreatedAt($faker->dateTimeBetween('now'));
            $manager->persist($moodEntity);
        }
```
I try to refactor this code into the corresponding factory model but I can't seem to loop through the array and insert each `$moodName` and `$moodRating`. I try this but no success because it create five entries only with the same first array value and initial `moodRating` value.
```php
MoodFactory::new(
            function () {
                $faker = Factory::create();
                $moodNames = ['Very Bad Mood', 'Bad Mood', 'Neutral Mood', 'Good Mood', 'Very Good Mood'];
                $moodRating = 1;
                foreach ($moodNames as $moodName) {
                    array_shift($moodNames);
                    return [
                        'name' => $moodName,
                        'rating' => $moodRating++,
                        'createdAt' => $faker->dateTimeBetween('now')
                    ];
                }
            }
        )->many(5)->create();
```

Some help would be appreciated. Thank you

PS: I am French so sorry for any grammatical mistakes

**Comment by wouterj** [comment]
Hi!

The callable is run for each fixture that is created, which means `$moodNames` and `$moodRating` are re-set each time.

I would suggest you would replicate your original set-up much more when using Foundry (there is no need to make working code more complex :smiley: ):

```php
        $moodNames = ['Very Bad Mood', 'Bad Mood', 'Neutral Mood', 'Good Mood', 'Very Good Mood'];
        $moodRating = 1;
        foreach ($moodNames as $moodName) {
            MoodFactory::createSingle([
                'name' => $moodName,
                'rating' => $moodRating++
            ]);
        }
```

You don't need to use faker, this is something you configure in your `MoodFactory::getDefaults()`:

```php
protected function getDefaults(): array
{
    return [
        'createdAt' => self::faker()->dateTimeBetween('now'),

        // it's a good practice to make sure your factory has default values for each required property
        'name' => self::faker()->randomElement(['Very Bad Mood', 'Bad Mood', 'Neutral Mood', 'Good Mood', 'Very Good Mood']),
        'rating' => self::faker()->numberBetween(1, 10),
    ];
}
```

**Comment by sabri-said** [comment]
Hi, thank you four your answer 

Indeed your code is much simple, but just to be sure is it possible to move all the first snippet code in my `MoodFactory` and reproduce the same result ? 
Because what I was originally trying to do was to only use `MoodFactory` methods like `MoodFactory::createMany(5)` and have the same result as the first code you posted without have many loops, etc... in order to have a "clean" fixture file

**Comment by wouterj** [comment]
You can indeed add this to a static method in the factory class:

```php
class MoodFactory extends Factory
{
    // ...

    public static function createDefaultMoods(): void
    {
        $moodNames = ['Very Bad Mood', 'Bad Mood', 'Neutral Mood', 'Good Mood', 'Very Good Mood'];
        $moodRating = 1;
        foreach ($moodNames as $moodName) {
            self::createOne([
                'name' => $moodName,
                'rating' => $moodRating++
            ]);
        }
    }
}
```

Now you can do `MoodFactory::createDefaultMoods()` in your code to load the fixture.

**Comment by sabri-said** [comment]
I feel stupid 😄 I was so focused on creating the values through the `getDefaults` method that I forgot to think about creating a custom method. In any case, thank you very much for your help, appreciate 😀
