### ISSUE TITLE
Entity cascading unexpected behavior

### ISSUE THREAD

**Issue by mpiot** [zenstruck/foundry#179]
In the case we have 3 entities linked together likes:

```php
class A
{
  /**
   * @ORM\OneToMany(targetEntity=B::class, mappedBy="a", cascade={"persist"})
   */
  private Collection $bs;

  private ?string $reference = null;

  public function __construct() {
    ​$this->bs = new ArrayCollection();
  ​}
}

class B
{
  /**
    * @ORM\ManyToOne(targetEntity=A::class, inversedBy="bs")
    * @ORM\JoinColumn(nullable=false)
    */
  ​private ?A $a = null;

  /**
   * @ORM\ManyToOne(targetEntity=C::class, inversedBy="bs", cascade={"persist"})
   * @ORM\JoinColumn(nullable=false)
   */
  ​private ?C $c = null;

  ​private ?string $reference = null;
}

class C
{
  /**
   * @ORM\OneToMany(targetEntity=B::class, mappedBy="c")
   */
  private Collection $bs;

  ​private ?string $reference = null;

  public function __construct() {
    ​$this->bs = new ArrayCollection();
  ​}
}
```

There is listener on A and C to generate tha A, B and C references. The A listener loop over the collection of B. It works well in the application, but when I want to create a fixture for A... It totally explode, when Foundry call the persist, there is no B inside the collection (in A class). But to generate the A reference I need the first B class of the collection and the linked C class.

Someone know how we can do this ? Actually I've something similar to:

AFactory::createOne();

Internally:
 - AFactory call BFactory::new()->many(3);
 - BFactory call CFactory::new();

**Comment by kbond** [comment]
Does it work if you create the factories manually on their own? Create C, create A, then create B with these?

I find using foundry for one-to-many a bit finicky for complex scenarios. I tend to favor creating many-to-one's only.

**Comment by mpiot** [comment]
It didn't for A and B, it's ok for C. In this case, C can live alone. But a B can't exists without a A, and a A can't exists without at least a B.

All work without the prePersist listener that generate the reference. Because to generate the A reference the listener get the first B, then the attached C. And to define the B reference, get the C then the A. A and B must be persisted together with a pre-existing C or by saving the C to.

Apparently, if I have correctly understand, foundry save the A entity in database (persist and flush) but have not yet added the B to the entity (there is no link, the adder is never called before), then when the listener call the getBs() method, it return an empty collection. This is the real problem, because in this case we just need A have B and B have C objects, to do the reference. After, we can save the first without B and C for exemple.

**Comment by kbond** [comment]
In your app where it works correctly, are you creating/persisting all the entities at once and then calling `flush()` just once?

I think this is related to #37. Are you able to test with #84. This allows you to create all your factories inside a callback. When they are created they are not immediately flushed. A _single_ flush occurs after the callback has run. #84's description has an example on how to use.

**Comment by mpiot** [comment]
@kbond In the app, I just fush and persist one time, the A class, then it cascade persist B that cascade persist C.
I look at your PR and test it.

**Comment by kbond** [comment]
Ah, yes, the cascade persist - I'm not very familiar with that doctrine feature but _I think_ that PR could still help.

**Comment by mpiot** [comment]
Yes, I try it. For the moment it return to me an error about auto refreshing:

> RuntimeException: Cannot auto refresh "App\Entity\Specificity" as there are unsaved changes. Be sure to call ->save() or disable auto refreshing (see https://github.com/zenstruck/foundry#auto-refresh for details).

Related to the Factory::new() inside, I'll try by disable refreshing globally to check, then if it works, by disabled it only for that part.

**Comment by mpiot** [comment]
By disabling auto-refreshing it works well for that auto-refresh error. But, return the same error that before, the Collection in A class is always empty.

**Comment by kbond** [comment]
> For the moment it return to me an error about auto refreshing:

I've fixed this in the PR - disabling auto-refresh within the callback is no longer required.

> In the Factory, when we define attributes, and an attributes call a Factory, this one is called, procces its attributes, execute persist() then flush() on it, then comeback to the initial factory and continue to resolves its attributes, that's it ?

Yes (but within the callback in #84 `flush()` isn't called for each factory, just `persist()`).

> When it find a ->many(), it create a FactoryCollection, that can't match with a Doctrine Collection, then the adder is never call I think ? In my case, more than a problem of sore it in database before the other, it's a problem of we can't reach the Collection from the entity in the listener because never added. I've not well understand how it works. :/ (sorry)

Did you make any changes to the [default instantiation](https://github.com/zenstruck/foundry#instantiation) of factories? If not, then the adder should be called (by `symfony/property-accessor`).

What happens when a `FactoryCollection` is encountered is: call `FactoryCollection::create()` which returns an array of objects. Using the default instantiator, this array is set on the object using the adders.

I know this is a bit of an ask but, can you create a minimal reproducer? Even better would be a failing test but I can use a reproducer to build a failing test myself.

**Comment by mpiot** [comment]
I investigate more, because in fact I have a collection that is filled with adder called and the other not. I check in my own code if something can do that.

Else, the only difference is that one is a Collection of a class with only scalar attributes, than the other is a Collection of a class with relation to other entities, and have Collection to.

**Comment by kbond** [comment]
> I have a collection that is filled with adder called and the other not

How is the other's collection being set `->setCollection($collection)`? That might be a problem although I'd expect the error to be different... Like a `TypeError`: "cannot set array as `Collection`" exception.

**Comment by mpiot** [comment]
No, both use adder. When I dump the attributes, I have an empty array for this Collection. I do not understand why, in my factory:

ProbeFactory.php
```php
    protected function getDefaults(): array
    {
        return [
            //...
            'usages' => UsageFactory::new()->many(1),
            //...
            'probeAcoustics' => ProbeAcousticFactory::new()->withoutProbe()->many(1),
        ];
    }
```
The first one is ok, but the never not.

ProbeAcousticFactory.php
```php
    protected function getDefaults(): array
    {
        return [
            'acoustic' => AcousticFactory::new(),
            'probe' => ProbeFactory::new(),
        ];
    }

    public function withoutProbe(): self
    {
        return $this->addState([
            'probe' => null,
        ]);
    }
```

**Comment by kbond** [comment]
```php
$a= ProbeFactory::new()
    ->instantiateWith(function(array $attibutes, string $class): object {
        dd($attibutes['probeAcoustics']); // THIS is [] (an empty array)?
    })
    ->create()
;
```

**Comment by kbond** [comment]
Maybe a bug in [`Factory::normalizeCollection()`](https://github.com/zenstruck/foundry/blob/b145059c812f614bef23043870641aa0797579d9/src/Factory.php#L317)? See how it's returning an empty array if inverse. I think I'm not taking `cascade: persist` into account here.

**Comment by mpiot** [comment]
I check it tomorrow, and say you what I find.
Thanks a lot for your help 🙏

**Comment by mpiot** [comment]
> $a= ProbeFactory::new()
    ->instantiateWith(function(array $attibutes, string $class): object {
        dd($attibutes['probeAcoustics']); // THIS is [] (an empty array)?
    })
    ->create()
;

Yep it return an empty array.

I've commented lines in `Factory::normalizeCollection()`, by doing it only: it throw an error about not defined Probe (null) in ProbeAcoustic. Butby  adding it with `Factory::delayFlush` seem works well for this part. Logical, it create the ProbeAcoustic, then use the adder to add it to Probe, at this point nothing flush, the adder create the link between us (addProbeAcoustic, call $probeAcoustic->setProbe()).

But, inevitably break all other parts because it create all dependencies and flush them incompletly (no added to the one that "invoke" them).

This is tricky because all work well, all sub Entities are created on demand, persisted and flushed, then after linked to the parent. In case of revert relation, the link is done in prePersist actually. This problem only come from eventListener used in the application, when this one need to access a revertCollection. (In the exemple bellow between Usage collection and ProbeAcoustic collection is here: Usage is a ManyToMany relation owned by Probe, but ProbeAcoustic is a OneToMany relation on Probe); that's why it's escaped in the Factory. But by escaping it, all inversed relation are empty on persist (not totally sure of having all understand).

**Comment by mpiot** [comment]
I thought about it for a while, I think there is 2 possibilities of creating the entity:
  1. The entity need to be linked to another existing entity (eg: select a Category), that works very well, because we create, persist and flush it on this own, then refer to it in our entity and that's exactly the expected behavior.
  2. The entity has a relation with a `cascade={"persist"}` on it, in this case:
    - The relation entity must be created, but not persisted, and not flushed
    - Use the our original entity setter/adder to attach this entity on, and continue (this adder, permit to reference this entity on the main one by adding it in the collection, or just set it. Often it call the "child" setter to refer the parent. On flush, because cascade persist, doctrine do the necessary).

I take a look about it, and see if I find an idea of how to do that. Normally it should solve the issue, and be more realistic with how the fixture is created, compared to how this same entity(ies) are created from the application logic.

**Comment by kbond** [comment]
> I've commented lines in Factory::normalizeCollection(), by doing it only: it throw an error about not defined Probe (null) in ProbeAcoustic.

Yeah, I thought this might cause an issue with your other entities. I can try to create a failing test with cascade persist when I have a chance.

**Comment by mpiot** [comment]
Just a start of try:

Factory.php
```php
    private function normalizeCollection(FactoryCollection $collection): array
    {
        $field = $this->inverseRelationshipField($collection->factory());
        $cascadePersisted = $this->hasCascadePersist($collection->factory(), $field);

        if ($this->isPersisting() && $field && false === $cascadePersisted) {
            $this->afterPersist[] = static function(Proxy $proxy) use ($collection, $field) {
                $collection->create([$field => $proxy]);
                $proxy->refresh();
            };

            // creation delegated to afterPersist event - return empty array here
            return [];
        }

        return $collection->all();
    }

 // ...

    private function hasCascadePersist(self $factory, ?string $field): bool
    {
        if (null === $field) {
            return false;
        }

        $collectionClass = $factory->class;
        $factoryClass = $this->class;
        $collectionMetadata = self::configuration()->objectManagerFor($collectionClass)->getClassMetadata($collectionClass);
        $classMetadataFactory = self::configuration()->objectManagerFor($factoryClass)->getMetadataFactory()->getMetadataFor($factoryClass);

        // Find inversedBy key
        $inversedBy = $collectionMetadata->associationMappings[$field]['inversedBy'] ?? null;

        // Find cascade metatada for the inversedBy field
        $cascadeMetadata = $classMetadataFactory->associationMappings[$inversedBy]['cascade'] ?? [];

        return in_array('persist', $cascadeMetadata, true);
    }
```

I see to disabled the flush in that case too without `Factory::delayFlush()`, then see to enable it on all type of relations:
 - ManyToOne
 - OneToMany
 - ManyToMany (both side)
 - OneToOne (both side)

**Comment by kbond** [comment]
That's inline with what I was thinking except, instead of having to manually set, detect from the mapping.

Did the above work for your use case?

**Comment by mpiot** [comment]
Yep, this solve my problem, and do not break others.

I work on a way to enable it on owner side to, then do a PR for it.
