### ISSUE TITLE
 error when using random|randomOrCreate|findOrCreate on ManyToMany related column

### ISSUE THREAD

**Issue by webmasterMeyers** [zenstruck/foundry#184]
I am trying to use the factory function randomOrCreate() to no avail.

The entity is `User` and has a ManyToMany relationship with `Group`

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="`user`")
 * @UniqueEntity("username")
 * @UniqueUserEmail()
 */
class User implements UserInterface
{
    /**
     * @ORM\ManyToMany(targetEntity=UserGroup::class, inversedBy="users")
     */
    private $groups;

    /**
     * @return Collection|UserGroup[]
     */
    public function getGroups(): Collection
    {
        return $this->groups;
    }

    public function setGroups(Collection $groups): self
    {
        $this->groups = $groups;

        return $this;
    }
}
```

A line like:
```php
UserFactory::randomOrCreate(['groups' => $this->entityManager->find(UserGroup::class, 5)])
```
will fail with the error:  
> Notice: Trying to access array offset on value of type null

doing:
```php
UserFactory::createMany(3, ['groups' => $this->entityManager->find(UserGroup::class, 5)])
```
works. I get 3 `User`s all with the same group.  I can also use `randomOrCreate` and pass in a simple attribute like a name and it works.

Am I doing something wrong?  Is this not how the Random functions are supposed to work?

**Comment by kbond** [comment]
RandomOrCreate is only meant to be used with attributes that can used as criteria in `ObjectRepository::findOneBy()`. In your example above, since `groups` is a collection, it can't be used this way.

How `randomOrCreate(['name' => 'john'])` works is (pseudo code):

```php
$entity = $repo->findOneBy(['name' => 'john']);

if ($entity) {
    return $entity; // entity already found in db, no need to create
}

return $this->create(['name' => 'john']); // not in db so create with passed attributes
```
