### ISSUE TITLE
PHP 8.0+ support

### ISSUE THREAD

**Issue by taboritis** [zenstruck/foundry#196]
Problem 1
    - fakerphp/faker[v1.9.1, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.0.10) does not satisfy that requirement.
    - zenstruck/foundry[v1.13.0, ..., v1.13.2] require fakerphp/faker ^1.5 -> satisfiable by fakerphp/faker[v1.9.1, ..., v1.16.0].
    - fakerphp/faker v1.16.0 conflicts with fakerphp/faker v1.16.0.
    - fakerphp/faker v1.15.0 conflicts with fakerphp/faker v1.15.0.
    - fakerphp/faker v1.14.1 conflicts with fakerphp/faker v1.14.1.
    - fakerphp/faker v1.14.0 conflicts with fakerphp/faker v1.14.0.
    - fakerphp/faker v1.13.0 conflicts with fakerphp/faker v1.13.0.
    - fakerphp/faker v1.12.1 conflicts with fakerphp/faker v1.12.1.
    - fakerphp/faker v1.12.0 conflicts with fakerphp/faker v1.12.0.
    - fakerphp/faker v1.11.0 conflicts with fakerphp/faker v1.11.0.
    - fakerphp/faker v1.10.1 conflicts with fakerphp/faker v1.10.1.
    - fakerphp/faker v1.10.0 conflicts with fakerphp/faker v1.10.0.
    - Root composer.json requires fzaninotto/faker ^1.5 -> satisfiable by fzaninotto/faker[v1.5.0], fakerphp/faker[v1.9.1, v1.9.2].
    - Root composer.json requires zenstruck/foundry ^1.13 -> satisfiable by zenstruck/foundry[v1.13.0, v1.13.1, v1.13.2].

**Comment by jdreesen** [comment]
The problem is that you require `fzaninotto/faker` in your `composer.json` which `zenstruck/foundry` is not compatible with, as it requires its successor `fakerphp/faker. So you first have to switch to that library.

**Comment by taboritis** [comment]
Thank you. It works
