### ISSUE TITLE
Getting TypeError when using custom repository.

### ISSUE THREAD

**Issue by juanma1331** [zenstruck/foundry#200]
Hi, Im getting this error when trying to create a factory.
` Return value must be of type Doctrine\Persistence\ObjectRepository,  App\Repository\DoctrineProductRepository returned`.
My repository only implements my domain repository interface. Do I have to change something on config to be able to use my custom repository to generate the factory? Thanks.

**Comment by kbond** [comment]
I don't think it would be possible to use your custom repository if it doesn't implement `Doctrine\Persistence\ObjectRepository` but it should just use the standard `Doctrine\ORM\EntityRepository` when it needs a repository... What exactly is throwing the exception?

**Comment by juanma1331** [comment]
Sure.
![foundryerror](https://user-images.githubusercontent.com/46537115/134236783-09c7d5ff-2cc0-48d7-9376-44806c969f18.png)
Thanks for your help.

**Comment by juanma1331** [comment]
Yeah I use it as a service, I have the specific repository class configured on service.yaml. The specific DoctrineProductRepository use the entity manager to perform the operations. Tell me if you need more code. Thanks

**Comment by kbond** [comment]
Ok, does your entity have `repositoryClass` set in it's `Entity` annotation (assuming you're using annotations)? If so, remove it, then you should be good to go.

**Comment by juanma1331** [comment]
Yes mate. I have it annotated with that. I i will remove it and try. Thanks.

**Comment by kbond** [comment]
Basically, you are telling doctrine to use a custom repository but a custom repository's needs to implement `Doctrine\Persistence\ObjectRepository` to work correctly. Since you are completely taking over and not implementing that interface, you need to configure doctrine use the "default" entity repository (`Doctrine\ORM\EntityRepository`). Removing `repositoryClass` does this.

**Comment by juanma1331** [comment]
Thanks, now I understand it better.

**Comment by juanma1331** [comment]
I tried removing that and it worked. Thanks

**Comment by kbond** [comment]
Excellent, glad to hear!
