### ISSUE TITLE
Cannot use faker with createMany

### ISSUE THREAD

**Issue by lamkimphu258** [zenstruck/foundry#202]
Hi, when I use createMany with faker in my UserFixtures, it does not work. It always have an error about `Duplicate entry` since in my database email must be unique. The error look like this 
```
 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'elockman@hotmail.com' for key 'user.UNIQ_8D93D649E7927C74'  
```
This is my code
```
UserFactory::createMany(10, ['email' => $faker->unique->email, 'username' => $faker->unique->userName]);
```
However, when I use this code instead, it works well. 
```
for ($i=0; $i < 10; $i++) {
     UserFactory::findOrCreate(['email' => $faker->unique->email, 'username' => $faker->unique->userName]);
}
```
So why faker does not load unique data in method `createMany`? Did I do something wrong? Can you guys explain to me why it does not work, please? Thank you.

**Comment by wouterj** [comment]
In your code, `$faker->unique->email` is called once and its return value is then set as `email`. So this will always be the same for the 10 entities.

Use a callback, as shown around line 15 in this example: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#many-to-one

**Comment by kbond** [comment]
This should work:

```php
UserFactory::createMany(10, fn() => ['email' => $faker->unique->email, 'username' => $faker->unique->userName]);
```

**Comment by lamkimphu258** [comment]
Thanks, it works well.
