### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jsamouh** [zenstruck/foundry#21]
Hello,

When I setup the package, I have the following error:
You have requested to a non-existent service "Zenstruck\Foundry\Configuration" 

Do you knw what can cause this issue ?

@kbond  @jdreesen 

Thks

**Comment by kbond** [comment]
@jsamouh did you solve this?

**Comment by jsamouh** [comment]
yes sorry for that

**Comment by jsamouh** [comment]
I did not go deeper in the code but why it is mandatory to use KernelTestCase for Unit testing ? Why do you need to boot the kernel in order to make it work ?

**Comment by kbond** [comment]
In your unit test, do you require the entities created with foundry to be persisted to the database?

**Comment by jsamouh** [comment]
not at all :-)

**Comment by jsamouh** [comment]
just need to create entity from your factory for unit testing other classes without saving anything in the database

**Comment by kbond** [comment]
Ok, perfect. Then you don't need to have your test case extend `KernelTestCase` or use the supplied traits. While this library is more tailored to creating and persisting entities, you can create without persisting.

If you created a model factory for an entity using `make:factory`, before calling `->create()`, call `->withoutPersisting()`:

```php
MyModelFactory::new()->withoutPersisting()->create();
MyModelFactory::new()->withoutPersisting()->createMany();
```

If desired, you can override your ModelFactory's [`initialize`](https://github.com/zenstruck/foundry#initialization) to never persist:

```php
protected function initialize(): self
{
    return $this->withoutPersisting();
}
```

You could even create your own abstract ModelFactory class to add this behaviour to all your factories.

If you're using [anonymous factories](https://github.com/zenstruck/foundry#anonymous-factories) you can use `instantiate` or `instantiate_many` helper functions.

**Comment by jsamouh** [comment]
excellent
thanks for your explanation :-)

**Comment by kbond** [comment]
No problem. Admittedly, the documentation is lacking on this - I'll open an issue to improve.

Also, while I use this feature a little in my projects, I think there still may be some edge cases. If you come across any issues or edge cases, let me know!

**Comment by janopae** [comment]
> yes sorry for that

But how did you solve this?

**Comment by janopae** [comment]
I just solved it by clearing the cache (`rm -rf var/cache/development/*`).
