### ISSUE TITLE
Factory create extra unintended records when cascade persist is enabled

### ISSUE THREAD

**Issue by anjeylink** [zenstruck/foundry#210]
Following documentation on how to work with doctrine relations I got unintended records for reverse side of relation with configured cascade persist. https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#doctrine-relationships

For example I have **Post** with **One-To-Many relation with Comment**.
Post field `comments` is configured **cascade persist**.

PostFactory:

```php

    protected function getDefaults(): array
    {
        return [
            'name' => self::faker()->word(),
        ];
    }
```

CommentFactory:

```php

    protected function getDefaults(): array
    {
        return [
            'text' => self::faker()->word(),
            'post' => PostFactory::new(),
        ];
    }
```

Test:

```php

    public function testThatCreatePostWithCommentsWillCreateOnlyOnePostRecord()
    {
        PostFactory::createOne([
            'comments' => CommentFactory::new()->many(5),
        ]);

        PostFactory::assert()->count(1);
    }
```

Expect that there will be only one Post entity but there are 6.
Tests failed starting from 1.13 version. It's working in 1.12.

**Comment by kbond** [comment]
Closing for now.
