### ISSUE TITLE
Question: Does the project only support one locale for Faker?

### ISSUE THREAD

**Issue by genby8** [zenstruck/foundry#214]
My project contains content in different languages. Do I understand correctly that I cannot use faker with different settings?

**Comment by kbond** [comment]
https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#faker does this help or do you mean something else?

**Comment by genby8** [comment]
I am generating articles and getting a random article language.
`
final class ArticleFactory extends ModelFactory{
    protected function getDefaults(): array {
        $language = LanguageFactory::random();
        return [
            'content' => self::faker()->text(),
            'nameAuthor' => self::faker()->name(),
            'lang' => $language
        ];
    }
}`
I want to generate content in the language of the article. Faker is configured once it turns out? And I can't do what I want out of the box?

**Comment by kbond** [comment]
Ah, I see what you mean. Yes, Faker can only be configured with one locale. You'd have to do something like:

```php
final class ArticleFactory extends ModelFactory {
    protected function getDefaults(): array {
        $language = LanguageFactory::random(); //there are many languages and random choice
        $faker = Faker\Factory::create($language);
        return [
            'content' =>  faker->text(),
            'nameAuthor' => faker->name(),
            'lang' => $language
        ];
    }
}
```

**Comment by genby8** [comment]
@kbond Thanks.
I know this method, but creating generator instances thousands of times is resource-intensive. I thought that once a wrapper was provided in the package, then through it and do it.
Otherwise, you have to write your own wrapper to avoid thousands of generators in memory. But the irony is that I will be writing test code that itself may contain bugs!

**Comment by kbond** [comment]
Yeah, that's fair. Writing your own little "faker factory" that caches the created faker instances by locale looks like your best bet.

Could be something worth bringing up in faker itself.
