### ISSUE TITLE
Problem with dependent entity properties

### ISSUE THREAD

**Issue by gnito-org** [zenstruck/foundry#227]
I've run into an issue in ``ModelFactory::createOne()`` when one property depends on the value of another property in the entity.

It appears that the values of the properties are being set in property name alphabetical order.

If property ``aField`` depends on property ``kField`` to compute its value in its setter, then property ``kField`` is still empty at the point where the foundry calls the setter of ``aField``.

This particular issue will be solved if properties are set in the order that they appear in the array of values that's given to the ``ModelFactory::createOne()`` method.

I wouldn't worry about properties that are set in the defaults of the model factory. Where property set sequence is important, one can simply include all the relevant property values in the ``ModelFactory::createOne()`` method. In other words, set only the properties that are specified in the ``ModelFactory::createOne()`` method in their given sequence, and not in alphabetical sequence. The sequence of the rest of the properties don't matter.

**Comment by gnito-org** [comment]
I tried setting the property ``kField`` in ``ModelFactory::new()->->beforeInstantiate()`` and ``ModelFactory::new()->afterInstantiate()``. It did not make any difference.

**Comment by kbond** [comment]
My first thought is this seems like a _domain_ issue. This is a problem in _user-land_ as well (creating these entities by hand). If `aField` depends on `kField`, `kField` should be set in the entity constructor.

That being said, after a quick review, I'm not aware of any place we're sorting these attributes in anyway. The attributes passed to `createOne()` are just merged with `getDefaults()`. Let me know if you see this somewhere.

To clarify:

```php
MyFactory::createOne([
    'kField' => 'some value',
    'aField' => 'another value',
]); // setKField is being called after setAField() ?
```

**Comment by gnito-org** [comment]
I misdiagnosed the problem.

It happens when you set the value of ``aField`` in ``ModelFactory::getDefaults()``, and the value ``kField`` is only available in ``ModelFactory::createOne()``. 

It also happens if, in ``ModelFactory::createOne()``, ``aField`` is above ``kField`` in the array.

The solution is simple:

- Don't put computed fields in ``ModelFactory::getDefaults()``,
- In ``ModelFactory::createOne()``, list the dependent field(s) later/last in the array.

**Comment by gnito-org** [comment]
I'm closing this issue because it's a feature, not a bug.
