### ISSUE TITLE
Column name with reserved words fails - should have backticks

### ISSUE THREAD

**Issue by lsv** [zenstruck/foundry#239]
If I have a entity as this

```php
#[ORM\Entity(repositoryClass: LevelRepository::class)]
class Level
{
    #[ORM\Id]
    #[ORM\Column(type: 'string', length: 255)]
    public string $id = '';

    #[ORM\Column(type: 'float', nullable: true)]
    public ?float $index = null;
}
```

and my factory as

```php
final class LevelFactory extends ModelFactory
{
    protected function getDefaults(): array
    {
        return [
            'id' => 123,
        ];
    }

    protected function initialize(): self
    {
        return $this;
    }

    protected static function getClass(): string
    {
        return Level::class;
    }
}

```

It will fail, because `index` is a reserved name in mysql, and as foundry doesnt wrap column names with backticks then it fails because it tries to execute `INSERT INTO level (id, index) VALUE (123, NULL)` if the column names was wrapped with backticks it would be <code>INSERT INTO level (\`id\`, \`index\`) VALUE (123, NULL)</code> and it would work as expected

**Comment by kbond** [comment]
Hello, you need to make this change with doctrine: https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words

**Comment by lsv** [comment]
It seems that it actually works fine with doctrine ORM, without setting backticks in column name.

```php
$l = (new Level)->index = 10;
$doctrine->persist($l);
$doctrine->flush();
```

**Comment by kbond** [comment]
I'm confused because that's exactly how foundry instantiates entity's:

```php
LevelFactory::createOne(['index' => 10]);

// internally, foundry does:
$level = new Level();
$level->index = 10;
// persist/flush
```

**Comment by lsv** [comment]
I made a boo boo, wupsi :) - i tested it with indes (yes - an s instead of x) with doctrine entity.
