### ISSUE TITLE
Generated entities do not implement interfaces?

### ISSUE THREAD

**Issue by abeal-hottomali** [zenstruck/foundry#242]
Hi,

I'm very excited about this package, but I'm not sure if we can use it.  I'm generating entities in kernel tests, and I'm running into issues where the generated proxy entity does not implement the same interfaces that the original one does.  Because I'm using the generated entities with classes that expect one of those interfaces in their methods, the generated foundry classes are unusable.

I'm not sure if this is by design or not, or if there's a simple workaround.  Mostly opening to make sure this is a known thing, and I haven't just made a mistake in my usage.

Can provide more info if needed?

**Comment by wouterj** [comment]
Hi!

You can use `->object()` on the proxy class to get the real entity. In all cases I've had this situation, the proxy was also not meant to be injected in the real classes that required them.

There is some (long standing) work on refactoring the proxy object to be real proxies: https://github.com/zenstruck/foundry/pull/127 I hope to round that one up some time, but for now `object()` is the way to go.

**Comment by abeal-hottomali** [comment]
Perfect, thank you.
