### ISSUE TITLE
Lazy run related entities defined in `getDefaults()` 

### ISSUE THREAD

**Issue by wouterj** [zenstruck/foundry#244]
Imagine `Post` has a n..1 relation with `Category`. In `PostFactory`, you would have a `getDefaults()` method like:

```php
public function getDefaults(): array
{
    return [
        'category' => CategoryFactory::randomOrCreate(),
    ];
}
```

However, this will cause the `PostFactory` to always create a category entity (even if I always explicitly pass a category when creating posts).

Is it maybe an idea to allow some sort of "lazy" value instantiating? two ideas:

**A) Make values as functions special**

Currently, if I do `'category' => fn() => CategoryFactory::randomOrCreate()`, it'll pass the function as argument value. It is a BC break to call the function instead, but on the other hand it makes sense to me to not support functions as a valid attribute value for entities.

**B) Add a special helper**

We can create a callable class and in the factory, we would use an `instanceof` check to determine if we should call the method. We can add a helper function and do something like: `'category' => lazy(fn() => CategoryFactory::randomOrCreate())`.

**Comment by kbond** [comment]
Interesting, could `randomOrNew()` be an option?
