### ISSUE TITLE
Multiple instantiateWith call should not override instantiator

### ISSUE THREAD

**Issue by flohw** [zenstruck/foundry#256]
Hello,

Maybe the title is not that clear and is not accurate, if you have a better idea after reading my issue, suggestions are welcome :slightly_smiling_face: 

As my entities have required parameters to match my model as close as possible, I use `instanciateWith` method a lot which constructs my entity with the defaults parameters using the `$attributes` parameter provided to the callable.

But sometime I have to set the id of my entity for some of my tests (**due to legacy code I am not able to remove its usage**). So I created a `withId` method in an `AbstractModel` (from which all of my factories extends) this method also calls `instantiateWith` method. As the Factory works, this cause problem as my constructor parameters are not provided anymore.

As the `instantiator` property is private and `instantiateWith` is final I see no solution to set my `id` property which is private and has no setter and should not have any.

For more clarity, here is the code I use:
```php
namespace Factory\Tests;

abstract class ModelFactory extends \Zenstruck\Foundry\ModelFactory
{
    public function withId(int $id): self
    {
        return $this->instantiateWith((new Instantiator())->alwaysForceProperties(['id']))->addState(['id' => $id]);
    }
}
```

```php
namespace Factory\Tests\Referential;
// All the use statements

final class UnitFactory extends \Factory\Tests\ModelFactory
{
    protected function getDefaults(): array
    {
        return [
            'name' => self::faker()->text(),
            'symbol' => self::faker()->text(5),
            'availableForRecipes' => self::faker()->boolean(),
        ];
    }

    public function initialize(): self
    {
        return $this->instantiateWith(fn (array $attributes) => new Unit($attributes['name'], $attributes['symbol'], [], $attributes['availableForRecipes']));
    }

    protected static function getClass(): string
    {
        return Unit::class;
    }
}
```

Then in my test when instantiating a `Unit` which needs an id with `UnitFactory::new()->withId(1)->create()->object()` I get the following exception: `InvalidArgumentException: Missing constructor argument "markets" for "App\Domain\Entity\Referential\Unit".`
The `markets` argument is the empty array of the `new Unit` statement in the `UnitFactory`.

Have you a solution or woarkaround for this? I found some but none of them satisfies my requirements or works for now.

Would it be possible to allow multiple `instantiators` in the `Zenstruck\Foundry\Factory`? Would it be the right solution? (same question applies for other callback like this one, I think)

Thank you

**Comment by flohw** [comment]
A solution which seems to work:

```php
class UnitFactory extends \Factiry\Tests\ModelFactory
{
// Same code as previously
    public function initialize(): self
    {
        return $this->instantiateWith(function (array $attributes, string $class) {
            return (new Instantiator())->withoutConstructor()->allowExtraAttributes(['id'])($attributes, $class);
        });
    }

    // This method goes int parent class instead
    public function withId(int $id): self
    {
        return $this->addState(['id' => $id]);
    }
}
```

But this solution may break the requirement of my model, if there is any solution which can mix this solutions, I would be extremely happy! :grinning:

**Comment by kbond** [comment]
Have you considered "always forcing all properties"?

This is the way I use foundry. I don't think it's a popular approach but for me, foundry provides a map between my entities and the raw database values. I think of my factories as unserializing entities from raw data.

**Comment by flohw** [comment]
Hi @kbond 

I tried your second solution which works. As `afterInstantiate` allows multiple callbacks, I will go with this solution.

I also agree with the first one but one of our objectives on the project is also to have better fixtures which aligns with our model and allowing this behavior would break this requirement. If the second solution hadn't worked, I would have take this one.

Thank you for your help.

I will let you the choice of closing the issue or keeping it to also allow multiple callbacks for the `instantiateWith`.
I do agree that multiple `instantiateWith` is not very logical and could lead to a lot of problem but it might be a use case. I let you the choice of closing the issue :wink:

**Comment by kbond** [comment]
Glad that solution worked! I'm going to close for now. As you say, multiple instantiators doesn't seem right and could be confusing.
