### ISSUE TITLE
Foundry factory not using validation constraints?

### ISSUE THREAD

**Issue by GrandOurs35** [zenstruck/foundry#258]
Hello,

first of all, thanks for this excellent bundle.

I have a problem when creating factories with validation constraints on my Doctrine Entity.

For example, my User Class  has this property:

```
    #[ORM\Column(type: 'string', length: 10)]
    #[Groups(["user:collection:post",  "admin:read"])]
    #[Assert\Type('string')]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 5,
        max: 5,
    )]
    #[Assert\Regex('/^[0-9]{5}$/')]
    private string $zipCode;
```

When creating the default config of my factory, i did this by mistake;

```
        return [
             ...
            'zipCode' => '75 000',
            'city' => self::faker()->city(),
        ];
```

so you can notice that the zipCode is invalid but Foundry is still able to persist this object. 
I tried with other fields, different constraints and with attributes/annotations but in every case the validation is not applied when Foundry persist the object.
I have the same behavior when using Foundry for testing or for fixtures in dev.
My validation works fine when using Api Platform for example.

Is it a normal behavior? Do you know what i am missing?

My config:
PHP 8.1
Symfony 6.0.4

Thanks for your help

**Comment by kbond** [comment]
Basically, it is normal behaviour. Foundry is unaware of the validator. It just instantiates entities and persists them. In your case it's the same as:

```php
$user = new User();
$user->setZipCode('some invalid zip code');
// ...

$em->persist($user);
$em->flush();
```

**Comment by kbond** [comment]
You could use the [`afterInstantiate`](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#events-hooks) hook to validate the entities before persisting.

```php
PostFactory::new()
    ->afterInstantiate(function (User $user) {
        $errors = $this->validator->validate($author);

        if (count($errors) > 0) {
            // validation failed
        }
    })
    ->create('zipCode' => 'invalid')
;
```

You could generalize and add this to a base `ModelFactory` class that all your factories use.

**Comment by GrandOurs35** [comment]
Hi,
Thanks a lot for your answer and for the tip about afterInstantiate, i will try this!
