### ISSUE TITLE
Can I really truncate a table?

### ISSUE THREAD

**Issue by nyssLab** [zenstruck/foundry#264]
This is more of a question or feature request, than an issue.

I couldn't find it in the docs, so is it possible to truncate a table using Factories?

and by that I mean: `TRUNCATE TABLE table_name` and not `DELETE FROM table_name`

I want to be able to reset the IDs of a table.

**Comment by kbond** [comment]
Unfortunately, no, Doctrine doesn't allow this out of the box. You can see some of the complexities required [here](https://stackoverflow.com/questions/9686888/how-to-truncate-a-table-using-doctrine-2).
