### ISSUE TITLE
DelayFlush does not persist ? 

### ISSUE THREAD

**Issue by neholouis** [zenstruck/foundry#268]
Hello there ! 

Thanks for your amazing bundle, it saves me a whole lot of time.

I'm encountering what I think is an issue, when I want to use the Factory::delayFlush(callback()) method, I'm encountering the following error when I'm using the random method from the ProxyRepository class to create a .

Here's the error : 

  At least 1 "App\Entity\MyEntity" object(s) must have been persisted (0 persisted).  

Has anyone encountered this error ?

Thanks !

**Comment by kbond** [comment]
Are you creating everything within the callback?

**Comment by kbond** [comment]
Everything in the callback is persisted/flushed *after* the callback is called. 

```php
// won't work:
Factory::delayFlush(function() {
   SomeFactory::createMany(10);

   AnotherFactory::createOne(['other' => SomeFactory::random()]); // error
});

// should work:
SomeFactory::createMany(10);

Factory::delayFlush(function() {
   AnotherFactory::createOne(['other' => SomeFactory::random()]);
});
```
