### ISSUE TITLE
Factory for embeddable classes only working when using "withoutPersisting"

### ISSUE THREAD

**Issue by mergeMarc** [zenstruck/foundry#270]
I have multiple embedded classes and factories for those. I get an exception like this when i don't initialize all those factories with 'withoutPersisting()' (in this example ProcessedSms is a embeddable class):

```
In ORMInvalidArgumentException.php line 63:
                                                                               
  [Doctrine\ORM\ORMInvalidArgumentException]                                   
  The given entity of type 'MyVendor\MyProject\Message\ProcessedSms' (MyVendor\MyProject\Message\ProcessedSms@541)
  has no identity/no id values set. It cannot be added to the identity map.  
```

Is this intended behavior? I think that #192 says otherwise.
If this is intended behavior it would be nice if the docs would mention having to use `withoutPersisting()` with embeddables.

Please note that i'm using Foundry for the first time so it could be an issue on my side.

**Comment by kbond** [comment]
You should not have to call `->withoutPersisting()` on embeddables. Can you share some example code? Perhaps you discovered an edge case.

**Comment by mergeMarc** [comment]
I quickly threw together an example project to replicate the issue: [FoundryExample](https://github.com/mergeMarc/FoundryExample)

When i run `php bin/console doctrine:fixtures:load` i get the following exception in that project:
```
In ORMInvalidArgumentException.php line 66:
                                                                               
  The given entity of type 'App\Entity\IcEngine' (App\Entity\IcEngine@218) has no 
  identity/no id values set. It cannot be added to the identity map.
```

I commented out the `->withoutPersisting()` in the factories. If those are uncommented everything works fine.

**Comment by kbond** [comment]
Perfect, thank you. Will debug deeper but my first thought is the nested embeddables is the issue. I've never come across this but if Doctrine supports, then foundry should as well.
