### ISSUE TITLE
Foundry and PHPStan errors

### ISSUE THREAD

**Issue by benr77** [zenstruck/foundry#272]
I have implemented Foundry to generate all the test fixtures for my app. It's working nicely - thank you.

However, when I run my static analysis with PHPStan, I see hundreds of errors such as:

```
Call to an undefined method App\Domain\Model\User|Zenstruck\Foundry\Proxy::getId()
```

This is because I am using the `getId()` method in my test - for example to build the route for a controller in a functional test.

I could of course add an annotation to make PHPStan happy -  e.g.

```
/** @var User $user */
$user = UserFactory::last();
```

However, this would have to be done many, many times and it does not seem like a smart way to deal with it.

Can you suggest any potential solutions? Am I missing something obvious? Thanks.

**Comment by kbond** [comment]
Hey @benr77, there was some work done to add psalm support but there are a lot of supressed exceptions because of the complexity of the proxy system.

In your `UserFactory`, instead of `App\Domain\Model\User|Zenstruck\Foundry\Proxy` for the `@method` annotations, does `App\Domain\Model\User&Zenstruck\Foundry\Proxy` help (`&` instead of `|`)?

**Comment by benr77** [comment]
Yes, this seems to keep PHPStan happy but now my PHPStorm inspections are warning me that `getId()` does not exist on `Proxy` etc - so the problem is reversed. 

(latest 2022.1 PHPStorm - does it support intersection types in @method annotations?). 

Thanks

**Comment by kbond** [comment]
Darn, yeah, that's why it's set to `|` currently. Had to choose between making psalm/phpstan happy or giving autocompletion. Figured autocompletion was the better choice...

Was hoping a PHPStorm update would begin supporting intersections in annotations, then switch but guess it's not supported yet.

**Comment by benr77** [comment]
Ok I would agree the autocompletion is more important.

For the moment I will leave it as `|` and then add a rule so PHPStan ignores this error.

Thanks for the help.

**Comment by kbond** [comment]
What about leaving the method annotation as is for phpstorm autocompletion and adding `@phpstan-method App\Domain\Model\User&Zenstruck\Foundry\Proxy`

(I don't know if `@phpstan-method` is a thing)

**Comment by benr77** [comment]
Great idea. This works! It doesn't seem to be in the [PHPStan docs](https://phpstan.org/writing-php-code/phpdocs-basics#prefixed-tags) yet, but the `@phpstan-method` annotation is supported.

I'm using the "long" version of the Foundry factory annotations (as generated by the MakerBundle command). If I duplicate all the `@method` lines to use `@phpstan-method` this is going to be a very large docblock. 

So I tried the "short" version of the annotations as per the Foundry docs example (without even trying `@phpstan-method`), and this works fine for PHPStan but not for PHPStorm (latest 2022.1) which now does not do the auto-complete. I've opened a separate issue for this is #273.

So currently, the only working solution is to use the "long" version of the annotations in my factory classes, AND to duplicate all the `@method` calls (at least the ones that are in use by my app) with `@phpstan-method` copies.

**Comment by pmatejczukpl** [comment]
Hello, I have used `@phpstan-method` doc blocks with the intersection types but PHPStorm reports two errors: "Method with same name already defined in this class" and "Another definition with same name exists in this file". Do you also have these errors? How to make PHPStorm happy about this?
![Snipaste_2022-09-12_10-30-04](https://user-images.githubusercontent.com/42750739/189609030-55182460-abc2-4e07-bbbb-df5f89669303.png)

**Comment by kbond** [comment]
PHPStan has no issues? Does PHPStorm provide the correct auto-completion?

I think this might have to be something you have to live with until [this PHPStorm issue](https://youtrack.jetbrains.com/issue/WI-62217/Support-intersection-types-for-method) is resolved...

**Comment by MichaelBrauner** [comment]
Yes, I also have the problem. Can't you at least turn it off somehow?
