### ISSUE TITLE
"Short" version of PHPDoc annotations does not allow PHPStorm to auto-complete

### ISSUE THREAD

**Issue by benr77** [zenstruck/foundry#273]
When creating a factory using the MakerBundle command, or copying from the docs, you get the "long" version of the PHPDoc annotations.

I'm running the latest PHPStorm (2022.1), and the docs state that a "short" version of the annotations can be used if you are running PHPStorm 2021.2+.

However, this short version of the annotations does NOT give me auto-complete in PHPStorm (although PHPStan is happy).

So it seems the "short" annotations are not working as a replacement for the "long" version of the annotations.

### Example Long Version
```php
/**
 * @extends ModelFactory<User>
 *
 * @method static     User|Proxy createOne(array $attributes = [])
 * @method static     User[]|Proxy[] createMany(int $number, array|callable $attributes = [])
 * @method static     User|Proxy find(object|array|mixed $criteria)
 * @method static     User|Proxy findOrCreate(array $attributes)
 * @method static     User|Proxy first(string $sortedField = 'id')
 * @method static     User|Proxy last(string $sortedField = 'id')
 * @method static     User|Proxy random(array $attributes = [])
 * @method static     User|Proxy randomOrCreate(array $attributes = [])
 * @method static     User[]|Proxy[] all()
 * @method static     User[]|Proxy[] findBy(array $attributes)
 * @method static     User[]|Proxy[] randomSet(int $number, array $attributes = [])
 * @method static     User[]|Proxy[] randomRange(int $min, int $max, array $attributes = [])
 * @method User|Proxy create(array|callable $attributes = [])
 */
```

### Example Short Version
```php
/**
 * @extends ModelFactory<User>
 *
 * @method static User[]|Proxy[] createMany(int $number, array|callable $attributes = [])
 * @method static UserRepository|RepositoryProxy repository()
 * @method User|Proxy create(array|callable $attributes = [])
 */
```

**Comment by kbond** [comment]
Ah you're right. I think what's best is to remove the note in the docs showing the short version and replace with what we discovered about `@phpstan-method` in #272. WDYT?

**Comment by kbond** [comment]
To clarify, is this what would be required to have autocompletion in PHPStorm and a happy PHPStan?

```php
/**
 * @extends ModelFactory<User>
 *
 * @method static     User|Proxy createOne(array $attributes = [])
 * @method static     User[]|Proxy[] createMany(int $number, array|callable $attributes = [])
 * @method static     User|Proxy find(object|array|mixed $criteria)
 * @method static     User|Proxy findOrCreate(array $attributes)
 * @method static     User|Proxy first(string $sortedField = 'id')
 * @method static     User|Proxy last(string $sortedField = 'id')
 * @method static     User|Proxy random(array $attributes = [])
 * @method static     User|Proxy randomOrCreate(array $attributes = [])
 * @method static     User[]|Proxy[] all()
 * @method static     User[]|Proxy[] findBy(array $attributes)
 * @method static     User[]|Proxy[] randomSet(int $number, array $attributes = [])
 * @method static     User[]|Proxy[] randomRange(int $min, int $max, array $attributes = [])
 * @method User|Proxy create(array|callable $attributes = [])
 *
 * @phpstan-method static     User&Proxy createOne(array $attributes = [])
 * @phpstan-method static     User[]&Proxy[] createMany(int $number, array|callable $attributes = [])
 * @phpstan-method static     User&Proxy find(object|array|mixed $criteria)
 * @phpstan-method static     User&Proxy findOrCreate(array $attributes)
 * @phpstan-method static     User&Proxy first(string $sortedField = 'id')
 * @phpstan-method static     User&Proxy last(string $sortedField = 'id')
 * @phpstan-method static     User&Proxy random(array $attributes = [])
 * @phpstan-method static     User&Proxy randomOrCreate(array $attributes = [])
 * @phpstan-method static     User[]&Proxy[] all()
 * @phpstan-method static     User[]&Proxy[] findBy(array $attributes)
 * @phpstan-method static     User[]&Proxy[] randomSet(int $number, array $attributes = [])
 * @phpstan-method static     User[]&Proxy[] randomRange(int $min, int $max, array $attributes = [])
 * @phpstan-method User&Proxy create(array|callable $attributes = [])
 */
```

**Comment by benr77** [comment]
I checked and simply had to start adding what's missing in the short version, to make the PHPStorm autocompletion work - essentially if you use all the methods you'd end up adding all the annotations and ending up with the long version anyway.

If the short version is not working, at least removing that from the docs will avoid any future confusion.

I'm not sure about simply adding all the `@phpstan-method` annotations as well - this would make the docblock huge, and I guess the same might be needed for Psalm as well??? Maybe better to just add an exclusion in PHPStan's configuration for the time being.

PHPStorm says it supports intersection types in annotations from v2021.3, but the example given is for `@param` and not `@method`:
https://blog.jetbrains.com/phpstorm/2021/12/phpstorm-2021-3-release/#pure_intersection_types

**Comment by kbond** [comment]
I would not add to the maker, just a note in the docs (replacing the short version note) showing how you can optionally support PHPStan.

Not sure about psalm. Wait until we hear otherwise for it I guess.

**Comment by benr77** [comment]
Boom! That bug report is what I've just been searching for. At least it's been logged with JetBrains.

I think the changes to the docs that you propose is the best compromise for the moment.
