### ISSUE TITLE
Create embedded entity without duplicated property not working

### ISSUE THREAD

**Issue by BernardA** [zenstruck/foundry#287]
I have an entity MultiChannel that has a `OneToMany` relation with SalesChannel.

The restriction is that MultiChannel cannot have 2 SalesChannels that have the same `name` property.

Initially I had created the `Story` below, but that will endup with SalesChannels that have the same `name`.

App/Tests/Story/MultiChannelStory

       final class MultiChannelStory extends Story
    {
        public function build(): void
    {

        SalesChannelFactory::createMany(100);

        MultiChannelFactory::createMany(50, function() {
            return [
                'salesChannel' => SalesChannelFactory::randomRange(1,3),
             ];
         });
      }
    }

Then I created a SalesChannelStory as below:

App/Tests/Story/SalesChannelStory

      final class SalesChannelStory extends Story
    {
    public function build(): void
    {
        $this->addToPool('name1', SalesChannelFactory::new(['name' => SalesChannelFactory::SALES_CHANNELS[0]])->many(50));
        $this->addToPool('name2', SalesChannelFactory::new(['name' => SalesChannelFactory::SALES_CHANNELS[1]])->many(50));
        $this->addToPool('name3', SalesChannelFactory::new(['name' => SalesChannelFactory::SALES_CHANNELS[2]])->many(50));
        $this->addToPool('name4', SalesChannelFactory::new(['name' => SalesChannelFactory::SALES_CHANNELS[3]])->many(50));
      }
    }

The intention was to do something as below on MultiChannelStory, in somewhat pseudo code, so that 
I could insert only uniquely named SalesChannel into MultiChannel:

App/Tests/Story/MultiChannelStory

       final class MultiChannelStory extends Story
    {
        public function build(): void
    {

        SalesChannelFactory::createMany(100);

        MultiChannelFactory::createMany(50, function() {
            return [
                'salesChannel' => $this->getUniqueNamed(),,
             ];
         });
      }
    }

     private function getUniqueNamed(): \App\Entity\SalesChannel|\Zenstruck\Foundry\Proxy
    {
     // get up to 4 SalesChannel without the property `name`  being repeated.
        $items = [SalesChannelStory::getRandom('name1'), SalesChannelStory::getRandom('name2')];
        return $items;
        //return SalesChannelStory::getRandom('name1');
    }

But that does not work. 

Note that MultiChannel has to have at least one SalesChannel, up to as many SalesChannel exists, or 4 currently.

**Comment by kbond** [comment]
Hey @BernardA!

So I guess `SalesChannel` has a unique constraint based on `name` and `multi_channel_id`?

What about making all `SalesChannel` factories with a unique name (ie pretend the unique constraint is on `name` only).

**Comment by BernardA** [comment]
Thanks @kbond and you guessed right. I do have that constraint.
What I believe you are suggesting would be a work around the constraint  and while that might do for some basic test it would not suffice.
I use Foundry also to generate Doctrine Fixtures and there I definitely need the proper SalesChannel name, not a random string.
But your answer did get me worried in that it might mean that there's no proper solution to this user case.

**Comment by kbond** [comment]
Yeah, not seeing a nice out of the box solution. What about a custom factory method: 

```php
class SalesChannelFactory extends ModelFactory
{
    /**
     * @return self[]
     */
    public static function uniqueSet(int $min = 1, int $max = 3): array
    {
        $uniqueNames = // .. generate x unique names

        return array_map(fn($name) => SalesChannel::new(['name' => $name]), $uniqueNames);
    }
}
```

Then to use:

```php
MultiChannelFactory::createMany(50, function() {
    return [
        'salesChannel' => SalesChannelFactory::uniqueSet(1,3),
    ];
});
```

**Comment by BernardA** [comment]
With a slight change on my setup, the following seems to work:

               $qty = 50;

        MultiChannelFactory::createMany(30);
        for ($i = 0; $i < count(SalesChannel::SALES_CHANNELS); $i++) {
            SalesChannelNameFactory::new()
                ->withAttributes([
                    'name' => SalesChannel::SALES_CHANNELS[$i],
            ])
            ->create();
        }


        for ($i = 0; $i < $qty; $i++) {
            SalesChannelFactory::new()
            ->withAttributes([
                'salesChannelName' => $this->createItem('salesChannelName')
            ])
            ->withAttributes([
                'multiChannel' => $this->createItem('multiChannel'),
            ])
            ->create();
        }
