### ISSUE TITLE
Strange error message about deprecation.

### ISSUE THREAD

**Issue by gazzatav** [zenstruck/foundry#288]
I'm working through the SymfonyCasts tutorials for Symfony 5 and have v1.21.0 installed.  When I create a factory and add state like this:

`QuestionFactory::new()->unpublished()->createMany(5);`

I get this weird message (when loading fixtures).  I wouldn't mind if what it told me to do actually worked but the instruction is to do exactly the same as what has been deprecated (except it doesn't work because of the single colon).

> "User Deprecated: Since zenstruck/foundry 1.7: Calling instance method "App\Factory\QuestionFactory::createMany()" is deprecated and will be removed in 2.0, use the static "App\Factory\QuestionFactory:createMany()" method instead.

I realise this may be out of date by now  but would appreciate an explanation and/or suggestion as to how I can make Factory.php happy again. 

EDIT: I see this is related to #115 and the error disappears after changing the line to:

`QuestionFactory::new()->unpublished()->many(5)->create();`

I still think the actual message could be improved!

**Comment by kbond** [comment]
Yes, I agree, what about 

> Calling instance method "App\Factory\QuestionFactory::createMany(x)" is deprecated and will be removed in 2.0, use "$factory->many(x)->create()" instead.

**Comment by gazzatav** [comment]
Yes, `$factory->many(x)->create()"` would have been helpful to me.  It is the replacement for the function called rather than a different function, which cannot be used in the same situation.  How much of the error is programmatically generated though?  I notice that it names the user class in the error.

**Comment by kbond** [comment]
> How much of the error is programmatically generated though?

You can see where the error is generated here: https://github.com/zenstruck/foundry/blob/a535f83ef65680a63f615d64b04219cdeee35f1b/src/Factory.php#L69

> I notice that it names the user class in the error.

Yes, I use `static::class` to get the name of your `ModelFactory` class.

---

Would you be willing to create a PR?

**Comment by gazzatav** [comment]
Yes, no problem.  I'm not a PHP expert but it looks like it's just that string that changes.   Are you happy to have a longer, more comprehensive message, or would you prefer to keep it to the above i.e. `$factory->many(x)->create()`?

**Comment by kbond** [comment]
Let's just change it exactly what I have above. The current message is confusing as you've found and doesn't show the proper upgrade path.

**Comment by gazzatav** [comment]
I was just thinking that as you have the static class there and as all the comments I've seen on this were people in the same boat as me, the 'what to do' part of the message could be:

use %1$s::new()->yourStateAdapter()->many(x)->create() instead or in addition but maybe it's too specific to a single use case.

**Comment by kbond** [comment]
Ok, we could replace the `x` with the actual number passed as well.

**Comment by gazzatav** [comment]
How do I access the $min value going into the FactoryCollection inside trigger_deprecation?

This works - works for me locally - don't know reliable it is.

        `trigger_deprecation('zenstruck/foundry', '1.7', 'Calling instance method "%1$s::createMany()" is deprecated and will be removed in 2.0, use e.g. "%1$s::new()->stateAdapter()->many(%2$s)->create()" instead.', static::class, $arguments[0]);`

**Comment by kbond** [comment]
Don't worry, I fixed it up. The test suite is messy.
