### ISSUE TITLE
Postpersist doesn't work for the 2nd time

### ISSUE THREAD

**Issue by ghostika** [zenstruck/foundry#292]
I use the bundle together with Behat. Behat has a `beforeScenario` step, to purge the DB.

I have for the given entity - for example `User` -  post persist calculation and the postPersist contains a flush as well. For Foundry, Autofersh is set to `true` by default.

I create it like this for the user:
```
$user = UserFactory::new()->create()->disableAutoRefresh()
```

If I have 2 Behat scenario, for the first test, everything goes though without a problem, the `flush` goes through from the postPersist, but for the second scenario, it doesn't, so I had to call `disableAutoRefresh` after I created a new User with a factory.

I have nothing special set up for Foundry, just the default setting.

The problem comes, that in the `function object()` it checks, if there is something in the changeset, which is not yet saved. Eventghoug for the second run, the changes are there from the `postPersist` - not saved into the DB, even though the flush is in the code - if I call a `$user->save()` nothing is saved actually.

I can solve things also by disabling the listener, but the perfect solution would be, if they could run correctly and always, not just for the first Scenario.

**Comment by kbond** [comment]
Hey @ghostika, sounds a bit similar to https://github.com/zenstruck/foundry/issues/234. WDYT?

**Comment by ghostika** [comment]
@kbond  I've seen that ticket as well. I don't think that it's the same problem. 
As I mentioned, the first time it works perfectly, even the post persist part is saved into the DB.
Then in the second scenario - in-between I purge the `SQLite` DB - the user fixture is loaded into the DB, it's there, but the part of the post persist doesn't work any more. 


I tried that I booted Foundry with fromContainer and withConfiguration , but then I received an error like this: 
```
Model Factories with dependencies (Model Factory services) cannot be used without the foundry bundle.
```
The UserFactory has a dependency.

**Comment by kbond** [comment]
I'm sort of thinking that somehow the object is still managed by doctrine in the second scenario, so when it tries to save, it see's it's already there (even though it's not).

Before creating the entity in the second scenario, can you try clearing the em?

**Comment by ghostika** [comment]
Hm, accidentally I left the `TestState::bootFromContainer($this->container);` inside and re-enabled the FoundryBundle inside the bundles.php and that solved the previous `Model Factories with dependencies ...` issue, the rest worked then.

I think the ticket can be closed, but in any case, it's interesting; the DB is in sync with the changes from postPersist as well.
