### ISSUE TITLE
The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by Aerendir** [zenstruck/foundry#293]
Running my tests, this is the error I get:

> The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces

I have many mappings registered for Doctrine: may be this is the cause of the issue?

I'm trying to configure one more mapping for Foundry, but don't know what to use as `type`:  the `Proxy` class doesn't have any annotation nor attribute and I cannot find a mapping configuration in `Resources` or in other folders...

Any ideas about how to fix this?

UPDATE

If I create entities from inside a controller, the error doesn't happen.
It happens only when I create entities from inside fixtures running `symfony console doctrine:fixtures:load -n`.
Fixtures are in the folder `fixtures`, in the root folder:

```
my-project
    - fixtures // From inside here, it DOESN'T work
    - src // From inside here, it works
```

**Comment by kbond** [comment]
> If I create entities from inside a controller, the error doesn't happen.

This is telling. I think somehow your fixture folder isn't autoloaded.

**Comment by Aerendir** [comment]
# What I did

I have to fixture classes:

```php
<?php

// ./fixtures/UsersFixture.php

namespace App\Fixtures;

use App\Dev\Factory\UserFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class UsersFixtures extends Fixture
{
    public const SUPER_ADMIN_REF = 'user_super_admin';
    public const SUPER_ADMIN_EMAIL = 'super_admin@example.com';

    public function load(ObjectManager $manager): void
    {
        $users = [
            self::SUPER_ADMIN_REF => UserFactory::createOne(['email' => self::SUPER_ADMIN_EMAIL, 'plainPassword' => self::SUPER_ADMIN_EMAIL, 'roles' => ['ROLE_USER', 'ROLE_SUPER_ADMIN']]),
        ];

        foreach ($users as $ref => $user) {
            $this->addReference($ref, $user);
        }
    }
}
```

and

```php
<?php

// ./fixtures/AccountsFixture.php

namespace App\Fixtures;

use App\Dev\Factory\AccountFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class AccountsFixtures extends Fixture implements DependentFixtureInterface
{
    public const ACCOUNT_1_REF = 'account_1';

    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create();

        $accounts = [
            self::ACCOUNT_1_REF => AccountFactory::createOne(['name' => $faker->company, 'owner' => $this->getReference(UsersFixtures::SUPER_ADMIN_REF)]),
            self::ACCOUNT_2_REF => AccountFactory::createOne(['name' => $faker->company, 'owner' => $this->getReference(UsersFixtures::MERCHANT_REF)]),
            self::ACCOUNT_3_REF => AccountFactory::createOne(['name' => $faker->company, 'owner' => $this->getReference(UsersFixtures::EMPLOYEE_REF)]),
        ];

        foreach ($accounts as $ref => $account) {
            $this->addReference($ref, $account);
        }
    }

    public function getDependencies():array
    {
        return [
            UsersFixtures::class,
        ];
    }
}
```

Now, with this code, I get the error

> The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces App\Common\Entity, App\MyNamespace\Entity, App\MyNamespace2\Entity, App\MyNamespace3\Entity, App\MyNamespace4\Entity, App\MyNamespace5\Entity, App\MyNamespace6\Entity, App\MyNamespace7\Entity, App\MyNamespace8\Entity, SerendipityHQ\Bundle\MyBundle\Entity, SerendipityHQ\Bundle\AwsSesMonitorBundle\Entity

To get them work, I need to change the configuration to this:

```diff
when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
-       auto_refresh_proxies: true
+       auto_refresh_proxies: false

when@test: *dev
```

Then I need to change fixtures this way:

```diff
...
+       /** @var Proxy $user */
        foreach ($users as $ref => $user) {
-           $this->addReference($ref, $user);
+           $this->addReference($ref, $user->object());
        }
...
```

With this configuration, all works well.

Obviously, I'd like to make them work without calling `->object()` and without disabling `auto_refresh_proxies`.

Now, is my way of configuring the bundle the "ordinary" way, or the bundle is meant to be used the way in this moment doesn't work for me (and so, I have to find which is the problem and fix it)?

**Comment by kbond** [comment]
Ok, I think I see the problem: `$this->addReference($ref, $user->object());` is required as this method requires a real Doctrine entity object - no way around this.

I don't see why `auto_refresh_proxies: false` makes a difference though. Does it work with keeping it as `true` and `$this->addReference($ref, $user->object());`?

**Comment by Aerendir** [comment]
> Ok, I think I see the problem: `$this->addReference($ref, $user->object());` is required as this method requires a real Doctrine entity object - no way around this.

The method `addReference()` itslef accepts any kind of `object`: the problem arise when I set the object in another entity:

```php
self::ACCOUNT_1_REF => AccountFactory::createOne(['name' => self::ACCOUNT_1_NAME, 'owner' => $this->getReference(UsersFixtures::SUPER_ADMIN_REF)]),
```

In this case, I receive the error about `Proxy` not in the configured namespaces.

> I don't see why `auto_refresh_proxies: false` makes a difference though. Does it work with keeping it as `true` and `$this->addReference($ref, $user->object());`?

No, it doesn't work with `auto_refresh_proxies: true`:

> Cannot auto refresh "App\Entity\User" as there are unsaved changes. Be sure to call ->save() or disable auto refreshing (see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh for details).

If I use `->save()`, as suggested, anyway the error remains:

```php
self::SUPER_ADMIN_REF => UserFactory::createOne(['email' => self::SUPER_ADMIN_EMAIL, 'plainPassword' => self::SUPER_ADMIN_EMAIL, 'roles' => ['ROLE_USER', 'ROLE_SUPER_ADMIN']])->save(),
```

If, instead, I explicitly call `->disableAutoRefresh()` (and leave `auto_refresh_proxies: true`), then the error disappears:

```php
self::SUPER_ADMIN_REF => UserFactory::createOne(['email' => self::SUPER_ADMIN_EMAIL, 'plainPassword' => self::SUPER_ADMIN_EMAIL, 'roles' => ['ROLE_USER', 'ROLE_SUPER_ADMIN']])->disableAutoRefresh(),
```

What I'm trying to understand is which is the expected behaviour of the library when working with `DoctrineFixturesBundle` and references: should have I to use `disableAutorefresh()`? Should have I to pass `->object()` instead of the `Proxy` object? I'm not well understanding and in the docs there is no example of this use case.

**Comment by kbond** [comment]
> In this case, I receive the error about Proxy not in the configured namespaces.

Admittedly, I have never worked with the reference feature of DoctrineFixturesBundle but from what I can see, the reference needs to be a valid doctrine entity, this is the cause of the this error.

> Should have I to pass ->object() instead of the Proxy object?

Yes.

> should have I to use disableAutorefresh()?

Basically what's happening is something is changing on the `User` (I think during `AccountFactory::createOne(...)`). This puts the object in a _dirty state_ so the next time it auto-refreshes, this is detected and the exception thrown. This is meant to prevent you from refreshing the object when there are _unsaved_ changes (and losing them).

What does the method `Account::setOwner()` look like? What is the relationship between `Account` and `User`? Is it one-to-one?

**Comment by Chris53897** [comment]
Thanks for sharing the solution @Aerendir 
I run into a similiar problem.
The Problem was i tried to run ->persist and manager->flush(). I removed them.

I did set `auto_refresh_proxies: false` to solve this.
But i do not use ->addReferences() at the moment.

Can someone share there setup of Fixtures working wirh `auto_refresh_proxies: false`?

Is there a possibility to set auto_refresh_proxies at runtime or different for Fixtures?

**Comment by kbond** [comment]
Hey @Chris53897, if `auto_refresh_proxies: false`, you can enable it for a created fixture after creating:

```php
$object = UserFactory::createOne()->enableAutoRefresh();
```

If `auto_refresh_proxies: true`, you can disable on a factory-by-factory basis (admittedly, it's a little verbose):

```php
$object = UserFactory::new()->withoutPersisting()->create()->save()->disableAutoRefresh();

$object->manipulate();
$object->manipulateMore();

$object->save(); // saves the changes
```

**Comment by Chris53897** [comment]
Thanks. I will have a look. I guess i will stay with the first option `auto_refresh_proxies: false`

I did try to create a BaseFixture Class and a call to disable it. 
But this does not work.

```
public function load(ObjectManager $manager): void
    {
        TestState::disableDefaultProxyAutoRefresh();
    }
```

and specifix Fixture

`public function load(ObjectManager $manager): void
    {
        parent::load($manager);

        ...
    }`

**Comment by kbond** [comment]
Yeah the TestState is only honoured when running tests.

**Comment by nikophil** [comment]
I think this problem does not occur anymore
