### ISSUE TITLE
Looking for guidance to deal with skeptical team

### ISSUE THREAD

**Issue by torian257x** [zenstruck/foundry#299]
The app we have is old, over 10 years. As a result, people are VERY hesitant to adapt something new, libraries that will not be supported any longer in say, 5 years. They just did a migration to php8 and it was painful for them. The project has over 300 tables as well... which in theory means, it could profit a lot from foundry imho.

One idea I heard was that we could just use foundry to create the necessary classes and then remove the library again. Would that even be possible?

What is the roadmap for the next whatever, 6 years? project will be abandoned?

**Comment by kbond** [comment]
Hey!

> One idea I heard was that we could just use foundry to create the necessary classes and then remove the library again. Would that even be possible?

No, I can't think of how that would be possible.

> What is the roadmap for the next whatever, 6 years?

Nothing concrete, I'd like to get a [2.x released](https://github.com/zenstruck/foundry/issues/110) at some point.

> project will be abandoned?

Can't predict for sure but I have no intention of abandoning it's maintenance. Even if I did, I think Foundry is well-used enough that someone would take over (probably even another Symfony core team member).

---

Hope this helps!

**Comment by kbond** [comment]
FYI, @nikophil is now a co-maintainer of this library.
