### ISSUE TITLE
Support for nested property paths

### ISSUE THREAD

**Issue by NorthBlue333** [zenstruck/foundry#307]
Hi, it's me again :wave: 

I am currently doing this in my factories:

```php
class CommentFactory {
  public function getDefaults(): array
  {
    return ['user' => UserFactory::new()];
  }

  public function withUserName(): array
  {
    return ['user.name' => 'foo'];
  }

  public function withUserRelation(): array
  {
    // does not work
    return ['user.posts' => PostFactory::new()->many(5)];
  }
}
```

Which works, I assume thanks to Symfony `PropertyAccess` component (?). But setting a relation this way does not work because the Factory cannot resolve the relation.

I do not really know how to implement it correctly; also, in some cases I am wondering if the first case can fail (if the object is not set first on the entity in example).

Should this be supported?

My current workaround is to use an `afterInstantiate/afterPersist` hook.

**Comment by kbond** [comment]
> I do not really know how to implement it correctly; also, in some cases I am wondering if the first case can fail (if the object is not set first on the entity in example).

Yeah, I think you're right.

> Should this be supported?

My first thought is no just because of the added complexity. We'd have to override the functionality of property access I think.

Either your afterInstantiate hook or using states would be best:

```php
public function withUser(string $name, int $numPosts): self
{
    return $this->addState(['user' => [
        'name' => $name,
        'posts' => PostFactory::new()->many($numPosts),
    ]]);
}
```

**Comment by NorthBlue333** [comment]
Actually after some thinking I thought of this flow for the`Factory::create` method:
* Loop on all attributes
* If the property path is nested, store it in an array keyed by first part of the path
* Loop again on all non-nested property paths
* If value is a Factory and property key exists in the array, then add a `withAttributes` call and unset the entry in the array
* Apply all nested attributes left in the array just like the other attributes. If it fails, it should be an error user-side.

(Instead of looping we could store differently nested paths in `withAttributes` method).

What do you think?

**Comment by kbond** [comment]
I think this could work but it would require that the factory have the relation in getDefaults(), no?

**Comment by NorthBlue333** [comment]
As stated in my last point, yes, this requires proper use. It might be by setting a default OR by setting the relation with states (as nested properties are always processed after in this flow). Do you ses anything else that would result in an error?

**Comment by kbond** [comment]
> Do you see anything else that would result in an error?

Could get tricky with embeddables...?

**Comment by NorthBlue333** [comment]
Yeah maybe that is my only concern but actually I think it would also work if it is correctly set up by the user. Might I make a PR with the according tests?

**Comment by NorthBlue333** [comment]
Sure will wait for #306 

I understand what you mean. I can make a suggestion, you are free to reject it!

**Comment by nikophil** [comment]
hey @NorthBlue333 

I'm wondering if this problem could not be fixed using:
```php
class CommentFactory {

  public function withUserAndPosts(): static
  {
    return $this->with(['user' => UserFactory::new(['posts' => PostFactory::new()->many(5))]);
    // OR
    return $this->with(['user' => UserFactory::new()->withPosts(5)]);
  }
}
```

I'm afraid that supporting nested attributes for relationships would add a lot of complexity with no real added value. But I might be wrong, feel free to open a PR :)
