### ISSUE TITLE
[feature] add a way to exclude database connection for mongo support on reset database

### ISSUE THREAD

**Issue by jbalieux** [zenstruck/foundry#311]
There's way to exclude database connection for the ORM with 
```
FOUNDRY_RESET_CONNECTIONS=connection1,connection2
FOUNDRY_RESET_OBJECT_MANAGERS=manager1,manager2
```
But we cannot exclude ODM connection for the moment.

It would be nice to add
```
FOUNDRY_RESET_ODM_CONNECTIONS
FOUNDRY_RESET_ODM_OBJECT_MANAGERS
```

**Comment by kbond** [comment]
`FOUNDRY_RESET_ODM_OBJECT_MANAGERS` should absolutely be possible. Not sure about `FOUNDRY_RESET_ODM_CONNECTIONS`, we don't look at mongo connections. @nikophil, any insight here?

**Comment by nikophil** [comment]
Indeed the only useful thing here would be `FOUNDRY_RESET_ODM_OBJECT_MANAGERS`.

This change is quite trivial, but I think it would be nice some day to add all these env vars to config options, and maybe remove "bundleless" usage as stated in https://github.com/zenstruck/foundry/issues/110

I can definitely work on this.

**Comment by kbond** [comment]
> I think it would be nice some day to add all these env vars to config options, and maybe remove "bundleless" usage as stated in #110

Agreed.
