### ISSUE TITLE
Improve exception message

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#332]
https://github.com/zenstruck/foundry/blob/210faff9429ae8777001b9c89178d4a7c87c3026/src/ModelFactoryManager.php#L33

This should instead explain that the Factory `$class` isn't registered as a service. Even better, detect if using in unit test, and explain that factories with deps cannot be used in unit tests.

Per @OskarStark.

**Comment by nikophil** [comment]
this has been fixed for a long time :)
