### ISSUE TITLE
Question about DTOs for Entity Constructors

### ISSUE THREAD

**Issue by gubler** [zenstruck/foundry#34]
I like the look of this bundle, but I have a question about the best way to use it in my projects:

I currently construct my Entities with DTOs (example for a User entity: `public function __construct(NewUserCommand $command)` and do not have setter methods.

Would it be better to pass the values through defaults and then generate the DTO in `beforeInstantiate()`:

```
PostFactory::new()
    ->beforeInstantiate(function(array $attributes): array {
        $command = new NewUserCommand();
        $command->username = $attributes['username'];

        return $command;
    })
```

or would it be better to use `withoutConstructor())` and `alwaysForceProperties()` (probably through the bundle configuration)?

**Comment by kbond** [comment]
For your example, you would have to do this:

```php
PostFactory::new()
    ->beforeInstantiate(function(array $attributes): array {
        $command = new NewUserCommand();
        $command->username = $attributes['username'];

        unset($attributes['username']); // unless `allow_extra_attributes` is true

        $attributes['command'] = $command;

        return $attributes;
    })
;
```

If all your entities are built this way, setting the `withoutConstructor()` and `alwaysForceProperties()` bundle config might be your best bet. Although, if you have a *mix*, you can override the `ModelFactory::initialize()` to set the desired instantiator on a factory-by-factory basis.

**Comment by kbond** [comment]
Alternatively, you can bypass using the provided instantiator entirely and use a callback:

```php
class PostFactory extends ModelFactory
{
    // ...

    protected function initialize(): self
    {
        return $this
            ->instantiateWith(function (array $attributes) {
                $command = new NewUserCommand();
                $command->username = $attributes['username'];

                return new Post($command);
            })
        ;
    }
}
```

**Comment by gubler** [comment]
All of my Entities use DTOs. I'll have to think about which of those two I want to go with, but thanks for the quick answer :)
