### ISSUE TITLE
Disable ORM filters

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#342]
Per @OskarStark.

Might be nice to provide a way to [disable](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/filters.html#disabling-enabling-filters-and-setting-parameters) ORM(/ODM?) filters.

Related to #216.

**Comment by nikophil** [comment]
I think ODM filters [are a thing](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.3/reference/filters.html) (never used them so far)

**Comment by nikophil** [comment]
I don't think we're gonna work on this, since the subject has not been raised for more than one year... feel free to reopen this if needed
