### ISSUE TITLE
readonly support for identifiers

### ISSUE THREAD

**Issue by benblub** [zenstruck/foundry#353]
If you use readonly on the id/identifier an error is thrown. Use readonly on `$title` works as expected. 

if we take a look into the code where the error is thrown..
if we look into the comparison, values are the same, so the object instance is not the same
```php
        if (parent::getValue($objectOrValue) !== $value) {
            throw new LogicException(sprintf('Attempting to change readonly property %s::$%s.', $this->class, $this->name));
        }
```

Stacktrace
```
LogicException : Attempting to change readonly property App\Foo\Domain\Model\Foo::$id.
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionReadonlyProperty.php:48
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2753
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:266
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:492
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:148
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:270
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:841
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2227
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2199
 /app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:711
 /app/vendor/zenstruck/foundry/src/Proxy.php:168
 /app/vendor/zenstruck/foundry/src/Proxy.php:131
```

Model/Entity
```php
#[ORM\Entity]
class Foo
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    public readonly UuidInterface $id;

    public function __construct(
        #[ORM\Embedded(columnPrefix: false)]
        public readonly Title $title,
    ) {
        $this->id = Uuid::uuid4();
    }
}
```

Factory
```php
    protected function getDefaults(): array
    {
        return [
            'title' => new Title('Foo..'),
        ];
    }

    protected function initialize(): self
    {
        return $this->instantiateWith((new Instantiator())->alwaysForceProperties());
    }
```

i didn't looked yet deep dive into the code how foundry instantiate the object and whats the different there between normal props and the identifier. With PHP 8.2 we get immutable classes, this examble used readonly probs -> PHP 8.1

https://stitcher.io/blog/php-81-readonly-properties

**Comment by kbond** [comment]
I've definitely seem some problems with readonly properties in doctrine that aren't fixed.

Are you sure this is foundry-specific?

What's the code that causes the problem?

```php
$object = FooFactory::create(); // ?

$object->id; // ?
$object->title; // ?
```

**Comment by kbond** [comment]
Does this work as expected (no foundry code):

```php
$foo = new Foo(new Title('foo...));
$em->persist($foo);
$em->flush();

$em->refresh($foo);
```

**Comment by benblub** [comment]
Hi Kevin `FooFactory::create();` throws the exception

i tested this without problems. Let me check refresh works or not.
```
$foo = new Foo(new Title('foo...));
$em->persist($foo);
$em->flush();
```

**Comment by benblub** [comment]
refresh works

**Comment by kbond** [comment]
Ok thanks, I'll have to dig into this.

**Comment by kbond** [comment]
> refresh works

Per a slack conversation with @benblub, it does not. I think:
- https://github.com/doctrine/orm/pull/10171
- https://github.com/doctrine/common/pull/999

Could be related

**Comment by nikophil** [comment]
In my experience, `readonly` is broken with value objects in Doctrine:

- https://github.com/doctrine/orm/issues/9505
- https://github.com/doctrine/orm/pull/9998
