### ISSUE TITLE
Makefile improvements

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#358]
- [x] find a way to easily add `--stop-on-failure` (I'm always adding it to the `Makefile` itself, and commit the file by mistake) https://github.com/zenstruck/foundry/pull/376
- [x] provide an easy way to switch phpunit context (use dama, use orm, use odm)  https://github.com/zenstruck/foundry/pull/375
- [x] fix `make sca` and `make fixcs` which always try to update composer https://github.com/zenstruck/foundry/pull/376
- [x] change php version with an env var https://github.com/zenstruck/foundry/pull/376

**Comment by kbond** [comment]
Is it possible to have `make test ...` pass all args to phpunit?

```
make test tests/foo/bar
make test --exclude-group foo
```

**Comment by nikophil** [comment]
I would love this
I have to dig in a little bit but I'l afraid options won't work

**Comment by nikophil** [comment]
:tada:
