### ISSUE TITLE
Rename service IDs

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#360]
[Ref](https://github.com/zenstruck/foundry/blob/20ac3499c224c7ad4f5fe3e5f4da04ad2330ea5d/src/Bundle/Resources/config/services.xml)

I recently learned that if you id a services with the class name, it makes it autowireable. We don't want this for foundry's services. Additionally, if you prefix the service id with `.`, it marks it as [_hidden_](https://symfony.com/blog/new-in-symfony-4-1-hidden-services) so users will not see them in `debug:container` by default.

**Comment by nikophil** [comment]
:exploding_head: didn't know both of these!

**Comment by kbond** [comment]
I'll open a PR once #357 is merged
