### ISSUE TITLE
Invalid schema name with custom Postgres schema on database reset

### ISSUE THREAD

**Issue by BernardA** [zenstruck/foundry#379]
Having this problem when using a custom schema on Postgres  when running `php bin/phpunit`:

>  Schema-Tool failed with Error 'An exception occurred while executing a query: SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  no schema has been selected to create in' while executing DDL

The app uses the `ResetDatabase` trait as below:

      namespace App\Tests;

      use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
     use Zenstruck\Foundry\Test\Factories;
     use Zenstruck\Foundry\Test\ResetDatabase;

     class CustomApiTestCase extends ApiTestCase
     {
         use Factories;
         use ResetDatabase;

         protected object $entityManager;
         private static object $container;

         protected function setUp(): void
         {
             $kernel = self::bootKernel();
             $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();
         }
     }

So, when the `ResetDatabase` runs `doctrine:schema:create` it throws the error above.

If I run `php bin/console doctrine:schema:create --env=test` on the terminal I will have the same error.

But If I beforehand execute these 2 queries it will work fine:

> php bin/console doctrine:query:sql "CREATE SCHEMA IF NOT EXISTS myschema AUTHORIZATION root;" --env=test

> php bin/console doctrine:query:sql "ALTER USER root SET search_path TO myschema;

Then my question is how to configure the `ResetDatabase` to take into account the custom schema. 

I did look at your config and there I run into another issue. 

As per [your documentation](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration) it would be possible to change the config with the `database_resetter` key. 

But if I attempt to use that key I get: 

> Unrecognized option "database_resetter" under "zenstruck_foundry". Available options are "auto_refresh_proxies", "faker", "instantiator".

Not sure if that would resolve my issue anyways, but that looks strange.

My config for `zenstruck` is:

       when@dev: &dev
                   zenstruck_foundry:
                         auto_refresh_proxies: true
                         faker:
                                 locale: fr_FR 

      when@test: *dev

**Comment by kbond** [comment]
Hey @BernardA!

I don't think you're on the latest version of Foundry, can you confirm?

The only other options for resetting the schema is using Doctrine migrations. Do you use these?

**Comment by BernardA** [comment]
Hi @kbond. Thanks for your prompt reply. 
This is my version 
    "name": "zenstruck/foundry",
            "version": "v1.21.0",

Yes I do use Doctrine migrations, but it is failing on the `doctrine:schema:create`.  So I was thinking about using your `reset_mode` on `database_resetter:`, though I am not sure that would resolve the issue.

**Comment by kbond** [comment]
1.23.0 added the config option - can you upgrade to that? If not, try setting the env variable `FOUNDRY_RESET_MODE=migrate` to enable (pre 1.23)

**Comment by BernardA** [comment]
I did upgrade to `1.24.1` and added the config below, but still getting error:

> An exception occurred while executing a query: SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  no schema has been selected to create in
  LINE 1: CREATE TABLE doctrine_migration_versions (version VARCHAR(19...


This is the config:

        when@dev: &dev
                zenstruck_foundry:
                     auto_refresh_proxies: true
                     faker:
                            locale: fr_FR 
                     database_resetter: 
                            orm:
                                  reset_mode: migrate

          when@test: *dev

So, it is still struggling with the schema.

**Comment by kbond** [comment]
So to confirm, in your dev env, running either of the following snippets:

```bash
bin/console doctrine:database:drop --if-exists
bin/console doctrine:database:create
bin/console doctrine:schema:create
```

```bash
bin/console doctrine:database:drop --if-exists
bin/console doctrine:database:create
bin/console doctrine:migrations:migrate
```

Do not work to create your schema correctly?

**Comment by BernardA** [comment]
I have no issues in `dev` , as the database setup includes the queries I mentioned above. 

The issue is specific to the `test` environment. 

From your queries above, dropping and creating the database work fine as well when adding  the suffix `--env=test`.

But neither `schema:create --env=test` nor `migrations:migrate --env=test` work, throwing the `invalid schema` error.

**Comment by nikophil** [comment]
Hello @BernardA 

if the migrations work well in test, couldn't you add the two queries you need inside a migration?

**Comment by kbond** [comment]
> as the database setup includes the queries I mentioned above.

Can you explain this? Do you have some kind of custom setup?

**Comment by BernardA** [comment]
@nikophil I just added a migration before all others with the queries in question.
Still getting :

> An exception occurred while executing a query: SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  no schema has been selected to create in
  LINE 1: CREATE TABLE doctrine_migration_versions (version VARCHAR(19...

**Comment by BernardA** [comment]
@kbond This is a `docker-compose` set up and the queries are  added to volumes on the database service ( queries are in the schema.sql file) and then executed as part on the database initialization within the container :

> volumes:
            - db-data:/var/lib/postgresql/data:rw
            - ./docker/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

**Comment by nikophil** [comment]
hi! I'm closing this stale issue. Don't hesitate to reopen it!
