### ISSUE TITLE
Change `Story::getState()` visibility to `protected`

### ISSUE THREAD

**Issue by aprat84** [zenstruck/foundry#384]
Since [this commit](https://github.com/zenstruck/foundry/commit/8332956ad7274a556b9069af76f6cf2f89cfc827), i get a ton of deprecated.

I corrected the external calls easily by changing `::load()->get()` to `::get()`.

Could the method `getState()` be changed from `private` to `protected`, so we can access items indexed by ID from within the same story?

I know I could use an array/collection to store them, but we found this practical specially when this items can be used in other stories.
~I could also use `self::get()`, but why this many function calls when I could access "my own" internal state directly.~
Can't use `self::get()`, it triggers the deprecation anyway...

```php
final class AbsenceStory extends Story
{
    public function build(): void
    {
        foreach ($items as $item) {
            $this->addState($item['#ref'], ItemFactory::createOne($item));
        }

        foreach ($otherItems as $otherItem) {
            OtherItemFactory::createOne([
                'item' => $this->getState($otherItem['#itemRef']),
                ...
            ]);
        }
    }
}
```

**Comment by kbond** [comment]
Sure, this makes sense.
