### ISSUE TITLE
ModelFactory "target class" attribute

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#394]
I think we should create a `Target` (better name?) attribute to be used by ModelFactory's. This would allow us to deprecate/remove (`ModelFactory::getClass()` and `ModelFactory::getEntityClass()`).

A model factory could look like the following:

```php
#[Target(User:class)]
class UserFactory extends ModelFactory
{
    public function getDefaults(): array
    {
        return [
            // ...
        ];
    }
}
```

**Comment by nikophil** [comment]
genuine question: what would be the benefit to deprecate `ModelFactory::getClass()`?

about the naming, WDYT of `#[AsFactory()]`, following Symfony trends

**Comment by kbond** [comment]
> what would be the benefit to deprecate ModelFactory::getClass()?

This is indeed a good point. ModelFactory's already _need_ to implement an interface - an attribute is just sort of added noise. I was thinking on how we could remove the need for both `ModelFactory::getClass()` (currently protected) and `ModelFactory::getEntityClass()`.

**Comment by kbond** [comment]
Closing for now. My _lightbulb_ idea doesn't seem so clever anymore 😆
