### ISSUE TITLE
Factory Maker: match directory/namespace structure

### ISSUE THREAD

**Issue by jmsche** [zenstruck/foundry#401]
Hi, it would be nice if the `make:factory` command could match the entity namespace/directory structure?

Eg. for an entity with the `App\Entity\Franchise\Shop` FQCN, it would create a factory in the `src/Factory/Franchise/Shop.php` file, in the `App\Factory\Franchise` namespace.

**Comment by nikophil** [comment]
Hi @jmsche 

this actually makes sense, let's do it!

**Comment by nikophil** [comment]
this is actually harder than it seems:

I'm actually wondering from where I should stop to read the original namespace... in your example I should strip `App\Entity` in favor of `App\Factory` (or `App\Test\Factory` if `--test` option is passed)

but what should we do if the entity class is something like `App\Domain\Shop\Model\Franchise\Shop`?

I'm wondering if the answer would not be to access doctrine's configuration. WDYT @kbond?

And if we're asked to create a factory for an object not managed by doctrine, we'd place the factory at the root of the `App\Factory` namespace, as we're doing now

EDIT: after some digging, I think I'll go with this solution

**Comment by nikophil** [comment]
Hi @jmsche 

I've finished the PR

would you play around to check if everything is OK for you?

**Comment by jmsche** [comment]
Seems to work fine for my current use case, thanks :)
