### ISSUE TITLE
Improve CI for Forks (Sync meta files)

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/foundry#405]
It would be great to improve the CI, to get green testresults in forks.
`Sync meta files` fails in lack of token

Example [Sync meta files](https://github.com/Chris53897/foundry/actions/runs/3978621994/jobs/6820511009#logs)

I am not sure if it is possible and how much work that would be.

**Comment by kbond** [comment]
I think I can skip if is a fork - I'll look into this

**Comment by kbond** [comment]
@Chris53897, do you mind testing your fork to ensure #417 fixes the problem?

**Comment by nikophil** [comment]
see here: https://github.com/zenstruck/foundry/pull/418
`sync meta files` [is skipped](https://github.com/nikophil/foundry/actions/runs/4077498560/jobs/7026594596)

**Comment by kbond** [comment]
Thanks!
