### ISSUE TITLE
Is it possible to truncate id auto_increment for each table?

### ISSUE THREAD

**Issue by dimabredun** [zenstruck/foundry#408]
Hey guys! First of, thanks for this great library, really useful and makes life easier!

When I'm seeding my database with factories, I want each table id count to start from 1. Is it possible to achieve with your library?

**Comment by nikophil** [comment]
Hi @dimabredun 

do you use this (great) bundle: https://github.com/dmaicher/doctrine-test-bundle ?

because it opens a transaction which is never committed, all your ids will start from 1 for each test (that, and you may have significant performance improvements in your tests with the bundle)

**Comment by kbond** [comment]
There isn't a way to do this with Foundry directly. I don't think the ORM provides a way either. You'd have to use raw SQL: https://stackoverflow.com/a/8923132

**Comment by dimabredun** [comment]
@nikophil thank you for advice! Looks good

**Comment by dimabredun** [comment]
@kbond got it, thanks! Closing the thread
