### ISSUE TITLE
Fatal error "Return value of Zenstruck\Foundry\RepositoryProxy::random() must be an instance of Zenstruck\Foundry\Proxy

### ISSUE THREAD

**Issue by anjeylink** [zenstruck/foundry#42]
I have a User entity and UserFactory.
I'm using `UserFactory::random()` in my fixtures and it fails randomly, might be on first call or last.

Error message is:
`Return value of Zenstruck\Foundry\RepositoryProxy::random() must be an instance of Zenstruck\Foundry\Proxy, instance of Proxies\__CG__\App\Entity\User  returned `.

I debug it a little bit and I can see that method `\Zenstruck\Foundry\RepositoryProxy::findAll` return array with objects where part of it is 
`App\Entity\User` and other part is `Proxies\__CG__\App\Entity\User`

Quick work around was modifying  `\Zenstruck\Foundry\RepositoryProxy::proxyResult` object check

```
if (\is_object($result)
            && (
                $this->getClassName() === \get_class($result)
                || is_subclass_of(get_class($result), $this->getClassName())
            )
        ) {
```

**Comment by kbond** [comment]
Good catch @anjeylink, thanks!

[This test](https://github.com/zenstruck/foundry/blob/60e6881cbf5b9fd6233ccb5a0cd897085fc5de40/tests/Functional/RepositoryProxyTest.php#L208) demonstrates the problem - you're solution was exactly what was needed to fix.

Tagged [v1.1.4](https://github.com/zenstruck/foundry/releases/tag/v1.1.4).
