### ISSUE TITLE
Problem with `Factory::findOrCreate()` and `Embeddable`

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#428]
There is actually no way to use embeddables with `Factory::findOrCreate()`:
```php
#[ORM\Embeddable]
final class Address
{
    #[ORM\Column()]
    public string $value;
}

#[ORM\Entity]
final class Contact
{
    #[ORM\Embedded(Address::class)]
    public Address $address;
}

// 💥 Error "Unrecognized field: address" when doctrine tries to get the contact:
// for doctrine, this field is called "address.value" 
ContactFactory::findOrCreate(['address' => 'some address']); 

// 💥 "Class "Contact" does not have property "address.value"" when Foundry tries to create the address
ContactFactory::findOrCreate(['address.value' => 'some address']); 
```
Actually, I don't think we will be able to fix this :thinking:

**Comment by KDederichs** [comment]
Ah, bummer cause I came here cause I ran into EXACTLY the same issue :)

One solution could be that you require the Address to be initialized (via constructor) and then if you find an Embedded in create/find it'll call the getter/setter on that maybe?

Like `address.value` is mapped to `address->getValue()` or `address->setValue()` internally?

**Comment by nikophil** [comment]
> Ah, bummer cause I came here cause I ran into EXACTLY the same issue :)

this may give some more motivation to fix this!

I'm wondering if we couldn't use it like this:
```php
ContactFactory::findOrCreate(['address' => new Address('some address')]); 
```
this way Foundry is happy when it tries to create the address, and we could transform all embeddable objects into DQL criteria understandable by doctrine. 

Actually that won't be that complex to fix.

Any thoughts @kbond?

**Comment by kbond** [comment]
Yes that makes sense, since it's an embeddable, I think we could also accept:

```php
ContactFactory::findOrCreate(['address' => AddressFactory::new('postalCode' => '90210')]);
```
