### ISSUE TITLE
Global State with unique entity constraint

### ISSUE THREAD

**Issue by mvhirsch** [zenstruck/foundry#433]
Hi there,

Being on a symfony 6.2 & doctrine project. Using `zenstruck/foundry` v1.29.0

I'm using an entity called `Instance` (which is basically a reference to an external HTTP service, scheme, url, and so on). These instances are unique (database constraint on `Instance::$name`) and referenced by many other doctrine entities.

I've implemented a global state `InstancesStory`, basically containing this:

```yaml
# same config used in dev & test

zenstruck_foundry:
    global_state:
        - App\Fixtures\Story\InstancesStory
```

```php
final class InstancesStory extends Story
{
    public function build(): void
    {
        $instances = [
            'rema' => ['name' => 'rema', 'url' => 'https://example.com/service1', ...],
            'foobar' => ['name' => 'foobar' 'url' => 'https://example.com/service2', ...],     
        ];

        foreach ($instances as $instance => $attributes) {
            $this->addState($instance, InstanceFactory::new($attributes), 'all');
        }
    }
}
```

One of my entities (using `Instance`) is called `Fieldgroup`. It's simply factory looks like this:

```php
final class FieldgroupFactory extends ModelFactory
{
    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#model-factories
     */
    protected function getDefaults(): array
    {
        return [
            'createdTimestamp' => self::faker()->dateTime(),
            'instance' => InstancesStory::getRandom('all'),
            'name' => self::faker()->word(),
            'oid' => self::faker()->numberBetween(9999),
        ];
    }

    protected static function getClass(): string
    {
        return Fieldgroup::class;
    }
}
```

Since `instance` must be one of the created in global state, I'm using `InstancesStory::getRandom('all')`.
But my (`KernelTest`) test fails everytime I'm trying to create any `Fieldgroup`:

```php


final class FieldgroupTest extends IntegrationTestCase // extends symfony's KernelTestCase
{
    /**
     * @test
     */
    public function canBeSerializedWithMetaReadGroupSerializationGroup(): void
    {
        $fieldgroup = FieldgroupFactory::new()->withoutPersisting()->create(['id' => 1])->object();

        // ...
    }
}
```

Resulting in an error:
```
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "uniq_b8dfe61a5e237e06"
DETAIL:  Key (name)=(rema) already exists.

/path/to/project/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121
/path/to/project/vendor/doctrine/dbal/src/Statement.php:190
/path/to/project/vendor/doctrine/dbal/src/Statement.php:249
/path/to/project/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:278
/path/to/project/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1145
/path/to/project/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:431
/path/to/project/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
/path/to/project/vendor/zenstruck/foundry/src/Proxy.php:147
/path/to/project/vendor/zenstruck/foundry/src/Factory.php:136
/path/to/project/vendor/zenstruck/foundry/src/Story.php:176
/path/to/project/vendor/zenstruck/foundry/src/Story.php:152
/path/to/project/src/Fixtures/Story/InstancesStory.php:89
/path/to/project/vendor/zenstruck/foundry/src/StoryManager.php:51
/path/to/project/vendor/zenstruck/foundry/src/Story.php:50
/path/to/project/vendor/zenstruck/foundry/src/Story.php:60
/path/to/project/vendor/zenstruck/foundry/src/Story.php:100
/path/to/project/vendor/zenstruck/foundry/src/Story.php:82
/path/to/project/vendor/zenstruck/foundry/src/Story.php:68
/path/to/project/src/Fixtures/Factory/FieldgroupFactory.php:23
/path/to/project/vendor/zenstruck/foundry/src/ModelFactory.php:60
/path/to/project/vendor/zenstruck/foundry/src/Factory.php:323
/path/to/project/vendor/zenstruck/foundry/src/Factory.php:95
/path/to/project/vendor/zenstruck/foundry/src/Factory.php:95
/path/to/project/tests/Integration/Entity/FieldgroupTest.php:21
```

I wanted to create that entity `Fieldgroup` withoutPersisting(), because I don't need it persisted (skip database flushing and instead working with the object right away in another context -> this case serialization). Anyway, I even tried to removed it, using it like this (because I thought, maybe there is a problem by mixing persisted and non-persisted entries): 

```php
$fieldgroup = FieldgroupFactory::createOne()->object();
```

No luck, same error. 

The [documentation states](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#story-state):

> Story state is cleared after each test (unless it is a Global State Story).

Did I misunderstood something? Am I using it wrong? Or is it a bug?

**Comment by nikophil** [comment]
Hello @mvhirsch 

thanks for this detailed issue.

When you run your test, is the db empty? do you use one of `ResetDatabase` trait or https://github.com/dmaicher/doctrine-test-bundle ?

**Comment by mvhirsch** [comment]
> When you run your test, is the db empty? do you use one of `ResetDatabase` trait or https://github.com/dmaicher/doctrine-test-bundle ?

Yes, `ResetDatabase` is used in `IntegrationTestCase` which my TestCase extends (forgot that one to post above :sweat_smile: ). And yes, DamaDoctrineTestBundle is enabled, too.

I drop the database and create the schema (without data) by using migrations (also configured in _zenstruck.yaml_) everytime I run the tests.

**Comment by nikophil** [comment]
OK I see the problem, I can reproduce the bug on my computer, but it will need some digging to fix.

As a quick fix, I can suggest that you only use `DamaDoctrineTestBundle` and drop usage of `ResetDatabase` trait and everything should go well.
