### ISSUE TITLE
findOrCreate doesn't allow entity in criteria, only embeddable object

### ISSUE THREAD

**Issue by nicolasne** [zenstruck/foundry#437]
The following PR https://github.com/zenstruck/foundry/pull/432 allow embeddable objects in criteria, but introduce a regression when using entities that aren't embeddable.

This exception is raised `InvalidArgumentException: Only embeddable objects can be passed as attributes for "findOrCreate()" method.` but the previous behavior allow to use entity in criteria.

For example:

```php
#[ORM\Entity]
class User 
{
   #[ORM\OneToOne(targetEntity: Device::class)]
    private Device $device;
}


// Foundy code that works before
$device = DeviceFactory::createOne();
UserFactory::findOrCreate(['device' => $device]); // now InvalidArgumentException is raised

// workaround that work with the merged PR
$device = DeviceFactory::createOne();
$user = UserFactory::findBy(['device' => $device]);

if(\count($user) === 0){
  UserFactor::createOne(['device' => $device]);
}
```

**Comment by nikophil** [comment]
hi @nicolasne 

indeed, you're right, sorry for that.
problem is in these lines: https://github.com/zenstruck/foundry/blob/1.x/src/RepositoryProxy.php#L331-L345

**Comment by nicolasne** [comment]
@nikophil I can provide a PR to fix it or you want to fix the regression ?

**Comment by nikophil** [comment]
I'd be glad if you can do it... I won't have time to do it before few days, but still can review

thanks :)

**Comment by kbond** [comment]
Tagged 1.30.1 with the fix.
