### ISSUE TITLE
findOrCreate doesn't allow `\DateTime`or `\DateTimeImmutable`

### ISSUE THREAD

**Issue by sad270** [zenstruck/foundry#439]
The following PR https://github.com/zenstruck/foundry/pull/432 allow embeddable objects in criteria, but introduce a regression when using `\DateTime` or `\DateTimeImmutable` property.

This exception is raised `InvalidArgumentException: Only managed objects can be passed as attributes for "findOrCreate()" method.` and `Doctrine\Persistence\Mapping\MappingException: The class 'DateTimeImmutable' was not found in the chain configured namespaces App\Entity`, but the previous behavior allow to use type object in criteria.

```php
#[ORM\Entity]
class User 
{
   #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;
}


// Foundy code that works before
UserFactory::findOrCreate([
    'createdAt' => \DateTimeImmutable::createFromFormat('Y-m-d H:i:s', '2012-10-17 00:00:00'),
]); // now InvalidArgumentException is raised

// workaround that work with the merged PR
$createdAt =  \DateTimeImmutable::createFromFormat('Y-m-d H:i:s', '2012-10-17 00:00:00');
$user = UserFactory::findBy(['createdAt' => $createdAt]);

if(\count($user) === 0){
  UserFactor::createOne(['createdAt' => $createdAt]);
}
```

I didn't check but i think it will be the same for custom DBAL type having object value.

It's related with https://github.com/zenstruck/foundry/issues/437

**Comment by nikophil** [comment]
hello @sad270 

hum ok, it's been 2 issues caused by this feature...
I think I'll get rid off this exception: https://github.com/zenstruck/foundry/blob/1.x/src/RepositoryProxy.php#L336

**Comment by sad270** [comment]
And I think the Exception messages are not good. It's the "find" method (of `RepositoryProxy`), not the "findOrCreate" method (of `ModelFactory`).
