### ISSUE TITLE
Setting an auto increment private $id field

### ISSUE THREAD

**Issue by geoff-maddock** [zenstruck/foundry#44]
I'm trying to set the private $id of an entity when I create it it a factory.

The $id is private and auto generates:

```
class Facility implements ActivatableInterface, CommonEntityInterface, OrderableInterface
{
    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $description = '';

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private ?int $id = null;
...
```

I have the always force properties setting to true:
```
     # Whether or not to skip setters and force set object properties (public/private/protected) directly.
    always_force_properties: true
```

And in my GlobalStory I have some code to create the entities as such:
```
        // add facilities
        $facilityNames = [
            263 => 'Pittsburgh - 810 Parish',
            267 => 'Cleveland (151)',
        ];

        foreach ($facilityNames as $id => $facilityName) {
            $facility = FacilityFactory::new()->create([
                'force:id' => $id,
                'name' => $facilityName,
            ]);
        }
```

When I run a test, it seems like the GlobalState gets initialized, but when I check the database, the IDs are not being set correctly.
```
mysql> select * from facility;
+------------+------------+-------------+-----------+------------+-------------------------+-------+---------------------+---------------------+
| id         | region_id  | description | is_active | is_default | name                    | order | created_at          | updated_at          |
+------------+------------+-------------+-----------+------------+-------------------------+-------+---------------------+---------------------+
|  181983240 | 1174584734 | quibusdam   |         1 |          0 | Cleveland (151)         |    37 | 2020-10-07 18:19:06 | 2020-10-07 18:19:06 |
| 1055737034 |  164350616 | nihil       |         1 |          0 | Pittsburgh - 810 Parish |    52 | 2020-10-07 18:19:06 | 2020-10-07 18:19:06 |
```

Is there something else I'm missing?

**Comment by kbond** [comment]
I can double check tomorrow but I don't think Doctrine allows setting the id when you have `@ORM\GeneratedValue(strategy="AUTO")`.

To test, can you create and persist an entity like normal, setting it's id to an explicit value (without using foundry)?

See https://stackoverflow.com/questions/5301285/explicitly-set-id-with-doctrine-when-using-auto-strategy for possible solutions. [This package](https://github.com/tseho/doctrine-assigned-identity) looks like it could help?

**Comment by geoff-maddock** [comment]
I was able to get it to work.  I had assumed that always force properties would have worked, but I've run into needing to do this to override the generated id before.  I had to inject the entity manager and set the metadata for the class as such:

```
        $entityManager = $this->managerRegistry->getManagerForClass(Facility::class);
        $metadata = $entityManager->getClassMetaData(Facility::class);
        $metadata->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        foreach ($facilityNames as $id => $facilityName) {
            $facility = FacilityFactory::new()->create([
                'id' => $id,
                'name' => $facilityName,
            ]);
        }
```

One point of interest is that I couldn't use 'force:id' even with this setting changed it would set to some other id value.  Removing the force though as above worked.

**Comment by kbond** [comment]
That's strange about the `force:id` - I was going to say, if you have `always_force_properties: true`, the `force:id` was redundant (or it should be).

**Comment by kbond** [comment]
Actually, do you have `allow_extra_attributes: true` as well?

**Comment by geoff-maddock** [comment]
I don't have ```allow_extra_attributes```  set to true (it's null)

**Comment by kbond** [comment]
Hmm, that deepens the mystery. I was wrong, the `force:id` isn't redundant when `always_force_properties: true`. It would try and set a property called `$object->force:id` which of course doesn't exist so it should throw an error (unless `allow_extra_attributes: true`)
