### ISSUE TITLE
Class was not found in the chain confnigured namespaces since 1.30.0

### ISSUE THREAD

**Issue by ndench** [zenstruck/foundry#443]
Loving Foundry, we're rolling it out across our very heavily testing Symfony 5.4 codebase with plans to completely replace Alice fixtures. 

I ran into an issue when upgrading from 1.29.0 to 1.30.3.

PR #423 appears to have broken Foundry when creating objects which are not Doctrine entities. We're using Foundry to create both Entities and DTO's in the same test and now we're receiving the following exception:

```
Doctrine\Persistence\Mapping\MappingException : The class 'App\Integration\FooApiResponse' was not found in the chain configured namespaces ...
vendor/doctrine/persistence/src/Persistence/Mapping/MappingException.php:26
vendor/doctrine/persistence/src/Persistence/Mapping/Driver/MappingDriverChain.php:89
vendor/doctrine/doctrine-bundle/Mapping/MappingDriver.php:42
vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:132
vendor/doctrine/doctrine-bundle/Mapping/ClassMetadataFactory.php:18
vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:343
vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:207
vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:318
vendor/zenstruck/foundry/src/Factory.php:375
vendor/zenstruck/foundry/src/Factory.php:111
src/Factories/VendorFactory.php:101
tests/Functional/Api/VendorUpdaterTest.php:60
 ```

Stepping in with Xdebug I can identify the simplification in `Factory::normalizeAttribute()` which fetches the object manager for class. It appears that Doctrine is returning the default object manager when the given class is not a configured entity, and then calling `->getClassMetadata()` for a non-entity throws an exception. See: https://github.com/zenstruck/foundry/pull/423/files#diff-f1158fbec0bb446d87dbd5346fba683c58ccec1a98b1787511ec7786585e8c31R376

Whereas previously, `$this->ownedRelationshipField($name, $value);` returned `null` on line 360 and `$this->isPersisting()` returned `false` on line 369.

I think the `$objectManager instanceof EntityManagerInterface` check on line 376 was intended to catch this. I'm unsure if there's a better way to ask Doctrine if a gives class is a configured entity.

**Comment by nikophil** [comment]
hello @ndench 

indeed, if `$objectManager = self::configuration()->objectManagerFor($this->class);` returns the default manager even if `$this-class` is not managed, that's a problem... maybe we should catch the error in line `$objectManager->getClassMetadata($value->class)`?

what's surprising is that we also test creating "not entity" objects in the CI, and don't have this error :thinking: 

would you be able to provide a reproducer?

> I think the `$objectManager instanceof EntityManagerInterface` check on line 376 was intended to catch this. I'm unsure if there's a better way to ask Doctrine if a gives class is a configured entity.

actually this is also here to filter out ODM documents

**Comment by nikophil** [comment]
ok I found the problem: it was with nested "non related to doctrine" factories

**Comment by ndench** [comment]
Ah, that makes sense. I didn't realise it was due to the nesting. Thanks for tracking it down so quickly @nikophil!
