### ISSUE TITLE
Problem with many() function in Doctrine Relationships

### ISSUE THREAD

**Issue by StephaneBullier** [zenstruck/foundry#45]
I use this code in AppFixtures.php
`PostFactory::new()->many(6)->create(['comments' => CommentFactory::new()->many(0, 10)]);`

When I load fixtures with symfony console doctrine:fixtures:load command I have an error
`Attempted to call an undefined method named "many" of class "App\Factory\PostFactory".`

How it's possible to generate relationship between entities with foundry ?

**Comment by kbond** [comment]
many() was just added a few hours ago in version 1.2 - do you have this version of Foundry installed?

**Comment by StephaneBullier** [comment]
Thank for your reply. No I had the version 1.1
I made a composer update and foundry is now in 1.2 version.
It's work fine.
Thank you for your super bundle.
