### ISSUE TITLE
Initialize objects

### ISSUE THREAD

**Issue by benblub** [zenstruck/foundry#453]
I have a Question to the initialize function. Currently i have to deal with constructors in the entities.

Factory
```php
    protected function initialize(): self
    {
        return $this
            ->instantiateWith(function (array $attributes) {
                // call the constructor with your required arguments
                return new Portal($attributes['id']); // custom instantiation for this factory
            })
        ;
    }
```

calling code
```php
        PortalFactory::new([
            'id' => UrnHelper::uuid(),
        ])->create();
```

The problem i get now is that the defaults are not set anymore or set via method call?
```php
        PortalFactory::new([
            'id' => UrnHelper::uuid(),
        ])
    ->title('some title')
    ->create();
```

title is ignored :/

**Comment by kbond** [comment]
Yes, this is a limitation currently, when you use a custom instantiator, the standard _setMethod_ hydration doesn't happen. This should be solved by https://github.com/zenstruck/foundry/pull/395. Technically, it's also a feature as when you take over instantiation, we assume you don't want the method hydration to take place.

Is your above example of a custom instantiator more complex than you show above? You shouldn't need a custom instantiator for the code above.

**Comment by benblub** [comment]
ohh ok good to know. Should be simple as shown above. So `beforeInstantiate` should work to pass arguments to the constructor?

**Comment by kbond** [comment]
> So beforeInstantiate should work to pass arguments to the constructor?

Yes, but:

```php
PortalFactory::new([
    'id' => UrnHelper::uuid(),
    'title' => 'some title',
])->create();
```

Should work out of the box.

By default, the constructor is called with arguments matching your attributes (in your case, `id`), then, the remaining attributes (ones not _used up_ by the constructor) are set using setters.

**Comment by benblub** [comment]
Also 

One problem .. (field or relationship not found) -> resolved by rename to `$createdBy`
```php
    public function __construct(User $user)
    {
        $this->createdBy = $user;
    }
```

Create some defaults if no constructor arguments passed.
```php
        return $this
            ->beforeInstantiate(function (array $attributes) {

                if (false === array_key_exists('id', $attributes)) {
                    $attributes['id'] = new Portal(UrnHelper::news());
                }

                return $attributes;
            })
        ;
```

**Comment by kbond** [comment]
Can I get a bit more context on this problem?

Could be related to #454

**Comment by benblub** [comment]
Sure. 

EntityFoo.php

error `field or relation $user not found in class EntityFoo` 
```php
    public function __construct(User $user, Portal $portal)
    {
        // .. other fields
        $this->createdBy = $user
    }
```

working
```php
    public function __construct(User $createdBy, Portal $portal)
    {
        // .. other fields
        $this->createdBy = $createdBy
    }
```

**Comment by nikophil** [comment]
Hi @benblub 

is that a regression, or this has never worked? I bet is has never worked, but not sure... 

You still can use `->instantiateWith((new Instantiator())->withoutConstructor())` or `->instantiateWith((new Instantiator())->alwaysForceProperties())` and use directly the name of the property, this will prevent the need to change the name of the parameter in the constructor's name (you can [configure these globally](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration))

By the way, having a constructor param's name different from the property name might break some components such as property info, automapper, ...

**Comment by kbond** [comment]
> error field or relation $user not found in class EntityFoo

The first example fails when using:

```php
EntityFooFactory::createOne(['user' => ..., 'portal' => ...]);
```
?

**Comment by benblub** [comment]
Hey @kbond

Yes exactly.

Hey @nikophil 
Thanks for the explanation. Yeah a good reason to refactoring the class 👍

**Comment by nikophil** [comment]
@benblub could this issue be closed, or is there still some things to fix?

**Comment by kbond** [comment]
I think @benblub's second issue is the same as #454.

**Comment by benblub** [comment]
yes can be closed, busy .. late response
