### ISSUE TITLE
Since 1.30.0 getDefaults array key must be an Entity field

### ISSUE THREAD

**Issue by mpiot** [zenstruck/foundry#454]
Hi everyone,
Since the 1.30.0, if we define in getDefaults a key that not refer to an Entity property, an error is trigger.

In my case, an entity as a `$documents` property, but we use:
 - `addInitialDocument`
 - `getInitialDocuments`
 - `addAdditionalDocument`
 - `getAdditionalDocuments`

These one set a Discriminator (adder) or use filter (getter), this one work well in Factory:
```php
    protected function getDefaults(): array
    {
        return [
            //...
            'additionalDocuments' => DocumentFactory::new()->asAdditional()->many(1, 3),
            //...
        ];
    }
```

But since the 1.3.0, this one trigger an error:

> In Factory.php line 447:
>                                                                                                           
> Field App\Entity\ChangeRequest::$additionalDocuments does not exist or is not a relationship field.

**Comment by kbond** [comment]
I believe this is the same issue that @OskarStark had in one of his apps.

We ultimately came to the conclusion that using foundry this way was an undocumented fluke but I'm willing to re-evaluate.

Foundry was only intended to work with named object properties. The fluke was related to hydrating properties using `symfony/property-access` I believe.

@nikophil, any thoughts here?

**Comment by nikophil** [comment]
Hi!

yes, we can try to make this fluke a feature! I don't think it will be very complex to fix the regression, and let's document it this time :)

but maybe this opens the door to new subtle problems, like: there will be many ways to access to the same property. ie: which one should we take here ?
```php
protected function getDefaults() {
    return [
    	'documents' => DocumentFactory::new()->many(1, 3),
    	'addInitialDocument' => DocumentFactory::new()->many(1, 3),
    	'addAdditionalDocument' => DocumentFactory::new()->many(1, 3),
    	'setInitialDocument' => DocumentFactory::new()->many(1, 3),
    	'setAdditionalDocument' => DocumentFactory::new()->many(1, 3),
    ];
}
```
because all of these refers to the same property

**Comment by mpiot** [comment]
It initially work because of using the `symfony/property-access` that guess the way to access the property. 

Since the 1.30.0 in `Factory.php` file there is a check that throw an error if there is no relation:
https://github.com/zenstruck/foundry/blob/912f134c97aa3a6c5b530d829425f1b5a9d85537/src/Factory.php#L452..L454

**Comment by kbond** [comment]
> because all of these refers to the same property

Yeah, I think the fix would only work for attributes that would work with property access.

For instance, addInitialDocument would only work if your entity has an addAddInitalDocument method.

**Comment by kbond** [comment]
@nikophil, what are the side effects of removing that relationship check? Think it's the cause of several of these issues.

**Comment by nikophil** [comment]
I have to analyze this... I'm pretty sure it could be skipped. 

I'm too used to do "defensive programming" and throw fast and often, but this does not fits well for public libraries :shrug:

**Comment by nikophil** [comment]
hi @mpiot 

the PR has been released, could you confirm the problem is fixed?

**Comment by mpiot** [comment]
@nikophil Yes it's okay, just updated to 1.33 and it works :)
Thanks again :D
