### ISSUE TITLE
PostgreSQL and ResetDatabase trait

### ISSUE THREAD

**Issue by benblub** [zenstruck/foundry#455]
Since im working with a new project which is working with a postgreSQL Database i have issues with the ResetDatabase trait. This is maybe a problem which needs to be fixed on DB level or on the depending libary from `doctrine:database:drop` in AbstractSchemaResetter.php

The error
```
RuntimeException: Error running "doctrine:database:drop": Could not drop database "test" for connection named default                    
   ├ An exception occurred while executing a query: SQLSTATE[55006]: Object in use: 7 ERROR:  database "test" is being accessed by other users
   ├ DETAIL:  There is 1 other session using the database.
``` 

This happens in difference cases for me. 
1. When i run the tests while i have open and connected my DB Tool.
2. More worst: The project is using https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/database.md and in some tests it uses the https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseTools/ORMDatabaseTool.php This leads to the same error. Im unsure why its a different user. Both "resetter" use the entityManager default connection (needs some more debugging)

Looking for a solution :)

1. Dunno something like this has to be added to doctrine/dbal?
https://www.postgresql.org/docs/current/sql-dropdatabase.html
https://stackoverflow.com/questions/55747282/dropping-db-when-there-are-active-connections
Postgres 13 or higher
```sql
DROP DATABASE database_name WITH (FORCE);
```

**Comment by benblub** [comment]
related 
https://github.com/zenstruck/foundry/issues/72
https://github.com/doctrine/orm/issues/10639

**Comment by nikophil** [comment]
Hi @benblub 

yeah I have this problem as well...
I've fixed it in different ways:
- first I don't use in my projects `ResetDatabase` trait, but I use the excellent library https://github.com/dmaicher/doctrine-test-bundle which also improves the speed of my tests
- for all other moments I need to drop the db, I have a make target (this could be a shell script as well) which looks like this:
```make
db-recreate:
	bin/console doctrine:database:create --no-interaction --if-not-exists --quiet # prevents the next line to create an error
	bin/console doctrine:query:sql "SELECT pid, pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = current_database() AND pid <> pg_backend_pid();" --quiet
	bin/console doctrine:database:drop --if-exists --force
	bin/console doctrine:database:create --no-interaction
```
the second line kills all other connections to the db. Not sure we could make it to Foundry, though

**Comment by kbond** [comment]
> Not sure we could make it to Foundry, though

Can we make that sql call when postgres is detected?

**Comment by nikophil** [comment]
I think it is possible, yes!

**Comment by benblub** [comment]
finally i did this:

1. In my bootstrap.php i kill all active connections on posgreSQL before running the tests 🎉 
2. I didn't use ResetDatabase and go with DAMA

But it would be nice if we can add this to the ResetDatabase trait when posgreSQL is detected. Maybe i will give it a try and provide a PR 👍 

```php
$kernel = new \App\Kernel('test', true);
$kernel->boot();

$application = new \Symfony\Bundle\FrameworkBundle\Console\Application($kernel);
$application->setAutoExit(false);

$application->run(new \Symfony\Component\Console\Input\ArrayInput([
    'command' => 'doctrine:query:sql',
    'sql' => "SELECT pid, pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = current_database() AND pid <> pg_backend_pid();",
]));

$application->run(new \Symfony\Component\Console\Input\ArrayInput([
    'command' => 'doctrine:database:drop',
    '--if-exists' => '1',
    '--force' => '1',
]));

$application->run(new \Symfony\Component\Console\Input\ArrayInput([
    'command' => 'doctrine:database:create',
    '--no-interaction' => true,
    '--if-not-exists' => true,
]));

$application->run(new \Symfony\Component\Console\Input\ArrayInput([
    'command' => 'doctrine:schema:create',
    '--no-interaction' => true,
]));


$kernel->shutdown();
```

and btw: thanks for help 👍

**Comment by kbond** [comment]
Yep, hopefully we can get that needed sql statement in `ResetDatabase`. We already make a consideration for sqlite so shouldn't be hard.

PostgreSQL is the default recommended by Symfony so we should ensure it works nicely with foundry.

**Comment by nikophil** [comment]
Hi @benblub 
could you confirm the problem is fixed with the release of today's version?
