### ISSUE TITLE
ResetDatabase doesn't work with sqlite DB

### ISSUE THREAD

**Issue by anjeylink** [zenstruck/foundry#46]
Error occurs when run tests using `ResetDatabase` trait together with **sqlite** 

```
Error running "doctrine:database:drop": 
In DBALException.php line 39:
Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform. 
```

Looks like it's dbal issue. 

In `\Zenstruck\Foundry\Test\DatabaseResetter::runCommand` I added check for sqllite, but I'm not sure if bundle should be responsible for checking this though.

```
if (isset($parameters['--if-exists'])
    && $application->getKernel()->getContainer()->get('doctrine')->getConnection()->getDatabasePlatform()->getName() === 'sqlite'
) {
    unset($parameters['--if-exists']);
}
```

**Comment by anjeylink** [comment]
https://github.com/doctrine/dbal/pull/2402

**Comment by kbond** [comment]
Thanks @anjeylink - I'll add this check and look into running the test suite against sqlite as well to see if there are any other issues.

**Comment by kbond** [comment]
@anjeylink, I added the logic to fix but discovered an edge case where the test suite fails when using the FoundryBundle and DAMADoctrineTestBundle together (#49). I need to investigate further.

If you aren't using DAMADoctrineTestBundle, sqlite should work as expected now.

**Comment by anjeylink** [comment]
@kbond thx !

**Comment by anjeylink** [comment]
@kbond will be there a release for this fix soon? 
by the way I'm using DAMADoctrineTestBundle and working fine.

**Comment by kbond** [comment]
Thanks for reminding me: [v1.2.1](https://github.com/zenstruck/foundry/releases/tag/v1.2.1)
