### ISSUE TITLE
Support for UUIDs (e.g. ULIDs) in Zenstruck Foundry

### ISSUE THREAD

**Issue by MichaelBrauner** [zenstruck/foundry#460]
Hello! I've been using Zenstruck Foundry in my project and I encountered an issue when working with UUIDs (specifically ULIDs) instead of auto-incremental integer IDs.

Here's my current entity's ID configuration:

```php
#[ORM\Id]
#[ORM\Column(type: UlidType::NAME, unique: true)]
#[ORM\GeneratedValue(strategy: 'CUSTOM')]
#[ORM\CustomIdGenerator(class: 'doctrine.ulid_generator')]
private $id;

public function getId(): ?Ulid
{
    return $this->id;
}
```

[Like described here](https://symfony.com/doc/current/components/uid.html#storing-ulids-in-databases)

However, Zenstruck Foundry seems to assume that the ID is an auto-incremental integer. This can be seen in the comments in the factory:

```php
* @method static User|Proxy first(string $sortedField = 'id')
* @method static User|Proxy last(string $sortedField = 'id')
```

This causes an issue when using the factory in my Behat tests, as it generates an error related to the invalid input syntax for the type integer.

I would like to kindly ask for suggestions on how to make the repository compatible with UUIDs, or if there's a way to configure the factory to work with ULIDs in its current state.

Thank you for your help and for this great library!

**Comment by kbond** [comment]
Hey Michael,

I'm not too familiar with UUID/ULID's. What exactly is the error you're seeing and what foundry method is causing it?

> However, Zenstruck Foundry seems to assume that the ID is an auto-incremental integer. This can be seen in the comments in the factory:

This is true but I'm not seeing how exactly it's a problem.

**Comment by MichaelBrauner** [comment]
Hey Kevin, 

The problem is that in my case `id` is not an integer. 
It's some kind of string (an ULID). 

Here is my stacktrace:
 
 ```shell
     PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "01880188-6c6c-476a-14ae-b9c80c864d5e"
      CONTEXT:  unnamed portal parameter $1 = '...' in vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121
      Stack trace:
      #0 vendor/doctrine/dbal/src/Driver/PDO/Statement.php(121): PDOStatement->execute()
      #1 vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php(69): Doctrine\DBAL\Driver\PDO\Statement->execute()
      #2 vendor/doctrine/dbal/src/Logging/Statement.php(98): Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
      #3 vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php(69): Doctrine\DBAL\Logging\Statement->execute()
      #4 vendor/symfony/doctrine-bridge/Middleware/Debug/Statement.php(68): Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute()
      #5 vendor/doctrine/dbal/src/Statement.php(190): Symfony\Bridge\Doctrine\Middleware\Debug\Statement->execute()
      #6 vendor/doctrine/dbal/src/Statement.php(249): Doctrine\DBAL\Statement->execute()
      #7 vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(280): Doctrine\DBAL\Statement->executeStatement()
      #8 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1144): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
      #9 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\ORM\UnitOfWork->executeInserts()
      #10 vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403): Doctrine\ORM\UnitOfWork->commit()
      #11 vendor/zenstruck/foundry/src/Proxy.php(147): Doctrine\ORM\EntityManager->flush()
      #12 vendor/zenstruck/foundry/src/Factory.php(151): Zenstruck\Foundry\Proxy->save()
      #13 vendor/zenstruck/foundry/src/ModelFactory.php(84): Zenstruck\Foundry\Factory->create()
      #14 tests/Behat/Context/User/UserContext.php(39): Zenstruck\Foundry\ModelFactory::createOne()
```

This would work only with ULID not with UUID, because only first is sortable. 
```php
* @method static User|Proxy first(string $sortedField = 'id')
* @method static User|Proxy last(string $sortedField = 'id')
```

To solve this for me, I will go back to classic incremental id's and create an additional field with a UUID.

That should work for me. But of course it would be cool if Foundry would offer a solution for a pure UID approach one day.

**Comment by kbond** [comment]
Still not seeing the issue - foundry doesn't enforce (or set) an integer id if not told to do so with attributes.

The issue is with the _save_, does it persist without error using _standard_ doctrine?

```php
$user = new User();
$em->persist($user);
$em->flush();
```

**Comment by nikophil** [comment]
Hello

I'm using foundry with entities which only have uuids as ids and it works like a charm.
The errors looks like the database field is an integer, but a ulid is being passed, resulting in a sql error...

> This would work only with ULID not with UUID, because only first is sortable.

I think uuid v1, v6 and v7 are also sortable

**Comment by nikophil** [comment]
Hello

I'm using foundry with entities which only have uuids as ids and it works like a charm. 

> PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "01880188-6c6c-476a-14ae-b9c80c864d5e"

This error looks like the database field is an integer, but a ulid is being passed, resulting in a sql error...

> This would work only with ULID not with UUID, because only first is sortable.

I think uuid v1, v6 and v7 are also sortable

**Comment by MichaelBrauner** [comment]
> 



> Still not seeing the issue - foundry doesn't enforce (or set) an integer id if not told to do so with attributes.
> 
> The issue is with the _save_, does it persist without error using _standard_ doctrine?
> 
> ```
> $user = new User();
> $em->persist($user);
> $em->flush();
> ```

Yes. My app works fine. I can create a User via my custom Command and/or via Registration Form etc. 

Just the tests suite crashes.

**Comment by MichaelBrauner** [comment]
Hello Nicolas ;) 

> I'm using foundry with entities which only have uuids as ids and it works like a charm.

Cool. How did you implement it? Do you use the symfony/uid component and the doctrine-bridge UlidType?

> > PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "01880188-6c6c-476a-14ae-b9c80c864d5e"
> 
> This error looks like the database field is an integer, but a ulid is being passed, resulting in a sql error...

It might be, but my app works fine. I don't think it's a misconfiguration.

> I think uuid v1, v6 and v7 are also sortable

Oh, I am not an expert for UUIDs, but this might also be true. Nevertheless, it does not make it easier when some UUIDs are sortable, and some are not.

To my knowledge, UUIDs are randomly generated, and ULIDs are sortable because they are generated based on the current millisecond.

So, if you guys are interested - I can create a reproducer app.

**Comment by kbond** [comment]
> So, if you guys are interested - I can create a reproducer app.

If you could, that would help a bunch I think.

**Comment by MichaelBrauner** [comment]
> > So, if you guys are interested - I can create a reproducer app.
> 
> If you could, that would help a bunch I think.

Of course I can do that. 
Should be easy to reproduce, or sometimes the problem solves itself when creating a reproducer ;) 

At the latest on the weekend you have something to play around with.

**Comment by nikophil** [comment]
I'm using them like this:
```php
     #[ORM\Id] 
     #[ORM\Column(type: 'uuid')] 
     private Uuid $id;
```
And the property is initialized in the constructor: `$this->id = Uuid::v7();`

**Comment by MichaelBrauner** [comment]
Hello @kbond and @nikophil,

I want to sincerely thank both of you for the time and effort you've put into understanding and addressing my concern. Your willingness to help and the dedication you've shown is truly appreciated.

As it turns out, it seems the issue was on my end. After creating a reproducer app, I've found that everything works perfectly fine with ULIDs, contrary to what I initially experienced in my project. It appears I might have reverted my initial attempt at using ULIDs too early and missed something in the process.

I'm truly sorry for any confusion or inconvenience caused by this. This issue can be considered resolved and I appreciate your understanding and patience.

Zenstruck Foundry is a wonderful library and I'm looking forward to continue using it in my projects. Thank you again for your help and for your work on this great tool!

Best regards,
Michael
