### ISSUE TITLE
Default Location for Generated Factories in the Test Directory

### ISSUE THREAD

**Issue by MichaelBrauner** [zenstruck/foundry#467]
Hello,

I've been using the `make:factory` command to generate entity factories, and I've noticed that by default, the factories are generated in the `src/Factory` directory. While this works fine and there is the --test option to generate them in the `test/Factory` directory instead, I've been wondering if the default behavior should be reversed.

In most use cases, these factories are utilized primarily, if not exclusively, within a testing context. Having them generated in the test/Factory directory by default would reflect this common usage and arguably make more sense.

Of course, there are exceptions where factories are used within a production environment, and having the flexibility to generate factories in the src/Factory directory is important for those cases. Still, it seems like those cases are less common and could be the ones to use an option (like --src).

I propose that the make:factory command generates factories in the test/Factory directory by default and includes a --src option for the instances where a factory is needed in a production context.

This change would align the make:factory command more closely with the most common use case of factories and make the command more intuitive to use.

I'm interested in hearing your thoughts on this and am open to further discussion.

Thank you for considering my proposal.

Best regards,
Michael

**Comment by kbond** [comment]
Hey Michael,

I personally agree with you. The problem is the tests directory isn't auto-wired/configured by default. I'm afraid we'd get many "my factory-as-a-service isn't working" issues (we get some of these as-is). Many tutorials exist showing the current way (ie SymfonyCasts).

So I think in this case it's better for maintainability to keep as-is.

**Comment by kbond** [comment]
We do have a namespace bundle config for the factory maker. We could also add a test option here as well I think. @nikophil, what do you think?

**Comment by MichaelBrauner** [comment]
Hi kbond,

Thank you for taking the time to explain the rationale behind the current setup. Your points about auto-wiring, potential issues, and the existing tutorials make a lot of sense.

I appreciate your suggestion about adding a test option to the namespace bundle config for the factory maker. However, given the potential complications and the fact that the current approach is well-documented and widely used, I'm quite satisfied with the status quo.

I mainly wanted to understand why things were set up as they are, and you've provided a clear explanation. Thanks again for your help!

Best,
Michael
