### ISSUE TITLE
TestState::addGlobalState not loading 

### ISSUE THREAD

**Issue by geoff-maddock** [zenstruck/foundry#47]
As per the [documentation](https://github.com/zenstruck/foundry#global-state), I added code to bootstrap.php to load the global state before my tests run.

```
<?php

use Symfony\Component\Filesystem\Filesystem;
use Zenstruck\Foundry\Test\TestState;
use App\Story\GlobalStory;

require \dirname(__DIR__).'/vendor/autoload.php';

(new Filesystem())->remove(\sys_get_temp_dir().'/zenstruck-foundry');

if (!\getenv('USE_FOUNDRY_BUNDLE')) {
    TestState::withoutBundle();
}

Zenstruck\Foundry\Test\TestState::addGlobalState(function() {
    GlobalStory::load();
    die('after load global story has run');
});

die('did not add global state');
```

When I run a functional test, it never adds the global state.  I added the die statements to see if it hits that block, and I only ever see the "did not add global state" message.   So it is running bootstrap but for some reason the add GlobalState function is not called.

Any tips on debugging this?  

Additional info:  I'm using codeception as my test framework.

**Comment by kbond** [comment]
Hmm, it looks like you copied the bootstrap code from this bundle's test suite. Can you remove:

```php
(new Filesystem())->remove(\sys_get_temp_dir().'/zenstruck-foundry');

if (!\getenv('USE_FOUNDRY_BUNDLE')) {
    TestState::withoutBundle();
}
```

and try again?

**Comment by kbond** [comment]
Also, does your test case use the `ResetDatabase` trait? This is required to use global state - I should mention this in the docs.

**Comment by geoff-maddock** [comment]
Removing the extra lines in the bootstrap.php worked.  Thanks!

I did in fact have the ResetDatabase trait used as well - good to point that out.

**Comment by geoff-maddock** [comment]
Something I'm noticing now though:  ResetDatabase is not doing anything.  If I run the test twice in a row, I get an error that it's trying to re-insert an entity with the same ID.   Not really related to the issue I opened here though.
