### ISSUE TITLE
Deprecate `addState()` in favor of `withAttributes()`

### ISSUE THREAD

**Issue by mpdude** [zenstruck/foundry#478]
What is the semantic difference between using `Factory::addState()` and `Factory::withAttributes()`? 

The former seems to simply dispatch to the latter.

Is there more intention behind it and should I be careful when I use which?

**Comment by kbond** [comment]
No difference, it's really just a way to be more explicit when writing _state_ methods. I think I'd be ok to deprecate addState - wdyt @nikophil?

**Comment by nikophil** [comment]
yes, I'm fine with it, moreover, in the version with "split factories", `addState()` and `withAttributes()` [are in the same class](https://github.com/zenstruck/foundry/blob/feat/split-factories/src/BaseFactory.php#L296)

**Comment by kbond** [comment]
Fixed in #493.
