### ISSUE TITLE
Can't change environment type in Bundles.php

### ISSUE THREAD

**Issue by ashraf-96** [zenstruck/foundry#481]
I have two different development environments (dev/dev_api) and when I change the environment in config/bundles.php  and in package yaml file I got this error below: 
**CODE:** 
**bundles.php** 
`return [
    Zenstruck\Foundry\ZenstruckFoundryBundle::class => ['dev_api' => true, 'test' => true],
];`
**zenstruck_foundry.yaml**
`when@dev: &dev_api
    zenstruck_foundry:
        auto_refresh_proxies: true
when@test: *dev_api`

**Error:** 
![image](https://github.com/zenstruck/foundry/assets/87384147/d3d4409a-a22b-49e0-983d-90b5a0a5a1a2)

**Version :** 
"zenstruck/foundry": "^1.34"
Any help please ?

**Comment by nikophil** [comment]
hello,

shouldn't it be like this?
```php
Zenstruck\Foundry\ZenstruckFoundryBundle::class => ['dev' => true, 'dev_api' => true, 'test' => true]
```

**Comment by ashraf-96** [comment]
Hi ! 
I tried it, same error shown

**Comment by nikophil** [comment]
please provide more information:
- full `zenstruck_foundry.yaml` file
- in which environment are you working?

**Comment by nikophil** [comment]
please provide more information:
- full `zenstruck_foundry.yaml` file
- in which environment are you working?

**Comment by ashraf-96** [comment]
zenstruck_foundry.yaml

![image](https://github.com/zenstruck/foundry/assets/87384147/9d3ceaa9-9f03-4e28-8e39-82d6b41ce085)

Env: 
Symfony: 5.4
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

**Comment by nikophil** [comment]
seems something is missing:
```yaml
when@dev_api: *dev
```
but the problem does not come from here I think

when I was talking about `which environment` I was meaning dev|test|prod|dev_api :sweat_smile: 

please also could you provide a full stacktrace? (add `-v` option to the command which creates the problem)

**Comment by ashraf-96** [comment]
sorry about mis-understanding, I'm working on dev_api environment.
stack strace: 
![image](https://github.com/zenstruck/foundry/assets/87384147/b2bcaa8a-69d1-4ea4-a2c1-ce666fc0a38e)

**Comment by ashraf-96** [comment]
I want to change the environment type inside the bundle instead of changing it for the whole project, I tried to change it in **.env** to **"dev"** and it worked, I'm creating factories successfully but if I want to do it the other way around it doesn't work.

**Comment by nikophil** [comment]
> I want to change the environment type inside the bundle instead of changing it for the whole project

not sure what you mean here? why do you want to achieve this? the environment is set for the whole app, not at bundle's level.

the error is weird: it seems the app does not load Foundry's config :thinking:

**Comment by ashraf-96** [comment]
I just want the bundle to work in the **dev_api** environment, somewhow at the bundle's level, it's not getting the **dev_api** environment, it's getting **dev**
`Zenstruck\Foundry\ZenstruckFoundryBundle::class => ['dev' => true, 'test' => true],` 
and I got the error when I change it to : 
`Zenstruck\Foundry\ZenstruckFoundryBundle::class => ['dev' => true, 'dev_api' => true,'test' => true],` 
Did you get what I mean ?

**Comment by nikophil** [comment]
yes, but it really not sounds like a Foundry problem: the bundle is agnostic of the app's environment. 

maybe it would help if you can create a public reproducerr
