### ISSUE TITLE
createMany and createOne or new->create does not work well together on the CI

### ISSUE THREAD

**Issue by benblub** [zenstruck/foundry#482]
```php
        EmbeddedContentFactory::createMany(5);
        EmbeddedContentFactory::createMany(3, ['type' => EmbeddedContentType::CantonNavigation]);
        EmbeddedContentFactory::createOne(['title' => 'Exact title', 'type' => EmbeddedContentType::Fixture]);

        $this->assertCount(9, EmbeddedContentFactory::repository()->findAll(), 'Expected 9 embedded contents');
```

This is failing in CI/Github actions = `Failed asserting that actual size 8 matches expected size 9.`

What is working
```php
        EmbeddedContentFactory::createMany(
            6,
            static function (int $i) {
                if ($i === 1) {
                    return ['title' => 'Exact title', 'type' => EmbeddedContentType::Fixture];
                }

                return ['title' => "Title $i"];
            }
        );
        EmbeddedContentFactory::createMany(3, ['type' => EmbeddedContentType::CantonNavigation]);

        $this->assertCount(9, EmbeddedContentFactory::repository()->findAll(), 'Expected 9 embedded contents');
```

I trying to understand what the problem can be but since its working local its hard to debug. Did someone know or can lead me the right direction? Not sure this is a bug ..

Additional: DAMA is used, the code is failing early without other code involved.

**Comment by benblub** [comment]
fun fact

If I switch the order there is no error raised
```php
        EmbeddedContentFactory::createOne(['title' => 'Exact title', 'type' => EmbeddedContentType::Fixture]);
        EmbeddedContentFactory::createMany(5);
        EmbeddedContentFactory::createMany(3, ['type' => EmbeddedContentType::CantonNavigation]);

        $this->assertCount(9, EmbeddedContentFactory::repository()->findAll(), 'Expected 9 embedded contents');
```

**Comment by nikophil** [comment]
Hi @benblub 

sorry I have no clue why this is happening. I bet this is not related to Foundry, but not really sure. The "fun fact" is really weird :exploding_head: 

Maybe if you can create a public reproducer I could give a hand.

I recently heard about https://github.com/mxschmitt/action-tmate which can help to debug your actions by ssh-ing on the runners, maybe this could help!

**Comment by benblub** [comment]
ok will take a look by time, thx

**Comment by nikophil** [comment]
I'm closing this stale issue. feel free to reopen :)
