### ISSUE TITLE
Stub maker commands: missing command name in error

### ISSUE THREAD

**Issue by jmsche** [zenstruck/foundry#484]
Hi,

When running e.g. `symfony console make:factory`, the error message is missing the command name:

```
 [ERROR] To run "" you need the "MakerBundle" which is currently not installed.

         Try running "composer require symfony/maker-bundle --dev".
```

It's because the stub command uses `static::$defaultName` which is not defined anymore.

**Comment by kbond** [comment]
Thanks for the report - should be fixed in #485.
