### ISSUE TITLE
Generated factories with PHPStan methods cause PhpStorm to mark file as error

### ISSUE THREAD

**Issue by rsereir** [zenstruck/foundry#503]
Hello,

I have an issue with phpstan annotations on phpstorm:

`Method with same name already defined in this class`

I didn't find anything opened on this github, and nothing else in the web.

I didn't really know if it's a phpstorm i

ssue or more depth Foundry problem ( or maybe just config..? )

This is the render of my Factory with the error:
<img width="1586" alt="Screenshot 2023-09-09 at 15 53 35" src="https://github.com/zenstruck/foundry/assets/43849341/95d3892a-9660-476f-bbf6-d0701347d921">

**Comment by kbond** [comment]
Hey, I just ran into this the other day too. My solution was to wrap the type-hint in `()`, so for your example: `@phpstan-method static (list<Proxy<EmailTemplateTranslation>>) all()`.

Is your above example what's generated by the maker?

**Comment by rsereir** [comment]
@kbond Thanks for your tip, it looks better now, but it's not underlight like previous methods 

Yes all is generated by maker

<img width="837" alt="Screenshot 2023-09-09 at 16 57 01" src="https://github.com/zenstruck/foundry/assets/43849341/e0c2505f-21d8-45d4-a22b-efeaeda105fd">

**Comment by kbond** [comment]
> but it's not underlight like previous methods

Yeah, PHPStorm doesn't recognise the syntax but at least it no longer marks the entire file with an error.

> Yes all is generated by maker

Ok, we'll need to update the maker template - let's keep this issue open.

**Comment by nikophil** [comment]
PHPStorm is not smart enough to unedrstand nested generics in `@method` annotations, nevertheless since some time, these annotations are not required anymore I think
