### ISSUE TITLE
[Foundry 2] Allow objects creation in data provider

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#532]
Maybe we could use lazyness behavior of the proxy system and delay persistence when the object is accessed

**Comment by kbond** [comment]
Yes, we should at least experiment with this before releasing 2.0 to ensure it's possible w/o a BC break.

**Comment by nikophil** [comment]
cool! I'm just wondering if in any way, we could add a `->proxy()` method to the `PersistenceObjectFactory`... because it will be one of the only usecase, I'd reallyl need proxies
