### ISSUE TITLE
Using Stories multiple times in a test class

### ISSUE THREAD

**Issue by geoff-maddock** [zenstruck/foundry#55]
I'm using codeception and I'm trying to implement using a Story in a test class.  
With my current configuration, each test method is wrapped in a transaction using a doctrine feature in codeception.
So I can isolate what is created for that test.

To that end, I have a couple tests that I'd like to call the same story in:

```
class TicketControllerCest
{
    use Factories;

    private int $testId;

    /**
     * @group ticket
     * @group index
     * Check to see that an internal user with proper permission has access to index lists.
     */
    public function indexWithInternalUserPermission(FunctionalTester $I)
    {
        //  first time this story would be loaded
        TicketStory::load();
        $I->loginAsInternalUser($I);

        $I->wantTo(sprintf('View ticket index list with internal user permission'));

        $I->seeIndexPage($I, 'Tickets', 'Tickets', 'Tickets', 'ticket');
        $I->seeListItems($I, 'Ticket');

        // fixes weird bug
        unset($_GET);

        $I->logoutInternal($I);
    }

    /**
     * @group ticket
     * @group index
     * Check to see that an internal admin user with proper permission has access to index lists.
     */
    public function indexWithInternalAdminUserPermission(FunctionalTester $I)
    {
        // second time this story would be loaded
        TicketStory::load();
        $I->loginAsInternalAdminUser($I);

        $I->wantTo(sprintf('View ticket index list with internal admin user permission'));

        $I->seeIndexPage($I, 'Tickets', 'Tickets', 'Tickets', 'ticket');
        $I->seeListItems($I, 'Ticket');

        // fixes weird bug
        unset($_GET);

        $I->logoutInternal($I);
    }
```

If I run the whole test class:
```
codecept functionalFixture Controller/TicketControllerCest
```

The first test passes, and the second test fails - there are no Ticket entities found.

If I just run either test individually, they both pass.

Is this how Stories work typically?  Is there a way to force them to re-load in each instance?
Or is the transaction wrapping need to be done with Foundry for it to be aware that the Story should be reloaded?

**Comment by kbond** [comment]
From the example above, you aren't using the `Factories` trait. This is what resets the story "state" after each test.

**Comment by geoff-maddock** [comment]
I managed to leave that out when I copied it originally, but I am in fact using it.  Updated to the actual code (minus some additional irrelevant methods after).  I am not using ResetDatabase trait (it wouldn't work for me) or extending WebTestCase.

**Comment by kbond** [comment]
Oh, you aren't extended `WebTestCase`? This is the problem - the `Factories` (and `ResetDatabase`) trait both require it. Basically, the reset isn't running with your setup.

Does Codeception not use the `WebTestCase` when working with a Symfony app?

**Comment by kbond** [comment]
More and more, this is showing the incompatibility of this library with Codeception. I'll try and take a look at what would be involved to add support (#56).

**Comment by geoff-maddock** [comment]
I wasn't using ```WebTestCase``` with my tests prior to trying to implement Foundry for fixtures.   (Previously we were using a testing database without fixtures).   I did try it out, but I'm only not using it currently because it didn't work when I tested using ```WebTestCase``` and  ```Resetdatabase``` - the transaction wrapping didn't happen.  

However, when I used Doctrine2 cleanup transaction wrapping (a standard codeception module), that piece did work.

**Comment by kbond** [comment]
Can you see if this helps:

```php
// tests/_support/Helper/FoundyModule.php

namespace App\Tests\Helper;

use Codeception\TestInterface;
use Zenstruck\Foundry\Test\DatabaseResetter;

class FoundyModule extends \Codeception\Module
{
    public function _before(TestInterface $test)
    {
        DatabaseResetter::resetSchema($this->getModule('Symfony')->kernel);
    }
}
```

And enable in `tests/functional.suite.yml`:

```yaml
actor: FunctionalTester
bootstrap: bootstrap.php
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \App\Tests\Helper\Functional
        - \App\Tests\Helper\FoundryModule
```

**Comment by geoff-maddock** [comment]
Thanks for  the follow up.   I'm going to circle back and try this when I have some cycles (this week).

**Comment by geoff-maddock** [comment]
I took a look at adding this - so the resetDatabase actually drops the database and re-adds it between each test?
Doesn't that defeat the purpose of wrapping each test in a transaction?   

That said, I implemented and ran it.   I got an error:
```
  [RuntimeException] Error running "doctrine:schema:create":

...
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'row' alread
  y exists

```

Sort of seems like it didn't drop the database.

**Comment by kbond** [comment]
Going to close for now and wrap into #56.
