### ISSUE TITLE
Support need for specific cases

### ISSUE THREAD

**Issue by Zer0NimO-web** [zenstruck/foundry#568]
Hello, 

 I couldn't find a way to do some specific things while reading Foundry documentation.
 
 First, i want to know if it is possible for a many-to-many relationship (between DIrectory and User) to do this : 
 ```php
     DirectoryFactory::createMany(
            3,
            [
                // ... stuff
                'users' => UserFactory::random(3, [ 'sharingZones' => [ $theOneIWant ] ]),   
                // here i want to add few users which are linked to a specific sharingZone
                // (a user can be linked to many sharingZones)
            ]
        );
 
 ```
Then, i want to build stories with parameters such as : 
```php
      SharingZoneStory::build($users, $documents);
 ```
 
 But i don't know how to create a story which involves such parameters for the build() function.
 
 Thanks a lot for your time.

**Comment by nikophil** [comment]
Hello,

for your first question, I think you should do this way:
```php
    DirectoryFactory::createMany(
           3,
           [
               'users' => UserFactory::new([ 'sharingZones' => [ $theOneIWant ] ])->random(3),   
           ]
       );
```

For the second question, it is currently not possible to parametrize stories.
This would be a nice addition, but which would come with some complexity because stories are only loaded once, even if you call it twice

**Comment by Zer0NimO-web** [comment]
Thank you very much. For the first question i'm afraid it won't work since i don't want to create new users, i want to get users already persisted which are linked with a specific sharingZone.

It's clear for the second case. Thanks a lot.

**Comment by nikophil** [comment]
oups, you're right :sweat_smile: 

what about `randomSet()`?

**Comment by Zer0NimO-web** [comment]
It could do the job but still i don't know how to write the condition. I don't even know if it is possible to do something like : 
```php

UserFactory::randomSet(4, ['SharingZones' => /* ... is linked to $specificSharingZone ... */]);
```

**Comment by nikophil** [comment]
sorry, I was not very helpful on this one :sweat_smile: 

I was thinking at first you had a `ManyToOne` between `User` and `SharingZones`. I think you cannot do it for `*ToMany` :man_shrugging:

**Comment by Zer0NimO-web** [comment]
No problem, you helped me a lot!
