### ISSUE TITLE
Using story pools without persisting 

### ISSUE THREAD

**Issue by Brewal** [zenstruck/foundry#573]
I'm using foundry without doctrine and manually save my objects with this function in my factories : 

```
protected function initialize(): self
    {
        return $this->withoutPersisting()
            ->afterInstantiate(
                fn (Establishment $establishment) => $this->repository->save($establishment),
            );
    }
``` 

I'm facing an issue while using stories and pools.  

If I call `$this->addToPool()` inside a story, I get the following error : 

```
RuntimeException : Should not get doctrine's object manager when persist is disabled.
```

What I understood is that I wouldn't be able to use pools because of the `normalizeObject` private method of `Story` : 

```
        // ensure proxies are persisted
        if (!$object->isPersisted()) {
            $object->save();
        }
```

Is there a workaround for this use case ? 

Thanks to this : https://github.com/zenstruck/foundry/pull/488 we can globally disable persist. Would it make sense to check for this configuration in the Story ?

**Comment by nikophil** [comment]
this is fixed!
