### ISSUE TITLE
[2.x] remove `@method` from `make:factory`

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#596]
since in Foundry 2.x, autocompletion comes out of the box (in recent phpstorm versions, and I'm pretty sure it works in VS code as well)

instead, provide an option `--with-phpdoc` which would only add the doc if the option is provided

**Comment by Aerendir** [comment]
It (almost) works out of the box: it has a return type hint equal to `mixed`, so static analyzers will complain if you pass the returned object somewhere the accepted type is `YourEntity` as it is marked as `mixed`.

The annotation serves to specify the correct returned type.

**Comment by nikophil** [comment]
Hi!

Which method are you talking about?
