### ISSUE TITLE
Unrecognized option "make_story" under "zenstruck_foundry"

### ISSUE THREAD

**Issue by rimas-kudelis** [zenstruck/foundry#607]
The docs refer to `make_story` configuration option, but when attempting to use it, I got an error saying it's not a recognized option:

> Unrecognized option "make_story" under "zenstruck_foundry". Available options are "auto_refresh_proxies", "database_resetter", "faker", "global_state", "instantiator", "make_factory".

**Comment by kbond** [comment]
Hey @rimas-kudelis, this is an unreleased feature. Sorry for the confusion, we should have added a _version added_ admonition to the docs.

**Comment by mvhirsch** [comment]
Just ran into this one too. 

@kbond any plans to release 1.38 (or similar)?

**Comment by nikophil** [comment]
@mvhirsch we're working on it! I hope by the end of the week or the next one

**Comment by nikophil** [comment]
it has been released since then! I'm closing this
