### ISSUE TITLE
Migration Guide to version 2

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/foundry#619]
Could you please add a link from the release note https://github.com/zenstruck/foundry/releases/tag/v2.0.0 to the migration guide?
Additional in the README.md would be great

**Comment by Chris53897** [comment]
'src/Factory' should be included in the path array.

return RectorConfig::configure()
    ->withPaths(['src/Factory', 'tests']) // add all paths where Foundry is used
    ->withSets([FoundrySetList::UP_TO_FOUNDRY_2])
    ;

**Comment by nikophil** [comment]
Hi @Chris53897 

> Could you please add a link from the release note https://github.com/zenstruck/foundry/releases/tag/v2.0.0 to the migration guide?
Additional in the README.md would be great

yes, this a nice suggestion

**Comment by nikophil** [comment]
release note updated + readme and upgrade guide updated in 2.x and 1.x as well
