### ISSUE TITLE
Creation of dynamic property App\Entity\MyEntity::$_autoRefresh is deprecated

### ISSUE THREAD

**Issue by norkunas** [zenstruck/foundry#630]
Running full suite currently getting this 276 times :smile:

**Comment by nikophil** [comment]
are you using symfony 7?

**Comment by norkunas** [comment]
Yes, this is while doing upgrade to 7.1

**Comment by nikophil** [comment]
we're investigating this [here](https://github.com/zenstruck/foundry/pull/622)

let me close this issue

**Comment by norkunas** [comment]
Ah, thanks

**Comment by nikophil** [comment]
Hey @norkunas 

maybe as a workaround for now while we're investigating for a solution, you can block `symfony/var-exporter` to ~7.0.x. It has no dependency, should not be problematic

**Comment by norkunas** [comment]
For me it works, it's just a deprecation :man_shrugging:
