### ISSUE TITLE
Find functions do not refresh entity

### ISSUE THREAD

**Issue by cooldude77** [zenstruck/foundry#638]
Hi, 

I will try to keep this short. 

I am doing a test case using Zenstruck Browser and then using find method of foundry to read the entity. 

**Process 1**
First I insert the entity, let us say an order item mapped to a cart

I use Foundry _find_ method to see it the order item has been inserted 

Next I use assert to determine if the item has been created

**Process 2**
Then I update the cart quantity for that item . I repeat the find method . However find method brings up the previous quantity , not the updated one. 

If I do an assert for individual quantity property of item , the test passes. 

IMO, find does not refresh the entity but calling a method does auto refresh on the entity and thus test gets passed. 
For example `item->getQuantity()` triggers refresh 
This happens in Proxy class 
```

private function _autoRefresh(): void
    {
        if (!$this->autoRefresh) {
            return;
        }

        $this->_refresh();
    }
```

With find or find By refresh is not triggered. If we use doctrine entity manager, it gets us the updated value. 

Even though there is no problem in test output, during debugging I see the unrefreshed value using find method. 

Is this an issue? Is this resolvable.

**Comment by nikophil** [comment]
Hi!

could you provide a little bit more code please? 

Indeed, using `find()` a second time may only get the object from doctrine's cache, but as soon as you use a getter, the proxy will refresh the object. Then, I'm not sure to understand where is the problem?

Maybe you can also call `$item->_refresh()` instead of using `find()`?

**Comment by cooldude77** [comment]
Hi @nikophil ,
 
 You got the problem exactly right. It was a little bit troublesome when I was trying to debug a problem while using a test case. Internally , the Factory methods use find(By) of doctrine and which does the intended behavior as you explained. 

I was feeling that since Factory find is a wrapper, it would be good idea to refresh it before querying doctrine. As for now I have resorted to calling entitymanager and then finding the object.
