### ISSUE TITLE
[2.0] Re-add `assertPersisted()` & `assertNotPersisted()`

### ISSUE THREAD

**Issue by simondaigre** [zenstruck/foundry#661]
In 2.0, `assertPersisted()` and `assertNotPersisted()` were removed without replacement.

These methods was really useful. Is it possible to re-add them ?

**Comment by nikophil** [comment]
I'm not 100% sure why they have been removed. @kbond any hints?

**Comment by kbond** [comment]
> I'm not 100% sure why they have been removed. @kbond any hints?

I didn't think they were useful - if they are, I'm ok re-adding.

**Comment by simondaigre** [comment]
I'm using them in some application tests, for example to check if the object was deleted by the controller.

**Comment by kbond** [comment]
Ok, that's a super fair use-case. I'll get these re-added.

**Comment by nikophil** [comment]
@simondaigre the methods were re-added and released in v2.0.6

**Comment by simondaigre** [comment]
Thank you !
