### ISSUE TITLE
Foundry 2 with PHPUnit changes the error handler of Symfony

### ISSUE THREAD

**Issue by marien-probesys** [zenstruck/foundry#667]
Hi,

I've made the upgrade to Foundry 2 this week, and I now have an annoying issue. When I run my tests, the output ends with a message error:

```console
php ./bin/phpunit
PHPUnit 11.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.20 with Xdebug 3.3.2
Configuration: /var/www/html/.phpunit.xml.dist

...............................................................

THE ERROR HANDLER HAS CHANGED!
```

I've searched and discovered that this is Symfony which complains about the error handler being changed.

Note that all the tests pass correctly, and the command doesn't fail because of this message. However, it seems to break the report of deprecation notices as they aren't shown.

When I comment the code of the function `restorePhpUnitErrorHandler()` in the file [`phpunit_helper.php`](https://github.com/zenstruck/foundry/blob/2.x/src/phpunit_helper.php) though, the error disappears and I get the deprecation notices. Obviously, as I don't know the role of this code, I'm absolutely not confident that it's the solution to my problem :)

Since I've made a lot of upgrades in the mean time (Symfony 7, Doctrine ORM 3, Doctrine DBAL 4), and that I'm running the tests with PHPUnit 11 which is not yet officially supported by Symfony, I thought the issue would come from some misconfiguration. However I was able to reproduce the issue in a simple project (https://github.com/marien-probesys/foundry-issue). It comes with Symfony 7, Foundry 2 and PHPUnit 9.6. If you want to reproduce, the instructions are given in the repository. I hope it helps!

**Comment by nikophil** [comment]
Hi @marien-probesys 

this problem is a nightmare :sweat:  

> Since I've made a lot of upgrades in the mean time (Symfony 7, Doctrine ORM 3, Doctrine DBAL 4), and that I'm running the tests with PHPUnit 11 which is not yet officially supported by Symfony, I thought the issue would come from some misconfiguration. 

Very strange: you were using PHPUnit 11 AND Symfony PHPUnit bridge's deprecation handler, I did not even know this was possible! Indeed, phpunit >9 is not officially supported by Symfony, and we definitively won't support this.
(as a curiosity how did you manage to do this? :sweat_smile:)
  
> However I was able to reproduce the issue in a simple project ([marien-probesys/foundry-issue](https://github.com/marien-probesys/foundry-issue))

very nice to create a reproducer like this!

> It comes with Symfony 7, Foundry 2 and PHPUnit 9.6

I think the solution of the problem would be indeed to skip the code in `phpunit_helper.php` when PHPUnit 9 is used

some more context on this problem:
- https://github.com/symfony/symfony/issues/53812
- https://github.com/zenstruck/foundry/issues/579
- https://github.com/zenstruck/foundry/issues/640

**Comment by nikophil** [comment]
v2.0.6 was released :)

**Comment by marien-probesys** [comment]
It doesn't look like an easy problem indeed, thanks for the quick fix! :)

> Very strange: you were using PHPUnit 11 AND Symfony PHPUnit bridge's deprecation handler, I did not even know this was possible! Indeed, phpunit >9 is not officially supported by Symfony, and we definitively won't support this.
(as a curiosity how did you manage to do this? 😅)

Well, I started to work on the update before knowing it wasn't possible :upside_down_face: I really didn't do a lot of work (the commit https://github.com/Probesys/bileto/commit/4dd097d16e6aef4f14f46ad6299d086b8ab07617), but it certainly doesn't work perfectly either. The thing is that I didn't configure the Symfony listener in my PHPUnit configuration file, but didn't remove the bridge. It seems that some deprecations are still reported, but not all of them. I have to admit that some aspects of the PHPUnit bridge is unclear to me, but as long as my tests work when everything is fine, and fail when an error is introduced, I'm fine with this solution!

Now, maybe I should consider to downgrade to PHPUnit 9 :sweat_smile:

**Comment by nikophil** [comment]
I think you should either stick to phpunit 9, and use the  bridge OR remove the bridge, and upgrade to the last phpunit version. Now PHPUnit is quite as efficient as symfony's bridge for deprecations, that's what I've done on my projects
