### ISSUE TITLE
Database reset randomly fails

### ISSUE THREAD

**Issue by MatTheCat** [zenstruck/foundry#682]
We have a test suite using Foundry v1.38.3’s  `ResetDatabase` trait whose `doctrine:schema:create` randomly fails (It’s quite rare though: this happens every 200 tests or so):

> In Connection.php line 33:
>
>  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "[NAME]" already exists                                                                           
>
> doctrine:schema:create [--em EM] [--dump-sql]
> /builds/[MASKED]/vendor/zenstruck/foundry/src/Test/AbstractSchemaResetter.php:33
> /builds/[MASKED]/vendor/zenstruck/foundry/src/Test/ORMDatabaseResetter.php:73
> /builds/[MASKED]/vendor/zenstruck/foundry/src/Test/ORMDatabaseResetter.php:61
> /builds/[MASKED]/vendor/zenstruck/foundry/src/Test/DatabaseResetter.php:58
> /builds/[MASKED]/vendor/zenstruck/foundry/src/Test/ResetDatabase.php:81
> /builds/[MASKED]/vendor/phpunit/phpunit/phpunit:107

As we’re using PostgreSQL I wonder if we’re hitting https://github.com/zenstruck/foundry/issues/455. When I looked at https://github.com/zenstruck/foundry/pull/458 I saw that connections are dropped in `dropAndResetDatabase`, but as we configured the `schema` reset mode this method is not called by `resetSchema`. I don’t know if it’s an issue but it is the only explanation I can think of :confused:

**Comment by nikophil** [comment]
Hi @MatTheCat 

>  I saw that connections are dropped in dropAndResetDatabase, but as we configured the schema reset mode this method is not called by resetSchema

I think this is normal. In `schema` mode, `dropAndResetDatabase()` is called by `resetDatabase()`  in a `#[BeforeClass]` hook.

I'm sorry but without a reproducer I doubt we can help you 😕

We're using Foundry in several projects along with PG and never had this problem. Any chance you're using paratest or something like this, which could actually try to create the db whereas is already exists?

**Comment by MatTheCat** [comment]
Hi!
There is no paratest, no DAMADoctrineTestBundle... and it seems totally random so I cannot reproduce 😕

**Comment by nikophil** [comment]
do you run your tests in random order, which would explain this randomness?

**Comment by MatTheCat** [comment]
We're using PHPUnit `testsuite` flag so I'm not sure 🤔

Could the schema drop command fail without stopping the execution?

**Comment by nikophil** [comment]
This sounds very unlikely 🤷‍♂️

**Comment by MatTheCat** [comment]
Managed to get some logs from the CI and there are in fact many errors regarding missing tables, but these don’t seem to impact tests results. I somewhat reproduced the behavior on my computer and the first thing I can say is that this happens when running many tests sequentially.

**Comment by nikophil** [comment]
do you have several entity managers? maybe they are not correctly reset

This *might* explain why you'd have missing tables, but I still can't explain the `Duplicate table` problem

**Comment by MatTheCat** [comment]
We do have two entity managers, but the issue seems to be linked with AJAX requests performed in end-to-end tests. Still investigating.

**Comment by nikophil** [comment]
just in case, this is something you can configure: which entity manager you want to reset. Otherwise, only the default one will be reset

https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#database-reset

**Comment by MatTheCat** [comment]
Yep the two managers are correctly configured to be reset :+1: 

I found that if a test triggers an AJAX request but doesn’t wait for its response, the database resetter will kick in (because the test technically ended) and the two will compete for their own database use.

I still don’t know if it is the root cause, but it certainly looks like something we’ll have to fix on our side.

**Comment by MatTheCat** [comment]
So I didn’t manage to reproduce the failure on my computer even once, but after ensuring all AJAX requests return before ending tests, this kind of issue did not show up again.

Waiting another week for good measure :crossed_fingers:

**Comment by nikophil** [comment]
I'm pretty sure that we can close this, it very much sounds like it's not related to Foundry
