### ISSUE TITLE
Using `Zenstruck\Foundry\Test\Factories` triggers deprecations

### ISSUE THREAD

**Issue by deluxetom** [zenstruck/foundry#696]
Similar to https://github.com/zenstruck/foundry/issues/680 and https://github.com/zenstruck/foundry/issues/650

I tried everything to ignore those:
- Removed `phpunit-bridge`
- Updated the deprecation level (via `SYMFONY_DEPRECATIONS_HELPER`) but thats just in PHPUnit, it shouldn't impact Symfony

<img width="1364" alt="Screenshot 2024-09-30 at 9 43 32 AM" src="https://github.com/user-attachments/assets/e383bc4d-07c8-4dfd-8560-b6d539881784">

I'm not sure what else to try to remove those internal notices.
I use Factories in my data fixtures, `dev` and `test` environments

Let me know if I missed something

**Comment by nikophil** [comment]
Hi,

sorry for the late answer... I think I've finally found an elegant solution for this

see https://github.com/zenstruck/foundry/pull/704

**Comment by nikophil** [comment]
fixed by https://github.com/zenstruck/foundry/pull/704
