### ISSUE TITLE
Support for Object Creation from Named Constructors in Zenstruck Foundry

### ISSUE THREAD

**Issue by d-cichon** [zenstruck/foundry#702]
Hi,

I checked the library and read through the documentation, but there is currently no way to create a new object using a named constructor. In my opinion, this should be addressed, as named constructors are very popular in DDD (Domain-Driven Design) practices today.

Thank you!

**Comment by nikophil** [comment]
Hi @d-cichon 

there is actually a feature to do this:
```php
class MyFactory extends ObjectFactory
{
    protected function initialize(): static
    {
        return $this
            ->instantiateWith(
                Instantiator::namedConstructor('namedConstructorMethod')
            )
}
```

I realize that this feature is not documented, this should be fixed

**Comment by d-cichon** [comment]
@nikophil Thank you! <3

There is problem with phpstan, but it solve my problem.

![image](https://github.com/user-attachments/assets/19c76e87-aae4-4309-977f-9f7ff5e69f2f)

**Comment by nikophil** [comment]
cool!

is that really a phpstan problem? or just your IDE that does not understand what's going on?

**Comment by nikophil** [comment]
I've documented [here](https://github.com/zenstruck/foundry/pull/703) the `namedConstructor` stuff.

I'll close you issue once the PR will be closed. Feel free to re-open it if something is still problematic
