### ISSUE TITLE
Change in symfony exception handler

### ISSUE THREAD

**Issue by mmarton** [zenstruck/foundry#711]
Hi!

In yesterday releases (7.1.6, 6.4.13, 5.4.45) symfony fixed it's exception/error handler registration issue with phpunit.
see: https://github.com/symfony/symfony/pull/58372

Now the workaround introduced after my previous issue (https://github.com/zenstruck/foundry/issues/640) is the one that triggers phpunit's `THE ERROR HANDLER HAS CHANGED!` warning :D  

if I remove the call to KernelHelper::shutdownKernel the warning is gone.

```
env:
phpunit/phpunit                                11.4.2
symfony/framework-bundle                       7.1.6
zenstruck/foundry                              1.38.3
```

**Comment by nikophil** [comment]
Hi @mmarton 

would you mind to create a PR?

**Comment by lsv** [comment]
What worked for me was just to empty the function `restorePhpUnitErrorHandler` in `src/phpunit_helper.php`

![image](https://github.com/user-attachments/assets/7ce523e7-856e-45e9-87ff-b37bf7de12fd)

With the function intact

![image](https://github.com/user-attachments/assets/f70e182b-3508-44ca-bb2a-9cb08a680476)

PHP 8.3
PHPUnit 11.4.3
Symfony 7.1
Foundry: v2.2.2

**Comment by kbond** [comment]
So we need to revert #643 and #642?

**Comment by nikophil** [comment]
I think so, I just want to take a little bit more time to be sure that it works in every situation

**Comment by nikophil** [comment]
When I remove the call to `restorePhpUnitErrorHandler()`, I got this warning in Foundry's testsuite
```
1) Zenstruck\Foundry\Tests\Integration\ArrayFactoryTest::can_create_with_defaults
Test code or tested code did not remove its own exception handlers
```
although it uses 7.1.6 :shrug:

**Comment by nikophil** [comment]
I've gave it another try: https://github.com/zenstruck/foundry/pull/729

everytuing seems OK, except one test permutation (always the same, and not even the one with lowest deps :thinking: ), I have to dig a little

**Comment by nikophil** [comment]
I've noticed that in https://github.com/zenstruck/foundry/actions/runs/12155369606/job/33896794700?pr=729 the problem occurs only when reset database is NOT used 

I really don't know why :shrug:

**Comment by nikophil** [comment]
apparently `symfony/runtime` is needed for the workaround... just by adding `symfony/runtime` as a require dev fixes the problem in our testsuite
