### ISSUE TITLE
[2.x] Proxy that's passed in an array duplicates object on save

### ISSUE THREAD

**Issue by KDederichs** [zenstruck/foundry#712]
When you create and return a proxy object in an array and then try to call `_save()` on that it'll try to re-insert the object causing duplicate key exceptions.

``` php
class BaseFoo {
    public function makeFixture(): array
    {
        $bar = BarRepository::createOne();
	
        return ['barFixture' => $bar];
	}
}

class FooTest extends BaseFoo
{
    public function testFoo()
    {
        $fixtures = $this->makeFixture();
        $fixtures['barFixture']->setBaz('a');
        $fixtures['barFixture']->_save(); //Causing exception here
    }
}
```
Again calling `_real()` before setting the values fixes this which makes me suspect that it's related to #710 but I'll report it as separate for now in case it's not.

**Comment by nikophil** [comment]
Please, could you share the factories + the error (with stack trace of possible)?

I can't see why returning and acting on an array does create a problem.
Does the following works?
```php
$bar = BarRepository::createOne();
$bar->setBaz('a');	
$bar->_save();
```

the best for both of those problems would be to create a reproducer app, if possible :pray: 

thanks

**Comment by KDederichs** [comment]
Hmm yeah can't seem to reproduce that one, strange I'll give you one for the other issue though
