### ISSUE TITLE
`RepositoryDecorator::inner()` is a private method

### ISSUE THREAD

**Issue by marienfressinaud** [zenstruck/foundry#713]
The documentation mentions that we can call `$repository->inner()` to get the real wrapped repository from a proxy (see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#repository-proxy).

Unfortunately, since Foundry v2, it seems that the new `RepositoryDecorator` class that provides the `inner()` method, declares it as a private method.

I'm not sure if this change was intentional, but it would be very helpful to get the `inner()` method back to public :)

Thanks!

**Comment by nikophil** [comment]
Hi @marienfressinaud 

yes, you're right, this method should be public.
Are you willing to make a PR?

**Comment by nikophil** [comment]
released in 2.2.1

**Comment by marienfressinaud** [comment]
Thanks! I didn't expect the fix to be available so soon :)
