### ISSUE TITLE
Cannot set attribute ... for object "...." (not public and no setter).

### ISSUE THREAD

**Issue by floriankraemer** [zenstruck/foundry#739]
I'm getting this exception

> InvalidArgumentException: Cannot set attribute "is_completed" for object "...." (not public and no setter).

because my object has intentionally no setter and getter. As a domain aggregate, all it needs is a completed() method, that internally sets this field to true.

Is there an existing workaround that doesn't require me to implement getters and setters or would you welcome a pull request that adds a hydrator based on reflections?

Edit: Changing the `PropertyAccessor` by adding this elseif-statement, I've made it work. If anyone could confirm that this is a valid solution I'll prepare a PR.

```php
            } elseif ($object instanceof \stdClass && property_exists($object, $property)) {
                $object->$property = $value;
            } elseif ($reflectionClass->hasProperty($property)) {
                $property = $reflectionClass->getProperty($property);
                $property->setAccessible(true);
                $property->setValue($object, $value);
            }
```

**Comment by nikophil** [comment]
Hello,

This is already a solved problem.

You can either always "force" properties globally in the config, with `zenstruck_foundry.instantiator.always_force_properties`.
You can also force one or all properties for a specific factory: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#instantiation
