### ISSUE TITLE
Couldn't find this class: Zenstruck\Foundry\Utils\Rector\FoundrySetList

### ISSUE THREAD

**Issue by guelosuperstart** [zenstruck/foundry#741]
Hello,  

I couldn't find this class: `use Zenstruck\Foundry\Utils\Rector\FoundrySetList;`.  

I recently updated to `zenstruck/foundry` and wanted to include `FoundrySetList::UP_TO_FOUNDRY_2_0` in my Rector configuration, but the class appears to be undefined.  

For context, I'm using Symfony 7.2 and PHP 8.4.  

Thank you for your help!

**Comment by nikophil** [comment]
Hi, which version of foundry are you using?
The rector set is only available in version 1, you should only use it once, and remove it once you've upgraded

**Comment by guelosuperstart** [comment]
Hello,  

I’m currently using `zenstruck/foundry: 2.2.2`.  

So, I need to downgrade to v1 to check compatibility with Rector and then upgrade back to v2

Thank you !!

**Comment by nikophil** [comment]
Not sure what you mean: did you upgrade from v1 to v2?
You'll find [here](https://github.com/zenstruck/foundry/blob/2.x/UPGRADE-2.0.md) a migration guide

**Comment by guelosuperstart** [comment]
I’d like to migrate to v2, but I updated the components before fully following the migration guide. 😅

Thank you for your help!
