### ISSUE TITLE
Error Resetting SQLite Database Introduced in 2.3.1

### ISSUE THREAD

**Issue by richard4339** [zenstruck/foundry#746]
Since upgrading to v2.3.1 with Symfony 7.2.1 on Windows, I cannot run any tests with the ResetDatabase trait, every instance of it throws a "Failed to remove file" error on the test db file with SQLite.

`Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\path\to/var/test.db": unlink(C:\path\to/var/test.db): Resource temporarily unavailable`

Rolling back to 2.2.2 and 2.3.0 immediately resolves the problem, which makes sense as the logic to delete the SQLite database file was introduced in 2.3.1. Edit to note this is Windows specifically, it does not occur in linux.

**Comment by nikophil** [comment]
Hi @richard4339 

~any chance it is because the db is opened by some other sql client?~

EDIT: ok, I've reproduced and fixed the error in https://github.com/zenstruck/foundry/pull/747

**Comment by richard4339** [comment]
Thanks!
