### ISSUE TITLE
Remove attribute prefix when doing findOrCreate() ?

### ISSUE THREAD

**Issue by wouterj** [zenstruck/foundry#75]
I'm not totally sure whether we're wrongly using this library or whether I have stumbled on a bug (I'm having this bug in so many places that I almost believe it's the first). That's why I decided to open an issue first, I'm happy to provide a PR to fix this issue.

---

In our code, some properties are not set by the constructor or by property accessible setters. E.g. a `User#subscribeTo($subscription)` method. However, I want to create fixtures with subscriptions. From what I understand, the `force:` attribute prefix is the way forward: `['force:subscription' => $subscription]`.

However, this does not work with `findOrCreate()`, as doctrine will try to use a field called `force:subscription` instead of the expected `subscription`. I'm often using `findOrCreate()` in my tests, as I want to avoid creating new test fixtures if a matching is already found.

The solution would be to strip attribute prefixes before passing them into `repository()->find($attributes)`: https://github.com/zenstruck/foundry/blob/ea8430f1ad295c88818e056ca565e5db2c528e0b/src/ModelFactory.php#L55-L59

**Comment by kbond** [comment]
Yes, this is indeed an oversight. If you could PR your proposed solution, that'd be great!
