### ISSUE TITLE
[Idea] Add a foundry console command

### ISSUE THREAD

**Issue by wouterj** [zenstruck/foundry#76]
I would like to generate fixtures from outside the application. More concrete, we're using a "stress testing" application that runs a couple of stress tests. Before doing so, I want that application to set-up some fixtures.

The problem here is that the number of fixtures to generate is dynamic (e.g. in a stress test with 5 users, I need 5 user fixtures, but a stress test with 50 users, will require 50 user fixtures). A colleague of mine came with the idea of using a console command for this, e.g. `bin/console foundry:generate --factory=App\Factory\UserFactory --amount=50`. This command then invokes `UserFactory::createMany(50)` and outputs the data, so the stress test library can e.g. parse the usernames.

Would you be interested in such a command in the bundle of this package? Or is there another (already existing) way to accomplish this use-case? Or is this the wrong library for the job?

**Comment by kbond** [comment]
Yeah, that could be useful and should be a simple enough command. To clarify, you can't use doctrine fixtures because you require the amount to be dynamic?

For the command, what about: `bin/console foundry:generate App\Factory\UserFactory 50` (first arg the factory class, second arg the amount)?

**Comment by wouterj** [comment]
> you can't use doctrine fixtures because you require the amount to be dynamic?

Yes, exactly. And I want to know some of the data that is generated (e.g. the password of our fixtures are static, but the usernames are faker-generated). So the command would have an `--format=json` option (or the like) to see the JSON serialize of the generated entities.

> For the command, what about: bin/console foundry:generate App\Factory\UserFactory 50 (first arg the factory class, second arg the amount)?

Also fine by me. I often prefer option names over arguments to be more precise about what that "50" means, but arguments for this function are more common the Symfony CLI indeed.

**Comment by kbond** [comment]
> what that "50" means

what about `bin/console foundry:generate App\Factory\UserFactory --amount=50` (amount would be an optional option that defaults to 1)

> So the command would have an --format=json option

So the command would output all the generated entities as json?

**Comment by wouterj** [comment]
> So the command would output all the generated entities as json?

Maybe it can optionally integrate with serializer? Normally it would just output "created x entities" and if `--format` is passed, the serializer is called with the entities and the specified formatter.

I'm not really sure here on the scope of the command (maybe it's easier to discuss these things if I build a small MVP command). But in my use-case, it would be great to get information about the generated entities.

**Comment by kbond** [comment]
> Maybe it can optionally integrate with serializer?

Yes, this is exactly what I was thinking.

> maybe it's easier to discuss these things if I build a small MVP command

Yep, go ahead!

**Comment by wouterj** [comment]
For your information, I didn't start working on this as it didn't turn out to be useful in our case. We needed entities is specific states and with specific dependencies, which is impossible to achieve in such a naive generate command.
We ended up creating our own command that used the factories, which worked perfectly and wasn't very hard to create.
